# Experimento de recortes: Docling vs visión directa

Notebook correspondiente a la **sección 4.3 de la memoria del TFM**, que documenta el experimento que justifica la estrategia de segmentación de imágenes adoptada en `imagen_pipeline.ipynb`.

## Pregunta de investigación

Cuando un estado financiero llega como imagen que comprime balance y PyG completos en un único plano visual, hay dos formas de extraer las partidas:

1. **Docling + LLM textual**: Docling extrae la estructura tabular mediante OCR y layout detection, y un LLM de texto identifica las partidas a partir del índice resultante.
2. **LLM multimodal de visión directa**: se pasa la imagen directamente a un modelo con capacidades de visión y se le pide que extraiga las partidas con sus valores.

El experimento evalúa ambos enfoques aplicando 0, 2, 3 y 4 recortes horizontales sobre la misma imagen, para determinar cuál es más robusto y cuál es el número óptimo de segmentos.

## Imagen de prueba

**Grifols, S.A.** — exportación directa del Excel de SABI a PNG que comprime balance consolidado y cuenta de PyG de tres ejercicios (2022, 2023, 2024) en una sola imagen. Se trata de un caso extremo de densidad: decenas de epígrafes jerárquicos, tres columnas de valores numéricos y cabeceras de metadatos coexisten en un único plano visual comprimido.

Se trabaja con dos versiones de la misma imagen:
- **Imagen densa** (`excel_balance.png`): exportación directa con la máxima densidad de información.
- **Imagen limpia** (`excel_balance (limpio).png`): misma imagen con mayor espaciado entre filas.

## Herramientas evaluadas

| Herramienta | Descripción |
|---|---|
| **Docling** (IBM) | Extracción estructurada de tablas con OCR (RapidOCR) y detección de layout. |
| **llama-4-scout-17b** (Meta/Groq) | Modelo multimodal con capacidades de visión, accesible gratis vía API de Groq. |

> Los modelos de mayor capacidad de OpenAI o Anthropic resuelven la extracción de visión directa sin problemas, pero el experimento busca una solución viable sin dependencia de modelos de pago. `llama-4-scout` es el modelo de visión gratuito más capaz disponible en Groq en el momento del experimento.

---

---

## Parte 1 — Docling con distinto número de recortes

### Hipótesis

Docling usa un modelo de detección de layout que necesita una separación visual mínima entre filas para identificarlas como entidades independientes. Cuando la imagen es muy densa, esa separación es inferior al umbral del modelo y varias filas adyacentes quedan fusionadas en una sola celda del DataFrame resultante.

**Si se segmenta la imagen en trozos horizontales antes de pasarla a Docling, cada trozo tiene menos filas y la separación relativa entre ellas aumenta. A más recortes, mejor debería ser la extracción.**

Se evalúan 4 configuraciones sobre la misma imagen: sin recortes (imagen completa), 2 recortes (mitades), 3 recortes (tercios) y 4 recortes (cuartos). En todas las configuraciones se añade un solapamiento del 5% en cada extremo del trozo para evitar que filas en la zona de corte queden partidas entre dos fragmentos.

### Imagen 1 — Exportación con máxima densidad

Primera prueba sobre la imagen más densa: balance y PyG comprimidos al máximo, columnas muy estrechas, separación mínima entre filas.

#### Celda 1 — Setup: carga de librerías, función de recorte y ejecución

Define `recortar_y_escalar`: recorta la imagen entre `top_pct` y `bottom_pct` (con overlap del 5% en cada extremo), escala el resultado ×2 con interpolación `LANCZOS` para mejorar la resolución que recibe RapidOCR, y guarda el trozo en disco.

Define `procesar_y_mostrar`: pasa cada trozo por `DocumentConverter` de Docling y muestra la tabla resultante para inspección visual.

> **Output:** confirmación de que la imagen se ha cargado correctamente y la ruta al fichero.

In [2]:
# ── CELDA 1: configuración ────────────────────────────────────────────────────
from PIL import Image
import pandas as pd
import os
from IPython.display import display
from docling.document_converter import DocumentConverter

# ► CAMBIA ESTA RUTA por la imagen que quieras analizar
RUTA_IMAGEN = r"C:\Users\perdi\Desktop\tfm\TFM PYTHON\RECORTES\excel_balance.png"

OUTPUTS = r"C:\Users\perdi\Desktop\tfm\TFM PYTHON\RECORTES\output recortes"
os.makedirs(OUTPUTS, exist_ok=True)

def recortar_y_escalar(ruta_imagen, top_pct, bottom_pct, escala=2, overlap_pct=0.05):
    img = Image.open(ruta_imagen)
    w, h = img.size
    top    = max(0, int(h * (top_pct - overlap_pct)))
    bottom = min(h, int(h * (bottom_pct + overlap_pct)))
    recorte = img.crop((0, top, w, bottom))
    recorte = recorte.resize((w * escala, (bottom - top) * escala), Image.LANCZOS)
    nombre = os.path.splitext(os.path.basename(ruta_imagen))[0]
    ruta_salida = os.path.join(OUTPUTS, f"{nombre}_exp_trozo_{top_pct}_{bottom_pct}.png")
    recorte.save(ruta_salida)
    return ruta_salida

def procesar_y_mostrar(trozos, etiqueta):
    converter = DocumentConverter()
    print(f"\n{'='*60}")
    print(f"  {etiqueta}")
    print(f"{'='*60}")
    for i, trozo in enumerate(trozos, 1):
        print(f"\n── Trozo {i} ──")
        result = converter.convert(trozo)
        n_tablas = len(result.document.tables)
        print(f"  Tablas detectadas: {n_tablas}")
        if n_tablas == 0:
            print("  (ninguna tabla encontrada)")
        for j, tabla in enumerate(result.document.tables, 1):
            print(f"  · Tabla {j}:")
            df_trozo = tabla.export_to_dataframe()
            df_trozo = pd.DataFrame(
                [df_trozo.columns.tolist()] + df_trozo.values.tolist()
            )
            df_trozo.columns = [f"C{k}" for k in range(df_trozo.shape[1])]
            display(df_trozo)

print("✅ Setup listo. Imagen:", RUTA_IMAGEN)

c:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

✅ Setup listo. Imagen: C:\Users\perdi\Desktop\tfm\TFM PYTHON\RECORTES\excel_balance.png

#### Celda 2 — Experimento: 0, 2, 3 y 4 recortes sobre la imagen densa

Ejecuta el mismo pipeline de Docling con cuatro granularidades distintas y muestra los DataFrames resultantes para cada configuración. Los outputs permiten comparar visualmente cómo evoluciona la calidad de extracción.

**Qué observar en los outputs:**
- **0 recortes (imagen completa):** múltiples filas fusionadas en una misma celda — una celda contiene el texto de dos, tres o más partidas concatenadas. Las columnas de valores también presentan errores de asignación.
- **2 recortes:** mejora notable. Persisten algunas fusiones en las zonas de corte superior e inferior de cada mitad, donde la densidad sigue siendo alta.
- **3 recortes:** la mayoría de partidas aparecen individualizadas. Las fusiones residuales se concentran en los bordes de los trozos.
- **4 recortes:** extracción limpia. Todas las partidas en sus propias filas, valores correctamente asignados a sus columnas de fecha.

In [3]:
# ── CELDA 2: experimento de recortes ─────────────────────────────────────────
# Cada bloque pasa la misma imagen por Docling con distinto número de cortes
# para evidenciar cómo más cortes => docling junta menos filas.

nombre = os.path.splitext(os.path.basename(RUTA_IMAGEN))[0]

# ── 0 recortes: imagen completa sin partir ────────────────────────────────────
img_completa = Image.open(RUTA_IMAGEN)
w, h = img_completa.size
img_escalada = img_completa.resize((w * 2, h * 2), Image.LANCZOS)
ruta_completa = os.path.join(OUTPUTS, f"{nombre}_exp_0recortes.png")
img_escalada.save(ruta_completa)
procesar_y_mostrar([ruta_completa], "SIN RECORTES (0 cortes) — imagen completa")

# ── 2 recortes: mitad superior + mitad inferior ───────────────────────────────
cortes_2 = [(0, 0.50), (0.50, 1.0)]
trozos_2 = [recortar_y_escalar(RUTA_IMAGEN, t, b) for t, b in cortes_2]
procesar_y_mostrar(trozos_2, "2 RECORTES — mitad superior / mitad inferior")

# ── 3 recortes: tres tercios ──────────────────────────────────────────────────
cortes_3 = [(0, 0.33), (0.33, 0.66), (0.66, 1.0)]
trozos_3 = [recortar_y_escalar(RUTA_IMAGEN, t, b) for t, b in cortes_3]
procesar_y_mostrar(trozos_3, "3 RECORTES — tres tercios iguales")

# ── 4 recortes: cuatro cuartos ────────────────────────────────────────────────
cortes_4 = [(0, 0.25), (0.25, 0.50), (0.50, 0.75), (0.75, 1.0)]
trozos_4 = [recortar_y_escalar(RUTA_IMAGEN, t, b) for t, b in cortes_4]
procesar_y_mostrar(trozos_4, "4 RECORTES — cuatro cuartos iguales")

============================================================
  SIN RECORTES (0 cortes) — imagen completa
============================================================

── Trozo 1 ──

[INFO] 2026-05-07 21:39:35,983 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:39:35,993 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-05-07 21:39:35,993 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-05-07 21:39:36,123 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:39:36,126 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-05-07 21:39:36,126 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-05-07 21:39:36,176 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:39:36,188 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
[INFO] 2026-05-07 21:39:36,189 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
Loading weights: 100%|██████████| 770/770 [00:00<00:00, 7062.94it/s]
Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3,C4,C5,C6
0,ROW,CO C1 Balance/Estado de resultad nan,C2 nan,nan,S nan,C6 nan,C7 nan
1,3 4,Cuentas No Consolidadas nan,nan 31/12/2024 mil EUR,nan,31/12/2023,nan,31/12/2022
2,nan nan nan,nan nan,nan nan 12 meses nan,nan 12 meses,mil EUR nan,nan 12 meses,mil EUR nan
3,5 9 7,nan,Aprobado nan Normal PGC 2007 nan,Aprobado Normal PGC 2007,nan nan,Aprobado Normal PGC 2007,nan nan
4,8,nan nan Activo nan,nan nan,nan,nan,nan,nan
...,...,...,...,...,...,...,...
67,115 116,1. Importe neto de la cifr nan,nan 701053 nan,619242,nan,488639,nan nan
68,117,a) Ventas nan,n.d. nan,n.d.,nan,n.d.,nan
69,118,b) Prestaciones de servic nan 2. Variacion de ...,247819 nan,242824 n.d. 2312,nan nan nan,199311 n.d.,nan nan
70,119,,nan,,,5478,
71,,,n.d. 5213 nan,,,,

[INFO] 2026-05-07 21:40:10,505 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:40:10,509 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-05-07 21:40:10,510 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx

============================================================
  2 RECORTES — mitad superior / mitad inferior
============================================================

── Trozo 1 ──

[INFO] 2026-05-07 21:40:10,609 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:40:10,611 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-05-07 21:40:10,611 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-05-07 21:40:10,664 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:40:10,676 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
[INFO] 2026-05-07 21:40:10,677 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
Loading weights: 100%|██████████| 770/770 [00:00<00:00, 10119.68it/s]
Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3,C4,C5,C6,C7
0,ROW,Co,C1,C2,C3,C4 C5,C6,C7
1,1,Balance/Estado de resultad,nan,nan nan,nan,nan,nan,nan
2,3,Cuentas No Consolidadas,nan,,31/12/2024 nan,31/12/2023,nan,31/12/2022
3,4,nan,nan,nan nan mil EUR,nan,mil EUR,nan,mil EUR
4,5,nan,nan,12meses nan,12 meses,nan,12meses,nan
...,...,...,...,...,...,...,...,...
58,61,VI Resultado del ejercicio,nan,nan nan nan,-246735,nan,-266296,nan nan
59,62 63,VIl Dividendo a cuenta) VIlI Otrosinstrumentosd,nan,n.d.,n.d. 8282,nan,n.d.,nan
60,,A-2)Ajustes por cambios,nan,6647 nan,,nan,7303,nan
61,65,,nan,-18391,56752,nan,57798,
62,66,IActivosno corrientesy,nan,nan n.d. nan,n.d.,nan,n.d.,nan

── Trozo 2 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3,C4,C5,C6,C7
0,51,1Capital,nan,119604,nan,119604 nan,119604,nan
1,52,1. Capital escriturado,nan,119604,119604,nan,119604,nan
2,53,2.(Capital no exigido),nan,nan n.d. nan,n.d.,nan,n.d.,nan
3,54,Il Prima de emision,nan,910728 nan,910728,nan,910728,nan
4,55,1. Reserva de revalorizad,nan,n.d. nan,n.d.,nan,n.d.,nan
...,...,...,...,...,...,...,...,...
58,115,1. Importe neto de la cifr,nan,701053 nan,619242,nan,488639,
59,116 117,a)Ventas,nan,n.d. nan,n.d.,nan,n.d.,nan nan
60,,b) Prestaciones de servic,nan,247819 nan,242824,nan,199311,
61,118,2.Variacion de existencia,nan,n.d. nan nan,n.d.,nan,n.d.,nan
62,119,3. Trabajos realizados por,nan,5213,2312,nan,5478,nan

[INFO] 2026-05-07 21:41:01,443 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:41:01,447 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-05-07 21:41:01,448 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-05-07 21:41:01,564 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:41:01,566 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-05-07 21:41:01,566 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx

============================================================
  3 RECORTES — tres tercios iguales
============================================================

── Trozo 1 ──

[INFO] 2026-05-07 21:41:01,617 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:41:01,627 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
[INFO] 2026-05-07 21:41:01,628 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
Loading weights: 100%|██████████| 770/770 [00:00<00:00, 11754.01it/s]
Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3,C4,C5,C6,C7,C8
0,ROW,Co,C1,C2,,C4,C5,C6,C7
1,1,Balance/Estadoderesultad,nan,nan,nan,nan,nan,nan,nan
2,3,Cuentas No Consolidadas,nan,nan,31/12/2024,nan,31/12/2023,nan,31/12/2022
3,4,nan,nan,nan,mil EUR,nan,mil EUR,nan,mil EUR
4,5,nan,nan,12 meses,nan,12 meses,nan,12 meses,nan
5,6,nan,nan,Aprobado,nan,Aprobado,nan,Aprobado,nan
6,7,nan,nan,Normal PGC 2007,nan,Normal PGC 2007,nan,Normal PGC 2007,nan
7,8,Activo,nan,nan,nan,nan,nan,nan,nan
8,9,A)Activono corriente,nan,12497590,nan,11416223,nan,12647002,nan
9,10,I Inmovilizado intangible,nan,23959,nan,19941,nan,23213,nan
10,11,1.Fondo de comercio de,nan,n.d.,nan,n.d.,nan,n.d.,nan
11,12,2. Investigacion,nan,n.d.,nan,n.d.,nan,n.d.,nan
12,13,3.Propiedad intelectual,nan,n.d.,nan,n.d.,nan,n.d.,nan
13,14,5.Otro inmovilizado inta,nan,n.d.,nan,n.d.,nan,n.d.,nan
14,15,Il Inmovilizado material,nan,31989,nan,32524,nan,35545,nan
15,16,1.Terrenos y construccio,nan,11064,nan,11151,nan,11239,nan
16,17,2.Instalaciones tecnicas,nan,16685,nan,14926,nan,18207,nan
17,18,3.Inmovilizado en curso,nan,4240,nan,6447,nan,6609,nan
18,19,Ill Inversiones inmobiliaria,nan,102332,nan,108977,nan,80458,nan
19,20,IV Inversiones en empres,nan,11838151,nan,11202474,nan,12469437,nan
20,21,1. Participaciones puesta,nan,n.d.,nan,n.d.,nan,n.d.,nan
21,22,2.Creditos a sociedades,nan,n.d.,nan,n.d.,nan,n.d.,nan
22,23,3. Otros activos financier,nan,n.d.,nan,n.d.,nan,n.d.,nan
23,24,4. Otras inversiones,nan,n.d.,nan,n.d.,nan,n.d.,nan
24,25,VInversionesfinancieras,nan,418896,nan,2714,nan,29199,nan
25,26,VI Activos por impuesto d,nan,82263,nan,49593,nan,9150,nan
26,27,VllIDeudas comercialesn,nan,n.d.,nan,n.d.,nan,n.d.,nan
27,29,B)Activo corriente,nan,342446,nan,1544994,nan,246099,nan
28,30,IActivosno corrientesma,nan,n.d.,nan,1360089,nan,n.d.,nan
29,31,IExistencias,nan,13342,nan,12333,nan,11439,nan
30,32,IlIDeudores comerciales,nan,79885,nan,79873,nan,72869,nan
31,33,1.Clientes por ventasy,nan,1496,nan,581,nan,833,nan
32,34,a) Clientes por ventasy,nan,n.d.,nan,n.d.,nan,n.d.,nan
33,35,b) Clientes porventasy,nan,1496,nan,581,nan,833,nan
34,36,2. Sociedades puestas er,nan,n.d.,nan,n.d.,nan,n.d.,nan
35,37,3. Activos por impuesto d,nan,16453,nan,12303,nan,2486,nan
36,38,4.Otros deudores,nan,n.d.,nan,n.d.,nan,n.d.,nan

── Trozo 2 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3,C4,C5,C6
0,23,3.Otros activosfinancier,n.d.,nan,n.d.,nan,nan
1,24,nan nan,n.d.,nan n.d.,nan,n.d. n.d.,nan
2,25,4.Otras inversiones VInversionesfinancieras nan,418896,nan 2714,nan,29199,nan
3,26,VIActivosporimpuestod nan,82263,nan 49593,nan,9150,nan
4,27,VllIDeudas comercialesn nan,n.d.,nan n.d.,nan,n.d.,nan
...,...,...,...,...,...,...,...
62,92,1.Provisiones por derech nan,n.d.,nan,nan,n.d.,nan
63,93,2.Otras provisiones nan,79947,n.d. nan 14000,nan,7000,nan
64,94,IlDeudas a corto plazo nan 1.Obliaacionesvotro...,68347 38907,nan 106970 30170,,74786 12554,nan nan
65,,,,,nan nan,,
66,95,,,nan,,,

── Trozo 3 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3,C4,C5,C6,C7,C8
0,79 80,iod 4. Otros pasivos financiel,ran nan,21 n.d.,nan nan,27 n.d.,nar nan,52 n.d.,ueu nan
1,81,Il Deudas con empresas,nan,4276854,nan,4673555,nan,6419171,nan
2,82,1.Deudas con sociedade,nan,n.d.,nan,n.d.,nan,n.d.,nan
3,83,2. Otras deudas,nan,n.d.,nan,n.d.,nan,n.d.,nan
4,84,IV Pasivos por impuesto d,nan,3244,nan,4907,nan,2580,nan
5,85,VPeriodificacionesalargd,nan,n.d.,nan,n.d.,nan,n.d.,nan
6,86,VI Acreedores comerciale,nan,n.d.,nan,n.d.,nan,n.d.,nan
7,87,VllDeuda con caracteristi,nan,n.d.,nan,n.d.,nan,n.d.,nan
8,89,C)Pasivo corriente,nan,313933,nan,298105,nan,226493,nan
9,90,IPasivos vinculados con a,nan,n.d.,nan,n.d.,nan,n.d.,nan
10,91,IlProvisiones a cortoplaz,nan,79947,nan,14000,nan,7000,nan
11,92,1. Provisiones por derech,nan,n.d.,nan,n.d.,nan,n.d.,nan
12,93,2. Otras provisiones,nan,79947,nan,14000,nan,7000,nan
13,94,IlIDeudas a corto plazo,nan,68347,nan,106970,nan,74786,nan
14,95,1.Obligaciones y otrosv,nan,38907,nan,30170,nan,12554,nan
15,96,2.Deudas con entidades,nan,29383,nan,68542,nan,60899,nan
16,97,3.Acreedores por arrend,nan,n.d.,nan,25,nan,391,nan
17,98,4.Otros pasivos financie,nan,n.d.,nan,n.d.,nan,n.d.,nan
18,99,IV Deudas con empresas,nan,62437,nan,64699,nan,61720,nan
19,100,1. Deudas con sociedade,nan,n.d.,nan,n.d.,nan,n.d.,nan
20,101,2. Otras deudas,nan,n.d.,nan,n.d.,nan,n.d.,nan
21,102,VAcreedores comerciales,nan,94624,nan,112436,nan,82987,nan
22,103,1.Proveedores,nan,65750,nan,69365,nan,58812,nan
23,104,a)Proveedoresalargop,nan,n.d.,nan,n.d.,nan,n.d.,nan
24,105,b)Proveedoresa cortop,nan,65750,nan,69365,nan,58812,nan
25,106,"2.Proveedores,empresa",nan,n.d.,nan,n.d.,nan,n.d.,nan
26,107,3.Pasivos por impuesto,nan,n.d.,nan,n.d.,nan,n.d.,nan
27,108,4.Otros acreedores,nan,n.d.,nan,n.d.,nan,n.d.,nan
28,109,VI Periodificaciones a cort,nan,8578,nan,n.d.,nan,n.d.,nan
29,110,VllDeuda con caracteristi,nan,n.d.,nan,n.d.,nan,n.d.,nan
30,111,Totalpatrimonionetoypa,nan,12840036,nan,12961217,nan,12893101,nan
31,113,Cuenta deperdidasy gana,nan,nan,nan,nan,nan,nan,nan
32,114,A)Operacionescontinuad,nan,nan,nan,nan,nan,nan,nan
33,115,1. Importe neto de la cifra,nan,701053,nan,619242,nan,488639,nan
34,116,a)Ventas,nan,n.d.,nan,n.d.,nan,n.d.,nan
35,117,b) Prestaciones de servic,nan,247819,nan,242824,nan,199311,nan
36,118,2.Variacion de existencia,nan,n.d.,nan,n.d.,nan,n.d.,nan

[INFO] 2026-05-07 21:41:57,301 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:41:57,306 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-05-07 21:41:57,307 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-05-07 21:41:57,398 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:41:57,400 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-05-07 21:41:57,400 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-05-07 21:41:57,447 [RapidOCR] base.py:22: Using engine_name: onnxruntime

============================================================
  4 RECORTES — cuatro cuartos iguales
============================================================

── Trozo 1 ──

[INFO] 2026-05-07 21:41:57,458 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
[INFO] 2026-05-07 21:41:57,458 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
Loading weights: 100%|██████████| 770/770 [00:00<00:00, 10906.40it/s]
Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3,C4,C5,C6,C7,C8
0,ROW,Co,C1,C2,C3,C4,C5,C6,C7
1,1,Balance/Estadoderesultad,nan,nan,nan,nan,nan,nan,nan
2,3,CuentasNo Consolidadas,nan,nan,31/12/2024,nan,31/12/2023,nan,31/12/2022
3,4,nan,nan,nan,mil EUR,nan,mil EUR,nan,mil EUR
4,5,nan,nan,12 meses,nan,12 meses,nan,12 meses,nan
5,6,nan,nan,Aprobado,nan,Aprobado,nan,Aprobado,nan
6,7,nan,nan,Normal PGC 2007,nan,Normal PGC 2007,nan,Normal PGC2007,nan
7,8,Activo,nan,nan,nan,nan,nan,nan,nan
8,9,A)Activono corriente,nan,12497590,nan,11416223,nan,12647002,nan
9,10,IInmovilizadointangible,nan,23959,nan,19941,nan,23213,nan
10,11,1.Fondo de comercio de,nan,n.d.,nan,n.d.,nan,n.d.,nan
11,12,2. Investigacion,nan,n.d.,nan,n.d.,nan,n.d.,nan
12,13,3.Propiedad intelectual,nan,n.d.,nan,n.d.,nan,n.d.,nan
13,14,5. Otro inmovilizado inta,nan,n.d.,nan,n.d.,nan,n.d.,nan
14,15,Il Inmovilizadomaterial,nan,31989,nan,32524,nan,35545,nan
15,16,1.Terrenos y construccio,nan,11064,nan,11151,nan,11239,nan
16,17,2.Instalaciones tecnicas,nan,16685,nan,14926,nan,18207,nan
17,18,3.Inmovilizadoen curso,nan,4240,nan,6447,nan,6099,nan
18,19,Ill Inversionesinmobiliaria,nan,102332,nan,108977,nan,80458,nan
19,20,IVInversionesenempres,nan,11838151,nan,11202474,nan,12469437,nan
20,21,1.Participaciones puesta,nan,n.d.,nan,n.d.,nan,n.d.,nan
21,22,2.Creditos a sociedades,nan,n.d.,nan,n.d.,nan,n.d.,nan
22,23,3. Otros activos financier,nan,n.d.,nan,n.d.,nan,n.d.,nan
23,24,4.Otras inversiones,nan,n.d.,nan,n.d.,nan,n.d.,nan
24,25,VInversionesfinancieras,nan,418896,nan,2714,nan,29199,nan

── Trozo 2 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3,C4,C5,C6,C7,C8
0,0,1,2,3,4,5,6,7,8
1,10 11,1.Fondo de comercio de,ran nan,23959 n.d.,ran nan,17661 n.d.,nar nan,23213 n.d.,ueu nan
2,12,2. Investigacion,nan,n.d.,nan,n.d.,nan,n.d.,nan
3,13,3.Propiedad intelectual,nan,n.d.,nan,n.d.,nan,n.d.,nan
4,14,5.Otro inmovilizado inta,nan,n.d.,nan,n.d.,nan,n.d.,nan
5,15,I Inmovilizadomaterial,nan,31989,nan,32524,nan,35545,nan
6,16,1. Terrenos y construccio,nan,11064,nan,11151,nan,11239,nan
7,17,2.Instalaciones tecnicas,nan,16685,nan,14926,nan,18207,nan
8,18,3.Inmovilizado en curso,nan,4240,nan,6447,nan,6099,nan
9,19,Il Inversiones inmobiliari,nan,102332,nan,108977,nan,80458,nan
10,20,IV Inversiones enempres,nan,11838151,nan,11202474,nan,12469437,nan
11,21,1.Participaciones puesta,nan,n.d.,nan,n.d.,nan,n.d.,nan
12,22,2.Creditos a sociedades,nan,n.d.,nan,n.d.,nan,n.d.,nan
13,23,3. Otros activos financier,nan,n.d.,nan,n.d.,nan,n.d.,nan
14,24,4.Otras inversiones,nan,n.d.,nan,n.d.,nan,n.d.,nan
15,25,VInversionesfinancieras,nan,418896,nan,2714,nan,29199,nan
16,26,V1 Activos porimpuesto d,nan,82263,nan,49593,nan,9150,nan
17,27,VllI Deudas comerciales n,nan,n.d.,nan,n.d.,nan,n.d.,nan
18,29,B)Activo corriente,nan,342446,nan,1544994,nan,246099,nan
19,30,IActivosno corrientesma,nan,n.d.,nan,1360089,nan,n.d.,nan
20,31,IExistencias,nan,13342,nan,12333,nan,11439,nan
21,32,Ill Deudores comerciales,nan,79885,nan,79873,nan,72869,nan
22,33,1.Clientes por ventas y,nan,1496,nan,581,nan,833,nan
23,34,a)Clientes por ventasy,nan,n.d.,nan,n.d.,nan,n.d.,nan
24,35,b) Clientes por ventasy,nan,1496,nan,581,nan,833,nan
25,36,2.Sociedades puestas er,nan,n.d.,nan,n.d.,nan,n.d.,nan
26,37,3. Activos por impuestod,nan,16453,nan,12303,nan,2486,nan
27,38,4.Otros deudores,nan,n.d.,nan,n.d.,nan,n.d.,nan
28,39,IV Inversiones en empres,nan,228981,nan,47884,nan,123033,nan
29,40,1.Creditos a empresas p,nan,n.d.,nan,n.d.,nan,n.d.,nan
30,41,2. Otros activos financier,nan,n.d.,nan,n.d.,nan,n.d.,nan
31,42,3. Otras inversiones,nan,n.d.,nan,n.d.,nan,n.d.,nan
32,43,V Inversiones financieras,nan,2752,nan,20917,nan,11569,nan
33,44,VI Periodificaciones a cort,nan,16203,nan,11031,nan,13511,nan
34,45,VllEfectivoyotrosactivo,nan,1283,nan,12867,nan,13678,nan
35,46,Total activo (A + B),nan,12840036,nan,12961217,nan,12893101,nan
36,48,Pasivo,nan,nan,nan,nan,nan,nan,nan
37,49,A)Patrimonio neto,nan,1953852,nan,2101487,nan,2343125,nan
38,50,A-1) Fondos propios,nan,1972243,nan,2044735,nan,2285248,nan
39,51,1Capital,nan,119604,nan,119604,nan,119604,nan
40,52,1.Capital escriturado,nan,119604,nan,119604,nan,119604,nan
41,53,2.(Capital no exigido),nan,n.d.,nan,n.d.,nan,n.d.,nan
42,54,I Prima de emision,nan,910728,nan,910728,nan,910728,nan
43,55,1.Reserva de revalorizad,nan,n.d.,nan,n.d.,nan,n.d.,nan
44,56,2.Reserva de capitalizac,nan,n.d.,nan,n.d.,nan,n.d.,nan
45,57,3. Otras reservas,nan,n.d.,nan,n.d.,nan,n.d.,nan
46,58,IlI Reservas y resultados,nan,n.d.,nan,n.d.,nan,n.d.,nan
47,59,IV (Acciones y participacid,nan,-134448,nan,-152748,nan,-162220,nan
48,60,V Otras aportacionesde,nan,n.d.,nan,n.d.,nan,n.d.,nan
49,61,VI Resultado delejercicio,nan,-83138,nan,-246735,nan,-266296,nan
50,62,Vll Dividendoa cuenta),nan,n.d.,nan,n.d.,nan,n.d.,nan
51,63 65,VIlI Otrosinstrumentosd A-2) Ajustes por cambios,nan,6647,nan nan,8282 56752,nan nan,7303 57798,nan nan
52,,IActivosno corrientesy,nan,-18391,,,,n.d.,
53,66,,nan,n.d.,nan,n.d.,nan,,nan

── Trozo 3 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3,C4,C5,C6,C7,C8
0,51,1Capital,nan,119604,nan,119604,nan,119604,nan
1,52,1. Capital escriturado,nan,119604,nan,119604,nan,119604,nan
2,53,2. (Capital no exigido),nan,n.d.,nan,n.d.,nan,n.d.,nan
3,54,I Prima de emision,nan,910728,nan,910728,nan,910728,nan
4,55,1. Reserva de revalorizad,nan,n.d.,nan,n.d.,nan,n.d.,nan
5,56,2.Reserva de capitalizac,nan,n.d.,nan,n.d.,nan,n.d.,nan
6,57,3.Otras reservas,nan,n.d.,nan,n.d.,nan,n.d.,nan
7,58,Il Reservas y resultadosd,nan,n.d.,nan,n.d.,nan,n.d.,nan
8,59,IV (Acciones y participacid,nan,-134448,nan,-152748,nan,-162220,nan
9,60,V Otras aportacionesde,nan,n.d.,nan,n.d.,nan,n.d.,nan
10,61,VI Resultado del ejercicio,nan,-83138,nan,-246735,nan,-266296,nan
11,62,VlIDividendoa cuenta),nan,n.d.,nan,n.d.,nan,n.d.,nan
12,63,VIlI Otros instrumentosd,nan,6647,nan,8282,nan,7303,nan
13,65,A-2) Ajustes por cambios,nan,-18391,nan,56752,nan,57798,nan
14,66,IActivosnocorrientesy,nan,n.d.,nan,n.d.,nan,n.d.,nan
15,67,IDiferenciadeconversio,nan,n.d.,nan,n.d.,nan,n.d.,nan
16,68,IlI Otros,nan,n.d.,nan,n.d.,nan,n.d.,nan
17,70,"A-3) Subvenciones,donad",nan,n.d.,nan,n.d.,nan,79,nan
18,72,A-4) Socios externos,nan,n.d.,nan,n.d.,nan,n.d.,nan
19,74,B)Pasivono corriente,nan,10572251,nan,10561625,nan,10323483,nan
20,75,1Provisiones a largo plazd,nan,3217,nan,3838,nan,n.d.,nan
21,76,I Deudasalargoplazo,nan,6288936,nan,5879325,nan,3901732,nan
22,77,1. Obligaciones y otros v,nan,5387413,nan,4571059,nan,2556641,nan
23,78,2.Deudas con entidades,nan,901345,nan,1308026,nan,1340473,nan
24,79,3.Acreedores por arrend,nan,21,nan,27,nan,52,nan
25,80,4. Otros pasivos financie,nan,n.d.,nan,n.d.,nan,n.d.,nan
26,81,IlDeudas con empresas,nan,4276854,nan,4673555,nan,6419171,nan
27,82,1. Deudas con sociedade,nan,n.d.,nan,n.d.,nan,n.d.,nan
28,83,2. Otras deudas,nan,n.d.,nan,n.d.,nan,n.d.,nan
29,84,IV Pasivos porimpuesto d,nan,3244,nan,4907,nan,2580,nan
30,85,VPeriodificacionesalarg,nan,n.d.,nan,n.d.,nan,n.d.,nan
31,86,VI Acreedores comerciale,nan,n.d.,nan,n.d.,nan,n.d.,nan
32,87,VlIDeudaconcaracteristi,nan,n.d.,nan,n.d.,nan,n.d.,nan
33,89,C)Pasivo corriente,nan,313933,nan,298105,nan,226493,nan
34,06,IPasivosvinculados cona,nan,n.d.,nan,n.d.,nan,n.d.,nan
35,91,IIProvisionesa cortoplaz,nan,79947,nan,14000,nan,7000,nan
36,92,1. Provisiones por derech,nan,n.d.,nan,n.d.,nan,n.d.,nan
37,93,2. Otras provisiones,nan,79947,nan,14000,nan,7000,nan
38,94 95,Il Deudasa cortoplazo,nan,68347,nan,106970,nan,74786,nan
39,,1. Obligaciones y otros v,nan,38907,nan,30170,nan,12554,nan
40,96,2. Deudas con entidades,nan,29383,nan,68542,nan,60899,nan
41,97,3. Acreedores por arrend,nan,n.d.,nan,25,nan,391,nan
42,98,4. Otros pasivos financie,nan,n.d.,nan,n.d.,nan,n.d.,nan
43,99,IV Deudas con empresas,nan,62437,nan,64699,nan,61720,nan
44,100,1.Deudas con sociedade,nan,n.d.,nan,n.d.,nan,n.d.,nan
45,101,2. Otras deudas,nan,n.d.,nan,n.d.,nan,n.d.,nan
46,102,VAcreedores comerciales,nan,94624,nan,112436,nan,82987,nan
47,103,1.Proveedores,nan,65750,nan,69365,nan,58812,nan
48,104,a)Proveedores alargop,nan,n.d.,nan,n.d.,nan,n.d.,nan
49,105,b)Proveedores a cortop,,65750,,,,58812,nan
50,106,"2.Proveedores,empresa",nan nan,n.d.,nan nan,69365 n.d.,nan nan,n.d.,nan nan
51,107 108,3.Pasivos por impuesto 4. Otros acreedores,nan nan,n.d. n.d.,nan nan,n.d. n.d.,nan nan,n.d. n.d. nd,nan

── Trozo 4 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3,C4,C5,C6,C7,C8
0,0,1,2,3,4,5,6,7,8
1,94,mDeudasacortoplazo,nan,68347,nan,106970,nan,74786,nan
2,95,1.obligacionesy otrosv,nan,38907,nan,30170,nan,12554,nan
3,96,2. Deudas con entidades,nan,29383,nan,68542,nan,60899,nan
4,97,3. Acreedores por arrend,nan,n.d.,nan,25,nan,391,nan
5,98,4. Otros pasivos financier,nan,n.d.,nan,n.d.,nan,n.d.,nan
6,99,IV Deudas con empresas,nan,62437,nan,64699,nan,61720,nan
7,100,1. Deudas con sociedade,nan,n.d.,nan,n.d.,nan,n.d.,nan
8,101,2. Otras deudas,nan,n.d.,nan,n.d.,nan,n.d.,nan
9,102,VAcreedorescomerciales,nan,94624,nan,112436,nan,82987,nan
10,103,1.Proveedores,nan,65750,nan,69365,nan,58812,nan
11,104,a)Proveedores a largop,nan,n.d.,nan,n.d.,nan,n.d.,nan
12,105,b)Proveedores a cortop,nan,65750,nan,69365,nan,58812,nan
13,106,"2.Proveedores,empresa",nan,n.d.,nan,n.d.,nan,n.d.,nan
14,107,3.Pasivos por impuesto,nan,n.d.,nan,n.d.,nan,n.d.,nan
15,108,4.Otros acreedores,nan,n.d.,nan,n.d.,nan,n.d.,nan
16,109,VI Periodificacionesa cort,nan,8578,nan,n.d.,nan,n.d.,nan
17,110,VlIDeudaconcaracteristi,nan,n.d.,nan,n.d.,nan,n.d.,nan
18,111,Totalpatrimonionetoypa,nan,12840036,nan,12961217,nan,12893101,nan
19,113,Cuenta deperdidasy gana,nan,nan,nan,nan,nan,nan,nan
20,114,A)Operacionescontinuad,nan,nan,nan,nan,nan,nan,nan
21,115,1. Importe neto de la cifra,nan,701053,nan,619242,nan,488639,nan
22,116,a)Ventas,nan,n.d.,nan,n.d.,nan,n.d.,nan
23,117,b) Prestaciones de servic,nan,247819,nan,242824,nan,199311,nan
24,118,2.Variacion de existencia,nan,n.d.,nan,n.d.,nan,n.d.,nan
25,119,3. Trabajos realizados por,nan,5213,nan,2312,nan,5478,nan

#### Conclusión — Imagen densa

> Los outputs de la celda anterior confirman la hipótesis: **a mayor número de recortes, menor densidad de filas por trozo y mejor calidad de extracción con Docling**.
>
> El solapamiento del 5% entre trozos garantiza que ninguna partida quede perdida en la zona de corte, a costa de que algunas aparezcan duplicadas en dos trozos consecutivos — duplicidad fácilmente gestionable en la fase de construcción del DataFrame final.
>
> Con 4 recortes la imagen densa queda completamente legible para Docling. Este es el número adoptado en `imagen_pipeline.ipynb` para este tipo de imagen.

### Imagen 2 — Exportación con mayor espaciado

Segunda prueba con la versión más limpia de la imagen, que tiene mayor separación entre filas. Permite verificar que la mejora progresiva con más recortes se mantiene con imágenes de mejor calidad y comprobar si el número óptimo de recortes cambia.

#### Celda 3 — Setup con imagen limpia

Mismo setup que la celda 1, apuntando a `excel_balance (limpio).png`.

In [4]:
# ── CELDA 1: configuración ────────────────────────────────────────────────────
from PIL import Image
import pandas as pd
import os
from IPython.display import display
from docling.document_converter import DocumentConverter

# ► CAMBIA ESTA RUTA por la imagen que quieras analizar
RUTA_IMAGEN = r"C:\Users\perdi\Desktop\tfm\TFM PYTHON\RECORTES\excel_balance (limpio).png"

OUTPUTS = r"C:\Users\perdi\Desktop\tfm\TFM PYTHON\RECORTES\output recortes"
os.makedirs(OUTPUTS, exist_ok=True)

def recortar_y_escalar(ruta_imagen, top_pct, bottom_pct, escala=2, overlap_pct=0.05):
    img = Image.open(ruta_imagen)
    w, h = img.size
    top    = max(0, int(h * (top_pct - overlap_pct)))
    bottom = min(h, int(h * (bottom_pct + overlap_pct)))
    recorte = img.crop((0, top, w, bottom))
    recorte = recorte.resize((w * escala, (bottom - top) * escala), Image.LANCZOS)
    nombre = os.path.splitext(os.path.basename(ruta_imagen))[0]
    ruta_salida = os.path.join(OUTPUTS, f"{nombre}_exp_trozo_{top_pct}_{bottom_pct}.png")
    recorte.save(ruta_salida)
    return ruta_salida

def procesar_y_mostrar(trozos, etiqueta):
    converter = DocumentConverter()
    print(f"\n{'='*60}")
    print(f"  {etiqueta}")
    print(f"{'='*60}")
    for i, trozo in enumerate(trozos, 1):
        print(f"\n── Trozo {i} ──")
        result = converter.convert(trozo)
        n_tablas = len(result.document.tables)
        print(f"  Tablas detectadas: {n_tablas}")
        if n_tablas == 0:
            print("  (ninguna tabla encontrada)")
        for j, tabla in enumerate(result.document.tables, 1):
            print(f"  · Tabla {j}:")
            df_trozo = tabla.export_to_dataframe()
            df_trozo = pd.DataFrame(
                [df_trozo.columns.tolist()] + df_trozo.values.tolist()
            )
            df_trozo.columns = [f"C{k}" for k in range(df_trozo.shape[1])]
            display(df_trozo)

print("✅ Setup listo. Imagen:", RUTA_IMAGEN)

✅ Setup listo. Imagen: C:\Users\perdi\Desktop\tfm\TFM PYTHON\RECORTES\excel_balance (limpio).png

#### Celda 4 — Experimento: 0, 2, 3 y 4 recortes sobre la imagen limpia

Misma batería de configuraciones que en la imagen densa. Con mayor espaciado entre filas, Docling ya lo hace mejor desde 0 recortes, pero la mejora progresiva sigue siendo visible y 4 recortes sigue siendo el punto de máxima limpieza.

**Qué observar respecto a la imagen densa:**
- El punto de partida (0 recortes) es mejor: menos fusiones y valores más consistentes.
- La curva de mejora es más suave: ya con 2 recortes el resultado es usable.
- Con 4 recortes el resultado es idéntico al de la imagen densa con 4 recortes, confirmando que la estrategia converge independientemente de la calidad inicial de la imagen.

In [5]:
# ── CELDA 2: experimento de recortes ─────────────────────────────────────────
# Cada bloque pasa la misma imagen por Docling con distinto número de cortes
# para evidenciar cómo más cortes => docling junta menos filas.

nombre = os.path.splitext(os.path.basename(RUTA_IMAGEN))[0]

# ── 0 recortes: imagen completa sin partir ────────────────────────────────────
img_completa = Image.open(RUTA_IMAGEN)
w, h = img_completa.size
img_escalada = img_completa.resize((w * 2, h * 2), Image.LANCZOS)
ruta_completa = os.path.join(OUTPUTS, f"{nombre}_exp_0recortes.png")
img_escalada.save(ruta_completa)
procesar_y_mostrar([ruta_completa], "SIN RECORTES (0 cortes) — imagen completa")

# ── 2 recortes: mitad superior + mitad inferior ───────────────────────────────
cortes_2 = [(0, 0.50), (0.50, 1.0)]
trozos_2 = [recortar_y_escalar(RUTA_IMAGEN, t, b) for t, b in cortes_2]
procesar_y_mostrar(trozos_2, "2 RECORTES — mitad superior / mitad inferior")

# ── 3 recortes: tres tercios ──────────────────────────────────────────────────
cortes_3 = [(0, 0.33), (0.33, 0.66), (0.66, 1.0)]
trozos_3 = [recortar_y_escalar(RUTA_IMAGEN, t, b) for t, b in cortes_3]
procesar_y_mostrar(trozos_3, "3 RECORTES — tres tercios iguales")

# ── 4 recortes: cuatro cuartos ────────────────────────────────────────────────
cortes_4 = [(0, 0.25), (0.25, 0.50), (0.50, 0.75), (0.75, 1.0)]
trozos_4 = [recortar_y_escalar(RUTA_IMAGEN, t, b) for t, b in cortes_4]
procesar_y_mostrar(trozos_4, "4 RECORTES — cuatro cuartos iguales")

[INFO] 2026-05-07 21:46:51,322 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:46:51,326 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-05-07 21:46:51,327 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx

============================================================
  SIN RECORTES (0 cortes) — imagen completa
============================================================

── Trozo 1 ──

[INFO] 2026-05-07 21:46:51,423 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:46:51,425 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-05-07 21:46:51,425 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-05-07 21:46:51,472 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:46:51,482 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
[INFO] 2026-05-07 21:46:51,483 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
Loading weights: 100%|██████████| 770/770 [00:00<00:00, 10438.89it/s]
Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3,C4,C5,C6
0,Balance/Estado de resultados.Cuentas No Consol...,31/12/2024,31/12/2023,,,,
1,,mil EUR,12 meses,,,,
2,Activo,Aprobado Normal PGC 2007,Aprobado Normal PGC 2007,Aprobado Normal PGC 2007,,,
3,A) Activo no corriente,12497590,11416223,12647002,,,
4,1 Inmovilizado intangible 1. Fondo de comerci...,23959 n.d.,19941 n.d.,23213 n.d.,,,
...,...,...,...,...,...,...,...
69,,,,n.d. 12893101,Vll Deuda con caracteristicas especiales a cor...,,
70,,,,n.d. n.d.,,,
71,,,,,,,C) Pasivo corriente 1. Obligaciones y otros va...
72,,,,n.d.,,,
73,,,,n.d.,,2. Otras deudas,

[INFO] 2026-05-07 21:47:32,023 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:47:32,027 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-05-07 21:47:32,028 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-05-07 21:47:32,122 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:47:32,125 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-05-07 21:47:32,125 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx

============================================================
  2 RECORTES — mitad superior / mitad inferior
============================================================

── Trozo 1 ──

[INFO] 2026-05-07 21:47:32,203 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:47:32,213 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
[INFO] 2026-05-07 21:47:32,214 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
Loading weights: 100%|██████████| 770/770 [00:00<00:00, 10092.67it/s]
Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3
0,,GRIFOLS SA,,
1,Balance/Estadoderesultados,,,
2,CuentasNo Consolidadas,,,
3,Activo,12meses Aprobado Normal PGC2007,12meses Aprobado Normal PGC 2007 11416223,12meses Aprobado Normal PGC2007 12647002
4,A)Activonocorriente I Inmovilizado intangible,12497590 23959,19941,23213
5,1.Fondo de comercio de consolidacion,n.d.,n.d.,n.d.
6,2. Investigaci6n,n.d.,n.d.,n.d.
7,3.Propiedad intelectual,n.d.,n.d.,n.d.
8,5.Otroinmovilizadointangible,n.d.,n.d.,n.d.
9,Il Inmovilizadomaterial,31989,32524,35545
10,1.Terrenosy construcciones,11064,11151,11239
11,2.Instalacionestecnicasyotroinmovilizadomaterial,16685,14926,18207
12,3.Inmovilizado en cursoy anticipos,4240,6447,6099
13,II Inversiones inmobiliarias,102332,108977,80458
14,IVInversionesenempresasdelgrupoyasociadasalarg...,11838151,11202474,12469437
15,1.Participaciones puestas en equivalencia,n.d.,n.d.,n.d.
16,2.Creditosasociedadespuestasenequivalencia,n.d.,n.d.,n.d.
17,3.Otros activos financieros,n.d.,n.d.,n.d.
18,4.Otras inversiones,n.d.,n.d.,n.d.
19,VInversionesfinancierasalargoplazo,418896,2714,29199
20,VI Activosporimpuestodiferido,82263,49593,9150
21,VllDeudascomercialesnocorientes,n.d.,n.d.,n.d.
22,B)Activo corriente IActivosnocorrientesmanteni...,342446 n.d.,1544994 1360089,246099 n.d.
23,IIExistencias,13342,12333,11439
24,IlDeudorescomercialesyotrascuentasacobrar,79885,79873,72869
25,1.Clientesporventasyprestacionesdeservicios a)...,1496,581 n.d.,833 n.d.
26,b)Clientesporventasyprestaciones de serviciosa...,n.d.,581,833
27,,1496,n.d.,
28,2.Sociedadespuestas en equivalencia,n.d.,,n.d.
29,3.Activosporimpuesto corriente,16453,12303,2486
30,4.Otrosdeudores IVInversionesenempresasdelgrup...,n.d.,n.d. 47884,n.d. 123033
31,1.Creditosa empresas puestos en equivalencia,228981 n.d. n.d.,n.d.,n.d. n.d.
32,2.Otros activos financieros,n.d.,n.d.,n.d.
33,3.Otras inversiones,,n.d.,
34,VInversionesfinancierasacortoplazo,,,11569
35,VIPeriodificacionesa cortoplazo,2752 16203,20917 11031,13511
36,VllEfectivoyotrosactivoslfquidosequivalentes,1283,12867,13678
37,Total activo (A + B),,,
38,,12840036,12961217,12893101
39,Pasivo A)Patrimonio neto,1953852 1972243,2101487 2044735,2343125 2285248
40,A-1) Fondos propios ICapital 1.Capital escritu...,119604 119604,119604 119604 n.d.,119604 119604
41,2. (Capital no exigido) IlPrima de emisi6n,,910728,
42,,n.d.,,n.d.
43,,910728,,910728
44,1.Reserva derevalorizacion,n.d.,n.d.,n.d. n.d.
45,2.Reserva de capitalizacion,n.d.,n.d.,n.d.
46,3.Otrasreservas,n.d.,n.d.,
47,Il Reservasyresultados deejerciciosanteriores,n.d.,n.d. -152748,n.d. -162220
48,IV(Accionesyparticipacionesenpatrimoniopropias...,-134448,n.d.,n.d.
49,,n.d. -83138,246735,266296

── Trozo 2 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3
0,A-1) Fondos propios,1972243,2044735,2285248
1,ICapital 1. Capital escriturado,119604 119604,119604 119604,119604 119604
2,2. (Capital no exigido),n.d.,n.d.,n.d.
3,IIPrima de emision,910728,910728,910728
4,1.Reserva derevalorizacion,n.d.,n.d.,n.d.
5,2.Reserva decapitalizacion,n.d.,n.d.,n.d.
6,3.Otrasreservas,n.d.,n.d.,n.d.
7,Il Reservasyresultadosdeejercicios anteriores,n.d.,n.d.,n.d.
8,IV(Accionesyparticipacionesenpatrimoniopropias...,-134448,-152748,-162220
9,VOtrasaportacionesdesocios,n.d.,n.d.,n.d.
10,VIResultadodelejercicioatribuidoalasociedaddom...,-83138,-246735,-266296
11,VllDividendoacuenta),n.d.,n.d.,n.d.
12,VIlllOtrosinstrumentosdepatrimonioneto,6647,8282,7303
13,A-2)Ajustes por cambios de valor,-18391,56752,57798
14,"IActivosnocorrientesypasivosvinculados,manteni...",n.d.,n.d.,n.d.
15,IIDiferencia deconversion,n.d.,n.d.,n.d.
16,IlIOtros,n.d.,n.d.,n.d.
17,"A-3)Subvenciones,donacionesylegadosrecibidos",n.d.,n.d.,79
18,A-4)Socios extemos,n.d.,n.d.,n.d.
19,B)Pasivonocorriente,10572251,10561625,10323483
20,IProvisionesalargoplazo,3217,3838,n.d.
21,II Deudas alargo plazo,6288936 5387413,5879325 4571059,3901732 2556641
22,1. Obligacionesy otrosvalores negociables 2.De...,901345,1308026,1340473
23,3.Acreedoresporarrendamientofinanciero,,27,52
24,4.Otros pasivos financieros,21 n.d.,n.d.,n.d.
25,IIDeudasconempresasdelgrupoyasociadasalargoplazo,4276854,4673555,6419171
26,1.Deudasconsociedadespuestaenequivalencia,n.d.,n.d.,n.d.
27,2.Otras deudas,n.d.,n.d.,n.d.
28,IVPasivosporimpuestodiferido,3244,4907,2580
29,VPeriodificacionesalargoplazo,n.d.,n.d.,n.d.
30,V1Acreedorescomercialesnocorrientes,n.d.,n.d.,n.d.
31,VllDeudaconcaracteristicasespecialesalargoplazo,n.d.,n.d.,n.d.
32,C)Pasivocorriente,313933,298105,226493
33,IPasivosvinculadosconactivosnocorrientesmanten...,n.d.,n.d.,n.d.
34,IIProvisionesacortoplazo,79947,14000,7000
35,1.Provisionesporderechosdeemisiondegasesdeefec...,n.d.,n.d.,n.d.
36,2.Otrasprovisiones,79947,14000,7000
37,IDeudasa cortoplazo,68347,106970,74786
38,1. Obligaciones y otros valores negociables,38907,30170,12554
39,2.Deudasconentidadesdecredito,29383,68542,60899
40,3.Acreedoresporarrendamientofinanciero,n.d.,25,391
41,4.Otros pasivos financieros,n.d.,n.d.,n.d.
42,IV Deudas con empresas del grupoy asociadas ac...,62437,64699,61720
43,1.Deudasconsociedadespuesta enequivalencia,n.d.,n.d.,n.d.
44,2.Otras deudas,n.d.,n.d.,n.d.
45,VAcreedorescomercialesyotrascuentasapagar,94624,112436,82987
46,1.Proveedores,65750,69365,58812
47,a)Proveedoresa largoplazo,n.d.,n.d.,n.d.
48,b)Proveedoresacortoplazo,65750,69365,58812
49,"2.Proveedores,empresas del grupoy asociadas",n.d.,n.d.,n.d.
50,3.Pasivosporimpuesto corriente 4.Otros acreedores,n.d.,n.d.,n.d. n.d.
51,,n.d.,n.d.,n.d.
52,VIPeriodificacionesacortoplazo,8578,n.d.,n.d.
53,VllDeudaconcaracteristicasespecialesacortoplazo,n.d.,n.d.,12893101
54,Totalpatrimonio netoy pasivo(A+B+C),12840036,12961217,

[INFO] 2026-05-07 21:48:05,782 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:48:05,786 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-05-07 21:48:05,787 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-05-07 21:48:05,877 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:48:05,879 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-05-07 21:48:05,880 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx

============================================================
  3 RECORTES — tres tercios iguales
============================================================

── Trozo 1 ──

[INFO] 2026-05-07 21:48:05,926 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:48:05,936 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
[INFO] 2026-05-07 21:48:05,936 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
Loading weights: 100%|██████████| 770/770 [00:00<00:00, 10615.52it/s]
Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3,C4,C5
0,,GRIFOLS SA,,,,
1,Balance/Estadoderesultados,,,,,
2,CuentasNoConsolidadas,31/12/2024,,31/12/2023,,31/12/2022
3,,mil EUR,,mil EUR,,mil EUR
4,,Aprobado,,,,Aprobado
5,,,,Aprobado,,
6,,Normal PGC2007,,Normal PGC 2007,,Normal PGC 2007
7,,,Activo,,,
8,A)Activonocorriente,12497590,,11416223,,12647002
9,I Inmovilizadointangible,23959,,19941,,23213
10,1.Fondodecomerciodeconsolidacion,n.d.,,n.d.,,n.d.
11,2. Investigaci6n,n.d.,,n.d.,,n.d.
12,3.Propiedad intelectual,n.d.,,n.d.,,n.d.
13,5.Otro inmovilizadointangible,n.d.,,n.d.,,n.d.
14,Il Inmovilizado material,31989,,32524,,35545
15,1.Terrenosyconstrucciones,11064,,11151,,11239
16,2.Instalacionestecnicasyotroinmovilizadomaterial,16685,,14926,,18207
17,3.Inmovilizado en curso y anticipos,4240,,6447,,6099
18,IllInversionesinmobiliarias,102332,,108977,,80458
19,IVInversionesenempresasdelgrupoyasociadasalarg...,11838151,,11202474,,12469437
20,1.Participacionespuestas en equivalencia,n.d.,,n.d.,,n.d.
21,2.Creditosasociedadespuestasenequivalencia,n.d.,,n.d.,,n.d.
22,3.Otros activos financieros,n.d.,,n.d.,,n.d.
23,4.Otras inversiones,n.d.,,n.d.,,n.d.
24,VInversionesfinancierasalargoplazo,418896,,2714,,29199
25,VIActivosporimpuestodiferido,82263,,49593,,9150
26,VllDeudascomercialesnocorrientes,n.d.,,n.d.,,n.d.
27,B)Activocorriente,342446,,1544994,,246099
28,IActivosnocorrientesmantenidosparalaventa,n.d.,,1360089,,n.d.
29,,13342,,12333,IlExistencias,11439
30,IlDeudorescomercialesyotrascuentasacobrar,79885,,79873,,72869
31,1.Clientesporventasyprestacionesdeservicios,1496,,581,,833
32,a)Clientesporventasyprestacionesdeservicios a ...,n.d.,,n.d.,,n.d.
33,b)Clientesporventasyprestaciones de serviciosa...,1496,,581,,833
34,2.Sociedadespuestasenequivalencia,n.d.,,n.d.,,n.d.
35,3.Activosporimpuestocorriente,16453,,12303,,2486
36,4.Otros deudores,n.d.,,n.d.,,n.d.
37,IV Inversionesenempresasdelgrupoy asociadas ac...,228981 n.d.,1.Creditosaempresaspuestos en equivalencia,47884 n.d.,,123033 n.d.
38,2.Otros activos financieros,n.d.,,n.d.,,n.d.

── Trozo 2 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3
0,IlExistencias,13342,12333,11439
1,IlDeudorescomercialesyotrascuentasacobrar,79885,79873,72869
2,1.Clientes por ventas y prestaciones de servicios,1496,581,833
3,a) Clientes por ventasy prestaciones de servic...,n.d.,n.d.,n.d.
4,b)Clientesporventasyprestacionesdeserviciosaco...,1496,581,833
5,2.Sociedadespuestas en equivalencia,n.d.,n.d.,n.d.
6,3.Activosporimpuesto corriente,16453,12303,2486
7,4.Otrosdeudores,n.d.,n.d.,n.d.
8,IVInversionesenempresasdelgrupoyasociadasacort...,228981,47884,123033
9,1.Creditos a empresaspuestos en equivalencia,n.d.,n.d.,n.d.
10,2.Otros activos financieros,n.d.,n.d.,n.d.
11,3. Otras inversiones,n.d.,n.d.,n.d.
12,VInversionesfinancierasacortoplazo,2752,20917,11569
13,VIPeriodificacionesacortoplazo,16203,11031,13511
14,VllEfectivoyotrosactivoslfiquidosequivalentes,1283,12867,13678
15,Total activo (A +B),12840036,12961217,12893101
16,Pasivo,,,
17,A)Patrimonioneto,1953852,2101487,2343125
18,A-1) Fondos propios,1972243,2044735,2285248
19,ICapital,119604,119604,119604
20,1.Capital escriturado,119604,119604,119604
21,2. (Capital no exigido),n.d.,n.d.,n.d.
22,IPrima de emision,910728,910728,910728
23,1.Reservaderevalorizacion,n.d.,n.d.,n.d.
24,2.Reserva de capitalizacion,n.d.,n.d.,n.d.
25,3.Otras reservas,n.d.,n.d.,n.d.
26,Il Reservasyresultadosdeejerciciosanteriores,n.d.,n.d.,n.d.
27,IV(Accionesyparticipacionesenpatrimoniopropias...,-134448,-152748,-162220
28,Votrasaportacionesdesocios,n.d.,n.d.,n.d.
29,VIResultadodelejercicioatribuidoalasociedaddom...,-83138,-246735,-266296
30,VllDividendo a cuenta),n.d.,n.d.,n.d.
31,VillOtrosinstrumentosdepatrimonioneto,6647,8282,7303
32,A-2)Ajustespor cambios devalor,-18391,56752,57798
33,"IActivosnocorrientesypasivosvinculados,manteni...",n.d.,n.d.,n.d.
34,IIDiferenciadeconversion,n.d.,n.d.,n.d.
35,IlOtros,n.d.,n.d.,n.d.
36,"A-3)Subvenciones,donacionesylegadosrecibidos",n.d.,n.d.,79
37,A-4)Sociosextemos,n.d.,n.d.,n.d.
38,B)Pasivo no corriente,10572251,10561625,10323483
39,IProvisiones alargoplazo,3217,3838,n.d.
40,II Deudas a largo plazo,6288936,5879325,3901732
41,1.obligacionesy otrosvaloresnegociables 2.Deud...,5387413,4571059,2556641 1340473
42,,901345,1308026,
43,3.Acreedoresporarrendamientofinanciero,21,27,52

── Trozo 3 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3
0,"A-3)Subvenciones,donacionesylegadosrecibidos",n.d.,n.d.,79
1,A-4)Sociosextemos,n.d.,n.d.,n.d.
2,B)Pasivonocorriente,10572251,10561625,
3,,,,10323483
4,IProvisionesalargoplazo,3217,3838,n.d.
5,IIDeudasalargoplazo,6288936,5879325,3901732
6,1. Obligaciones y otros valores negociables,5387413,4571059,2556641
7,,21,27,
8,3.Acreedores porarrendamientofinanciero,,,52
9,4. Otros pasivos financieros,n.d.,n.d.,n.d.
10,IDeudasconempresasdelgrupoyasociadasalargoplazo,4276854,4673555,6419171
11,1.Deudas con sociedades puesta en equivalencia,n.d.,n.d.,n.d.
12,2.Otras deudas,n.d.,n.d.,n.d.
13,IVPasivosporimpuestodiferido,3244,4907,2580
14,VPeriodificaciones a largoplazo,n.d.,n.d.,n.d.
15,VIAcreedorescomercialesnocorrientes,n.d.,n.d.,n.d.
16,VllDeudaconcaracteristicasespecialesalargoplazo,n.d.,n.d.,n.d.
17,C)Pasivo coriente,313933,298105,226493
18,IPasivosvinculadosconactivosnocorrientesmanten...,n.d.,n.d.,n.d.
19,IIProvisionesa cortoplazo,79947,14000,7000
20,1.Provisionesporderechosdeemisiondegasesdeefec...,n.d.,n.d.,n.d.
21,2. Otras provisiones,79947,14000,7000
22,IDeudas acortoplazo,68347,106970,74786
23,1.Obligacionesy otrosvaloresnegociables,38907,30170,12554
24,2.Deudas conentidadesde credito,29383,68542,60899
25,3.Acreedoresporarrendamientofinanciero,n.d.,25,391
26,4.Otros pasivos financieros,n.d.,n.d.,n.d.
27,IVDeudasconempresasdelgrupoyasociadasacortoplazo,62437,64699,61720
28,1.Deudas con sociedades puesta en equivalencia,n.d.,n.d.,n.d.
29,2.Otras deudas,n.d.,n.d.,n.d.
30,VAcreedorescomercialesyotrascuentasapagar,94624,112436,82987
31,1.Proveedores,65750,69365,58812
32,a)Proveedores a largoplazo,n.d.,n.d.,n.d.
33,b)Proveedoresacortoplazo,65750,69365,58812
34,"2.Proveedores,empresas del grupoy asociadas",n.d.,n.d.,n.d.
35,3.Pasivosporimpuesto corriente,n.d.,n.d.,n.d.
36,4.Otros acreedores,n.d.,n.d.,n.d.
37,VIPeriodificacionesacortoplazo,8578,n.d.,n.d.
38,Totalpatrimonio netoypasivo(A+B+C),12840036,12961217,12893101

[INFO] 2026-05-07 21:48:44,694 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:48:44,699 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-05-07 21:48:44,699 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-05-07 21:48:44,786 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:48:44,788 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-05-07 21:48:44,788 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-05-07 21:48:44,833 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 21:48:44,842 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
[INFO] 2026-05-07 21:48:44,843 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx

============================================================
  4 RECORTES — cuatro cuartos iguales
============================================================

── Trozo 1 ──

Loading weights: 100%|██████████| 770/770 [00:00<00:00, 9999.70it/s]
Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3,C4
0,,GRIFOLS SA,,,
1,Balance/Estadoderesultados,,,,
2,CuentasNoConsolidadas,31/12/2024,,,31/12/2022
3,,mil EUR,,,mil EUR
4,,,,12meses,
5,,Aprobado,Aprobado,Aprobado,
6,,NormalPGC2007,Normal PGC 2007,NormalPGC2007,
7,Activo,,,,
8,A)Activonocorriente,12497590,11416223,12647002,
9,IInmovilizadointangible,23959,19941,23213,
10,1.Fondodecomerciodeconsolidacion,n.d.,n.d.,n.d.,
11,2. Investigaci6n,n.d.,n.d.,n.d.,
12,3.Propiedad intelectual,n.d.,n.d.,n.d.,
13,5.Otro inmovilizadointangible,n.d.,n.d.,n.d.,
14,IInmovilizadomaterial,31989,32524,35545,
15,1.Terrenosy construcciones,11064,11151,11239,
16,2.Instalacionestecnicasy otro inmovilizado mat...,16685,14926,18207,
17,3.Inmovilizado en cursoy anticipos,4240,6447,6099,
18,I Inversionesinmobiliarias,102332,108977,80458,
19,IVInversionesenempresasdelgrupoyasociadasalarg...,11838151,11202474,12469437,
20,1.Participacionespuestas en equivalencia,n.d.,n.d.,n.d.,
21,2.Creditosasociedadespuestasenequivalencia,n.d.,n.d.,n.d.,
22,3.Otrosactivosfinancieros,n.d.,n.d.,n.d.,
23,4. Otras inversiones,n.d.,n.d.,n.d.,
24,VInversionesfinancierasalargoplazo,418896,2714,29199,
25,VIActivosporimpuestodiferido,82263,49593,9150,
26,VllDeudascomercialesnocorrientes,n.d.,n.d.,n.d.,
27,B)Activo corriente,342446,1544994,246099,
28,IActivosnocorrientesmantenidosparalaventa,n.d.,1360089,n.d.,
29,IlExistencias,13342,12333,11439,
30,IlIDeudorescomercialesyotrascuentasacobrar,79885,79873,72869,

── Trozo 2 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3
0,2.Creditosasociedadespuestasenequivalencia,n.d.,n.d.,n.d.
1,3.Otros activos financieros,n.d.,n.d.,n.d.
2,4.Otras inversiones,n.d.,n.d.,n.d.
3,VInversionesfinancierasalargoplazo,418896,2714,29199
4,VIActivosporimpuestodiferido,82263,49593,9150
5,VllDeudascomercialesnocorrientes,n.d.,n.d.,n.d.
6,B)Activo corriente,342446,1544994,246099
7,IActivosnocorrientesmantenidosparalaventa,n.d.,1360089,n.d.
8,IIExistencias,13342,12333,11439
9,IllDeudorescomercialesyotrascuentasacobrar,79885,79873,72869
10,1.Clientesporventasyprestacionesdeservicios,1496,581,833
11,a)Clientesporventasyprestacionesdeserviciosa l...,n.d.,n.d.,n.d.
12,b) Clientes por ventasy prestaciones deservici...,1496,581,833
13,2.Sociedadespuestas enequivalencia,n.d.,n.d.,n.d.
14,3.Activos porimpuesto corriente,16453,12303,2486
15,4.Otrosdeudores,n.d.,n.d.,n.d.
16,IVInversionesenempresasdelgrupoyasociadasacort...,228981,47884,123033
17,1.Creditos a empresaspuestos enequivalencia,n.d.,n.d.,n.d.
18,2.Otros activos financieros,n.d.,n.d.,n.d.
19,3.Otras inversiones,n.d.,n.d.,n.d.
20,VInversionesfinancierasa cortoplazo,2752,20917,11569
21,VIPeriodificacionesacortoplazo,16203,11031,13511
22,VllEfectivoyotrosactivoslfquidosequivalentes,1283,12867,13678
23,Total activo (A + B),12840036,12961217,12893101
24,Pasivo,,,
25,A)Patrimonioneto,1953852,2101487,2343125
26,A-1) Fondos propios,1972243,2044735,2285248
27,ICapital,119604,119604,119604
28,1.Capital escriturado,119604,119604,119604
29,2. (Capital no exigido),n.d.,n.d.,n.d.
30,IlPrima de emision,910728,910728,910728
31,1.Reserva derevalorizaci6n,n.d.,n.d.,n.d.
32,2.Reserva de capitalizacion,n.d.,n.d.,n.d.
33,3.Otras reservas,n.d.,n.d.,n.d.
34,I Reservasyresultadosdeejerciciosanteriores,n.d.,n.d.,n.d.
35,IV (Acciones y participaciones en patrimonio p...,-134448,-152748,-162220
36,VOtras aportacionesdesocios,n.d.,n.d.,n.d.
37,nante,-83138,246735,266296

── Trozo 3 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3
0,A-1)Fondospropios,1972243,2044735,2285248
1,ICapital,119604,119604,119604
2,1.Capital escriturado,119604,119604,119604
3,2. (Capital no exigido),n.d.,n.d.,n.d.
4,IlPrima de emision,910728,910728,910728
5,1.Reserva derevalorizacion,n.d.,n.d.,n.d.
6,2.Reserva de capitalizacion,n.d.,n.d.,n.d.
7,3.Otrasreservas,n.d.,n.d.,n.d.
8,Il Reservasyresultadosdeejerciciosanteriores,n.d.,n.d.,n.d.
9,IV(Accionesyparticipacionesenpatrimoniopropias...,-134448,-152748,-162220
10,V Otrasaportacionesdesocios,n.d.,n.d.,n.d.
11,VIResultadodelejercicioatribuidoalasociedaddom...,-83138,-246735,-266296
12,VllDividendoacuenta),n.d.,n.d.,n.d.
13,VIllOtrosinstrumentos depatrimonioneto,6647,8282,7303
14,A-2)Ajustesporcambiosdevalor,-18391,56752,57798
15,"IActivosnocorrientesypasivosvinculados,manteni...",n.d.,n.d.,n.d.
16,IDiferenciadeconversi6n,n.d.,n.d.,n.d.
17,IlOtros,n.d.,n.d.,n.d.
18,"A-3)Subvenciones,donacionesylegadosrecibidos",n.d.,n.d.,79
19,A-4)Sociosextemos,n.d.,n.d.,n.d.
20,B)Pasivonocorriente,10572251,10561625,10323483
21,IProvisionesalargoplazo,3217,3838,n.d.
22,IIDeudas a largoplazo,6288936,5879325,3901732
23,1.obligacionesy otrosvaloresnegociables,5387413,4571059,2556641
24,2.Deudasconentidadesdecredito,901345,1308026,1340473
25,3.Acreedoresporarrendamientofinanciero,21,27,52
26,4. Otros pasivos financieros,n.d.,n.d.,n.d.
27,IIDeudasconempresasdelgrupoyasociadasalargoplazo,4276854,4673555,6419171
28,1.Deudasconsociedadespuestaenequivalencia,n.d.,n.d.,n.d.
29,2. Otras deudas,n.d.,n.d.,n.d.
30,IVPasivos porimpuesto diferido,3244,4907,2580
31,VPeriodificacionesa largoplazo,n.d.,n.d.,n.d.
32,VIAcreedorescomercialesnocorientes,n.d.,n.d.,n.d.
33,VllDeuda concaracteristicas especialesa largop...,n.d.,n.d.,n.d.
34,C)Pasivo corriente,313933,298105,226493

── Trozo 4 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1
  · Tabla 1:

,C0,C1,C2,C3
0,3.Acreedoresporarrendamientofinanciero,,21 27,52
1,4. Otros pasivos financieros,n.d.,n.d.,n.d.
2,IlI Deudasconempresasdel grupoyasociadas alarg...,4276854,4673555,6419171
3,1.Deudasconsociedadespuestaenequivalencia,n.d.,n.d.,n.d.
4,2.Otras deudas,n.d.,n.d.,n.d.
5,IVPasivosporimpuestodiferido,3244,4907,2580
6,VPeriodificacionesalargoplazo,n.d.,n.d.,n.d.
7,VIAcreedorescomercialesnocorrientes,n.d.,n.d.,n.d.
8,VllDeudaconcaracteristicasespecialesalargoplazo,n.d.,n.d.,n.d.
9,C)Pasivo corriente,313933,298105,226493
10,IPasivosvinculadosconactivosnocorrientesmanten...,n.d.,n.d.,n.d.
11,IIProvisiones a cortoplazo,79947,14000,7000
12,1.Provisionesporderechosdeemisiondegasesdeefec...,n.d.,n.d.,n.d.
13,2. Otras provisiones,79947,14000,7000
14,IIDeudasacortoplazo,68347,106970,74786
15,1. Obligaciones y otros valores negociables,38907,30170,12554
16,2.Deudas conentidades decredito,29383,68542,60899
17,3.Acreedoresporarrendamientofinanciero,n.d.,25,391
18,4. Otros pasivos financieros,n.d.,n.d.,n.d.
19,IVDeudasconempresasdel grupoyasociadasa cortop...,62437,64699,61720
20,1.Deudas consociedadespuesta en equivalencia,n.d.,n.d.,n.d.
21,2.Otrasdeudas,n.d.,n.d.,n.d.
22,VAcreedorescomercialesyotrascuentasapagar,94624,112436,82987
23,1.Proveedores,65750,69365,58812
24,a)Proveedores a largo plazo,n.d.,n.d.,n.d.
25,b)Proveedores a cortoplazo,65750,69365,58812
26,"2.Proveedores,empresas del grupoy asociadas",n.d.,n.d.,n.d.
27,3.Pasivosporimpuesto corriente,n.d.,n.d.,n.d.
28,4.Otros acreedores,n.d.,n.d.,n.d.
29,VIPeriodificacionesacortoplazo,8578,n.d.,n.d.
30,VllDeudaconcaracteristicasespecialesacortoplazo,n.d.,n.d.,n.d.
31,Totalpatrimonio netoypasivo(A+B+C),12840036,12961217,12893101

#### Conclusión — Imagen limpia

> La mejora progresiva con más recortes se confirma también en imágenes de mejor calidad. El número óptimo de recortes **no depende de la calidad de la imagen sino de la densidad de filas**: una imagen de alta calidad con muchas filas necesita tantos recortes como una de baja calidad con la misma densidad.

---

## Parte 2 — LLM multimodal de visión directa

### Motivación

El enfoque alternativo más intuitivo es enviar la imagen directamente a un modelo con capacidades de visión y pedirle que extraiga las 22 partidas con sus valores en un único paso, sin necesidad de Docling ni de serialización textual.

Este enfoque tiene ventajas teóricas: el modelo ve la imagen tal como la vería un humano, puede interpretar el contexto visual completo y no depende de la calidad del OCR de Docling. La pregunta es si un modelo de visión gratuito (`llama-4-scout-17b`) es suficientemente fiable para esta tarea con imágenes de alta densidad.

### Hipótesis inversa

Al contrario que con Docling, **segmentar la imagen podría perjudicar al modelo de visión**: cuando se corta la imagen, los trozos inferiores pierden la cabecera con las fechas de los ejercicios, y el modelo ya no tiene referencia para saber a qué año corresponde cada columna de valores.

#### Celda 5 — Setup: recortes y cliente Groq para visión

Genera los mismos recortes que en la Parte 1 (0, 2, 3 y 4 fragmentos) y configura el cliente Groq con `llama-4-scout-17b-16e-instruct`, el modelo de visión disponible en el plan gratuito.

In [1]:
# celda 1



from PIL import Image
import os

RUTA_IMAGEN = r"C:\Users\david\Desktop\david\tfm\TFM PYTHON\RECORTES EXPERIMENTO\excel_balance.png"
OUTPUTS = r"C:\Users\david\Desktop\david\tfm\TFM PYTHON\outputs"
os.makedirs(OUTPUTS, exist_ok=True)

def recortar_y_escalar(ruta_imagen, top_pct, bottom_pct, escala=2, overlap_pct=0.05):
    img = Image.open(ruta_imagen)
    w, h = img.size
    top    = max(0, int(h * (top_pct - overlap_pct)))
    bottom = min(h, int(h * (bottom_pct + overlap_pct)))
    recorte = img.crop((0, top, w, bottom))
    recorte = recorte.resize((w * escala, (bottom - top) * escala), Image.LANCZOS)
    nombre = os.path.splitext(os.path.basename(ruta_imagen))[0]
    ruta_salida = os.path.join(OUTPUTS, f"{nombre}_exp_trozo_{top_pct}_{bottom_pct}.png")
    recorte.save(ruta_salida)
    return ruta_salida

# 0 recortes
img = Image.open(RUTA_IMAGEN)
w, h = img.size
img_escalada = img.resize((w * 2, h * 2), Image.LANCZOS)
nombre = os.path.splitext(os.path.basename(RUTA_IMAGEN))[0]
ruta_completa = os.path.join(OUTPUTS, f"{nombre}_exp_0recortes.png")
img_escalada.save(ruta_completa)

# 2 recortes
trozos_2 = [recortar_y_escalar(RUTA_IMAGEN, t, b) for t, b in [(0, 0.50), (0.50, 1.0)]]

# 3 recortes
trozos_3 = [recortar_y_escalar(RUTA_IMAGEN, t, b) for t, b in [(0, 0.33), (0.33, 0.66), (0.66, 1.0)]]

# 4 recortes
trozos_4 = [recortar_y_escalar(RUTA_IMAGEN, t, b) for t, b in [(0, 0.25), (0.25, 0.50), (0.50, 0.75), (0.75, 1.0)]]

print("✅ Recortes listos:")
print(f"  0 recortes: {ruta_completa}")
print(f"  2 recortes: {trozos_2}")
print(f"  3 recortes: {trozos_3}")
print(f"  4 recortes: {trozos_4}")

✅ Recortes listos:
  0 recortes: C:\Users\david\Desktop\david\tfm\TFM PYTHON\outputs\excel_balance_exp_0recortes.png
  2 recortes: ['C:\\Users\\david\\Desktop\\david\\tfm\\TFM PYTHON\\outputs\\excel_balance_exp_trozo_0_0.5.png', 'C:\\Users\\david\\Desktop\\david\\tfm\\TFM PYTHON\\outputs\\excel_balance_exp_trozo_0.5_1.0.png']
  3 recortes: ['C:\\Users\\david\\Desktop\\david\\tfm\\TFM PYTHON\\outputs\\excel_balance_exp_trozo_0_0.33.png', 'C:\\Users\\david\\Desktop\\david\\tfm\\TFM PYTHON\\outputs\\excel_balance_exp_trozo_0.33_0.66.png', 'C:\\Users\\david\\Desktop\\david\\tfm\\TFM PYTHON\\outputs\\excel_balance_exp_trozo_0.66_1.0.png']
  4 recortes: ['C:\\Users\\david\\Desktop\\david\\tfm\\TFM PYTHON\\outputs\\excel_balance_exp_trozo_0_0.25.png', 'C:\\Users\\david\\Desktop\\david\\tfm\\TFM PYTHON\\outputs\\excel_balance_exp_trozo_0.25_0.5.png', 'C:\\Users\\david\\Desktop\\david\\tfm\\TFM PYTHON\\outputs\\excel_balance_exp_trozo_0.5_0.75.png', 'C:\\Users\\david\\Desktop\\david\\tfm\\TFM PYTHON\\outputs\\excel_balance_exp_trozo_0.75_1.0.png']

#### Celda 6 — Inicialización del cliente de visión

Carga la API key desde `.env` y confirma el modelo de visión activo. Los tres clientes en rotación se usan para distribuir la carga entre las múltiples llamadas del experimento y respetar los límites RPM del plan gratuito de Groq.

In [2]:
# CELDA 2

import os
from dotenv import load_dotenv
import openai
import json

load_dotenv()

GROQ_BASE_URL = "https://api.groq.com/openai/v1"

clients = [
    openai.OpenAI(api_key=os.getenv("GROQ_API_KEY_1", ""), base_url=GROQ_BASE_URL),
    openai.OpenAI(api_key=os.getenv("GROQ_API_KEY_2", ""), base_url=GROQ_BASE_URL),
    openai.OpenAI(api_key=os.getenv("GROQ_API_KEY_3", ""), base_url=GROQ_BASE_URL),
]

MODELO_VISION = "meta-llama/llama-4-scout-17b-16e-instruct"

print("✅ Cliente Groq listo. Modelo visión:", MODELO_VISION)

✅ Cliente Groq listo. Modelo visión: meta-llama/llama-4-scout-17b-16e-instruct

#### Celda 7 — Setup de partidas objetivo y función base64

Define la lista de 22 alias a extraer y la función `imagen_a_base64` que codifica la imagen para enviarla al modelo multimodal.

In [3]:
# CELDA 3 - SETUP VISION
import base64

PARTIDAS_OBJETIVO = [
    "patrimonio_neto", "fondos_propios", "pasivo_no_corriente",
    "deudas_lp", "deudas_cp", "pasivo_corriente", "total_activo",
    "activo_corriente", "existencias", "deudores_comerciales", "efectivo",
    "inmovilizado_material", "acreedores_comerciales", "cifra_negocios",
    "otros_ingresos_explotacion", "resultado_explotacion", "amortizacion",
    "gastos_financieros", "resultado_antes_impuestos", "resultado_ejercicio",
    "deuda_credito_lp", "deuda_credito_cp"
]

def imagen_a_base64(ruta):
    with open(ruta, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")

print("✅ Setup listo")

✅ Setup listo

#### Celda 8 — Visión directa: imagen completa, prompt inicial

Primera llamada: imagen completa sin recortar, prompt básico que lista las 22 partidas y pide un JSON.

**Qué observar en el output:**
- El modelo devuelve las 22 partidas (`finish_reason: stop`, no trunca).
- Sin embargo los valores son **incorrectos**: `pasivo_no_corriente` aparece con valor `90.567.251` cuando el real es `10.572.251` (un dígito de más). El `resultado_antes_impuestos` recibe el valor del total del activo. Varios epígrafes tienen solo 2 valores en lugar de 3 (ignora un ejercicio).
- La PyG aparece sin valores o con valores inventados.

El modelo ve la imagen pero no la lee con precisión suficiente para valores numéricos en tablas densas.

In [4]:
# CELDA 4 - DEBUG RAW (sin parseo, ves exactamente lo que devuelve Groq)

def debug_raw(ruta_imagen, etiqueta):
    b64 = imagen_a_base64(ruta_imagen)
    prompt = f"""Eres un extractor de datos financieros. Esta imagen es un fragmento ({etiqueta}) de un balance/cuenta de pérdidas y ganancias.

Lista de partidas a extraer:
{', '.join(PARTIDAS_OBJETIVO)}

Devuelve SOLO JSON sin markdown con las partidas que encuentres:
{{
  "nombre_partida": {{"partida": "texto literal", "valores": [val1, val2]}},
  ...
}}"""

    response = clients[0].chat.completions.create(
        model=MODELO_VISION,
        messages=[{
            "role": "user",
            "content": [
                {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{b64}"}},
                {"type": "text", "text": prompt}
            ]
        }],
        temperature=0,
        max_tokens=2048
    )

    finish_reason = response.choices[0].finish_reason
    tokens_in  = response.usage.prompt_tokens
    tokens_out = response.usage.completion_tokens
    raw = response.choices[0].message.content

    print(f"finish_reason : {finish_reason}")
    print(f"tokens        : {tokens_in} in / {tokens_out} out")
    print(f"--- RAW ---")
    print(raw)
    print(f"--- FIN ---\n")

# Prueba primero solo imagen completa
debug_raw(ruta_completa, "trozo 1 de 1")

finish_reason : stop
tokens        : 2526 in / 694 out
--- RAW ---
```json
{
  "patrimonio_neto": {"partida": "Patrimonio Neto", "valores": [1953852, 2343325]},
  "fondos_propios": {"partida": "A) Fondos propios", "valores": [1972243, 2285248]},
  "pasivo_no_corriente": {"partida": "Pasivo No Corriente", "valores": [90567251, 90906126]},
  "deudas_lp": {"partida": "Deudas a largo plazo", "valores": [6288936, 5874925]},
  "deudas_cp": {"partida": "Deudas a corto plazo", "valores": [79947, 106970]},
  "pasivo_corriente": {"partida": "Pasivo Corriente", "valores": [313933, 298105]},
  "total_activo": {"partida": "Total Activo", "valores": [12840036, 12961217]},
  "activo_corriente": {"partida": "Activo Corriente", "valores": [290309, 324958]},
  "existencias": {"partida": "Existencias", "valores": [13342, 11359]},
  "deudores_comerciales": {"partida": "Deudores Comerciales", "valores": [79885, 72869]},
  "efectivo": {"partida": "Efectivo", "valores": [1283, 13678]},
  "inmovilizado_material": {"partida": "Inmovilizado Material", "valores": [31989, 32524]},
  "acreedores_comerciales": {"partida": "Acreedores Comerciales", "valores": [94624, 1124236]},
  "cifra_negocios": {"partida": "Importe Neto de la Cifra de Negocios", "valores": [701053, 619242]},
  "otros_ingresos_explotacion": {"partida": "Otros Ingresos de Explotación", "valores": [247819, 242824]},
  "resultado_explotacion": {"partida": "Resultado de Explotación", "valores": [488639, 193311]},
  "amortizacion": {"partida": "Amortización", "valores": [164453, 12303]},
  "gastos_financieros": {"partida": "Gastos Financieros", "valores": [3907, 30170]},
  "resultado_antes_impuestos": {"partida": "Resultado antes de Impuestos", "valores": [12840036, 12961217]},
  "resultado_ejercicio": {"partida": "Resultado del Ejercicio", "valores": [5213, 2312]},
  "deuda_credito_lp": {"partida": "Deuda a largo plazo con entidades de crédito", "valores": [5387413, 4571059]},
  "deuda_credito_cp": {"partida": "Deuda a corto plazo con entidades de crédito", "valores": [79947, 14000]}
}
```
--- FIN ---

#### Celda 9 — Visión directa: imagen completa, prompt mejorado

Segunda iteración con reglas más estrictas: solo incluir partidas vistas literalmente, un valor por columna de fecha, no inventar datos. Se añade extracción del bloque JSON con regex para aislar el resultado aunque haya texto adicional.

**Qué observar en el output:**
- Con instrucciones más estrictas el modelo omite más partidas (no inventa) pero los valores siguen siendo incorrectos donde los hay.
- El problema no es el prompt sino la limitación estructural del modelo para leer columnas de datos numéricos en imágenes de alta densidad.

In [8]:
# CELDA 4 - DEBUG RAW PROMPT MEJORADO

import re

def debug_raw(ruta_imagen, etiqueta):
    b64 = imagen_a_base64(ruta_imagen)
    prompt = f"""Eres un extractor de datos financieros experto en balances y cuentas de pérdidas y ganancias españoles.

Esta imagen es un fragmento ({etiqueta}) de un estado financiero.

PARTIDAS QUE BUSCO:
{', '.join(PARTIDAS_OBJETIVO)}

REGLAS ESTRICTAS:
1. Solo incluye en el JSON una partida si la ves LITERALMENTE en la imagen con su texto y sus valores numéricos.
2. Si no encuentras una partida, NO la incluyas. Ni con null, ni con [], ni con nan. Simplemente no la pongas.
3. Para cada partida encontrada, devuelve UN valor por cada columna de fecha/ejercicio que veas. Si hay 3 fechas, 3 valores. Si hay 2, 2 valores. En el mismo orden izquierda a derecha.
4. Los valores son siempre números enteros o decimales. Si en la imagen pone n.d. o está vacío, no incluyas esa partida.
5. No confundas partidas: cada clave del JSON debe corresponder exactamente a la partida que describes en "partida".
6. No inventes valores. Si no lees claramente un número, no lo incluyas.

Devuelve SOLO el JSON, sin texto antes ni después, sin markdown, sin explicaciones:
{{
  "nombre_partida": {{"partida": "texto literal exacto de la imagen", "valores": [val1, val2, val3]}},
  ...
}}"""

    response = clients[0].chat.completions.create(
        model=MODELO_VISION,
        messages=[{
            "role": "user",
            "content": [
                {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{b64}"}},
                {"type": "text", "text": prompt}
            ]
        }],
        temperature=0,
        max_tokens=2048
    )

    finish_reason = response.choices[0].finish_reason
    tokens_in  = response.usage.prompt_tokens
    tokens_out = response.usage.completion_tokens
    raw = response.choices[0].message.content

    # Extraer solo el bloque JSON aunque haya texto antes o después
    match = re.search(r'\{.*\}', raw, re.DOTALL)
    raw_limpio = match.group(0) if match else raw

    print(f"finish_reason : {finish_reason}")
    print(f"tokens        : {tokens_in} in / {tokens_out} out")
    print(f"--- RAW ---")
    print(raw)
    print(f"--- FIN ---\n")

    return raw_limpio

# Prueba con imagen completa
debug_raw(ruta_completa, "trozo 1 de 1")

finish_reason : stop
tokens        : 2737 in / 674 out
--- RAW ---
{
  "patrimonio_neto": {"partida": "Patrimonio neto", "valores": [1953852]},
  "fondos_propios": {"partida": "A-1) Fondos propios", "valores": [1972243, 2044735]},
  "pasivo_no_corriente": {"partida": "Pasivo no corriente", "valores": [90572251, 9039245]},
  "deudas_lp": {"partida": "Deudas a largo plazo", "valores": [6288936, 5879925]},
  "deudas_cp": {"partida": "Deudas a corto plazo", "valores": [79947, 14000]},
  "pasivo_corriente": {"partida": "C) Pasivo corriente", "valores": [313933, 298105]},
  "total_activo": {"partida": "Total activo (A + B)", "valores": [128640036, 12961217]},
  "activo_corriente": {"partida": "B) Activo corriente", "valores": [2280981]},
  "existencias": {"partida": "Existencias", "valores": [13342, 12253]},
  "deudores_comerciales": {"partida": "Clientes por ventas y prestación de servicios", "valores": [1496, 581]},
  "efectivo": {"partida": "Efectivo y otros activos líquidos", "valores": [1283, 13678]},
  "inmovilizado_material": {"partida": "II) Inmovilizado material", "valores": [31989, 32524]},
  "acreedores_comerciales": {"partida": "Proveedores", "valores": [65750, 69365]},
  "cifra_negocios": {"partida": "Importe neto de la cifra de negocios", "valores": [701053, 619242]},
  "otros_ingresos_explotacion": {"partida": "Otros ingresos de explotación", "valores": [247819, 242824]},
  "resultado_explotacion": {"partida": "-) Resultado de explotación", "valores": [-54296, -46755]},
  "amortizacion": {"partida": "A) Dotaciones para amortizaciones", "valores": [0]},
  "gastos_financieros": {"partida": "Gastos financieros", "valores": [3907, 30170]},
  "resultado_antes_impuestos": {"partida": "+) Resultado antes de impuestos", "valores": [163038]},
  "resultado_ejercicio": {"partida": "Resultado del ejercicio", "valores": [5213, 2312]},
  "deuda_credito_lp": {"partida": "Deudas con entidades de crédito a largo plazo", "valores": [5387413, 4571059]},
  "deuda_credito_cp": {"partida": "Deudas con entidades de crédito a corto plazo", "valores": [579883, 15920026]}
}
--- FIN ---

'{\n  "patrimonio_neto": {"partida": "Patrimonio neto", "valores": [1953852]},\n  "fondos_propios": {"partida": "A-1) Fondos propios", "valores": [1972243, 2044735]},\n  "pasivo_no_corriente": {"partida": "Pasivo no corriente", "valores": [90572251, 9039245]},\n  "deudas_lp": {"partida": "Deudas a largo plazo", "valores": [6288936, 5879925]},\n  "deudas_cp": {"partida": "Deudas a corto plazo", "valores": [79947, 14000]},\n  "pasivo_corriente": {"partida": "C) Pasivo corriente", "valores": [313933, 298105]},\n  "total_activo": {"partida": "Total activo (A + B)", "valores": [128640036, 12961217]},\n  "activo_corriente": {"partida": "B) Activo corriente", "valores": [2280981]},\n  "existencias": {"partida": "Existencias", "valores": [13342, 12253]},\n  "deudores_comerciales": {"partida": "Clientes por ventas y prestación de servicios", "valores": [1496, 581]},\n  "efectivo": {"partida": "Efectivo y otros activos líquidos", "valores": [1283, 13678]},\n  "inmovilizado_material": {"partida": "II) Inmovilizado material", "valores": [31989, 32524]},\n  "acreedores_comerciales": {"partida": "Proveedores", "valores": [65750, 69365]},\n  "cifra_negocios": {"partida": "Importe neto de la cifra de negocios", "valores": [701053, 619242]},\n  "otros_ingresos_explotacion": {"partida": "Otros ingresos de explotación", "valores": [247819, 242824]},\n  "resultado_explotacion": {"partida": "-) Resultado de explotación", "valores": [-54296, -46755]},\n  "amortizacion": {"partida": "A) Dotaciones para amortizaciones", "valores": [0]},\n  "gastos_financieros": {"partida": "Gastos financieros", "valores": [3907, 30170]},\n  "resultado_antes_impuestos": {"partida": "+) Resultado antes de impuestos", "valores": [163038]},\n  "resultado_ejercicio": {"partida": "Resultado del ejercicio", "valores": [5213, 2312]},\n  "deuda_credito_lp": {"partida": "Deudas con entidades de crédito a largo plazo", "valores": [5387413, 4571059]},\n  "deuda_credito_cp": {"partida": "Deudas con entidades de crédito a corto plazo", "valores": [579883, 15920026]}\n}'

#### Celda 10 — Visión directa: 2 recortes

Se segmenta la imagen en 2 mitades y se envía cada una al modelo por separado.

**Qué observar en el output:**
- El trozo superior (que contiene la cabecera con fechas) devuelve resultados parciales.
- El trozo inferior pierde la referencia temporal: el modelo ya no sabe a qué fecha corresponde cada columna y devuelve valores sin asignación correcta o JSON malformado.
- Solo 9 de las 22 partidas quedan correctamente identificadas entre los dos trozos.

La segmentación empeora el resultado con visión directa, confirmando la hipótesis inversa.

In [5]:
# CELDA 5 - DEBUG 2 RECORTES

import time
import re

def debug_raw(ruta_imagen, etiqueta):
    b64 = imagen_a_base64(ruta_imagen)
    prompt = f"""Eres un extractor de datos financieros. Esta imagen es un fragmento ({etiqueta}) de un balance/cuenta de pérdidas y ganancias.

Lista de partidas a extraer:
{', '.join(PARTIDAS_OBJETIVO)}

Devuelve SOLO JSON sin markdown con las partidas que encuentres:
{{
  "nombre_partida": {{"partida": "texto literal", "valores": [val1, val2]}},
  ...
}}"""

    response = clients[0].chat.completions.create(
        model=MODELO_VISION,
        messages=[{
            "role": "user",
            "content": [
                {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{b64}"}},
                {"type": "text", "text": prompt}
            ]
        }],
        temperature=0,
        max_tokens=2048
    )

    finish_reason = response.choices[0].finish_reason
    tokens_in  = response.usage.prompt_tokens
    tokens_out = response.usage.completion_tokens
    raw = response.choices[0].message.content
    raw_limpio = re.sub(r"```json\s*|\s*```", "", raw).strip()

    print(f"finish_reason : {finish_reason}")
    print(f"tokens        : {tokens_in} in / {tokens_out} out")
    print(f"--- RAW ---")
    print(raw)
    print(f"--- FIN ---\n")
    
    return raw_limpio

print("=== 2 RECORTES ===")
for i, ruta in enumerate(trozos_2, 1):
    print(f"\n── Trozo {i}/2 ──")
    print(f"ruta: {ruta}")
    debug_raw(ruta, f"trozo {i} de 2")
    if i < len(trozos_2):
        print("esperando 5s...")
        time.sleep(5)

=== 2 RECORTES ===

── Trozo 1/2 ──
ruta: C:\Users\david\Desktop\david\tfm\TFM PYTHON\outputs\excel_balance_exp_trozo_0_0.5.png
finish_reason : stop
tokens        : 2671 in / 658 out
--- RAW ---
```json
{
  "patrimonio_neto": {"partida": "AJ) Patrimonio neto", "valores": [1953852, 2101487, 2343125]},
  "fondos_propios": {"partida": "A) Fondos propios", "valores": [1972243, 2044735, 2285248]},
  "pasivo_no_corriente": {"partida": null, "valores": []},
  "deudas_lp": {"partida": "V. Deudas a largo plazo", "valores": [418896, 2714, 29199]},
  "deudas_cp": {"partida": "VII. Deudas comerciales no corrientes", "valores": [null, null, null]},
  "pasivo_corriente": {"partida": null, "valores": []},
  "total_activo": {"partida": "Total activo (A + B)", "valores": [12840036, 12961217, 12893101]},
  "activo_corriente": {"partida": "A) Activo no corriente", "valores": [12497590, 11416223, 12647002]},
  "existencias": {"partida": "I. Existencias", "valores": [13342, 12333, 11439]},
  "deudores_comerciales": {"partida": "III. Deudores comerciales", "valores": [79885, 79873, 72869]},
  "efectivo": {"partida": "VII. Efectivo y otros activos", "valores": [1283, 12867, 13678]},
  "inmovilizado_material": {"partida": "II. Inmovilizado material", "valores": [31989, 32524, 35545]},
  "acreedores_comerciales": {"partida": "III. Acreedores comerciales", "valores": [null, null, null]},
  "cifra_negocios": {"partida": null, "valores": []},
  "otros_ingresos_explotacion": {"partida": null, "valores": []},
  "resultado_explotacion": {"partida": "VI. Resultado del ejercicio", "valores": [-83138, -246735, -266296]},
  "amortizacion": {"partida": null, "valores": []},
  "gastos_financieros": {"partida": null, "valores": []},
  "resultado_antes_impuestos": {"partida": null, "valores": []},
  "resultado_ejercicio": {"partida": "VI. Resultado del ejercicio", "valores": [-83138, -246735, -266296]},
  "deuda_credito_lp": {"partida": "V. Deudas a largo plazo", "valores": [418896, 2714, 29199]},
  "deuda_credito_cp": {"partida": null, "valores": []}
}
```
--- FIN ---

esperando 5s...

── Trozo 2/2 ──
ruta: C:\Users\david\Desktop\david\tfm\TFM PYTHON\outputs\excel_balance_exp_trozo_0.5_1.0.png
finish_reason : stop
tokens        : 2671 in / 640 out
--- RAW ---
```json
{
  "patrimonio_neto": {"partida": "Total patrimonio neto y pasivo", "valores": [12840036, 12961217]},
  "fondos_propios": {"partida": "I Capital", "valores": [119604, 119604]},
  "pasivo_no_corriente": {"partida": "B) Pasivo no corriente", "valores": [10572251, 10323483]},
  "deudas_lp": {"partida": "Deudas a largo plazo", "valores": [6288936, 5879325]},
  "deudas_cp": {"partida": "C) Pasivo corriente", "valores": [313933, 298105]},
  "pasivo_corriente": {"partida": "C) Pasivo corriente", "valores": [313933, 298105]},
  "total_activo": {"partida": "Total patrimonio neto y pasivo", "valores": [12840036, 12961217]},
  "activo_corriente": {"partida": "I. Capital", "valores": [119604, 119604]},
  "existencias": {"partida": "n.d.", "valores": [null, null]},
  "deudores_comerciales": {"partida": "Acreedores comerciales", "valores": [94624, 112436]},
  "efectivo": {"partida": "n.d.", "valores": [null, null]},
  "inmovilizado_material": {"partida": "n.d.", "valores": [null, null]},
  "acreedores_comerciales": {"partida": "Acreedores comerciales", "valores": [94624, 112436]},
  "cifra_negocios": {"partida": "1. Importe neto de la cifra", "valores": [701053, 619242]},
  "otros_ingresos_explotacion": {"partida": "2. Otros ingresos", "valores": [247819, 199311]},
  "resultado_explotacion": {"partida": "n.d.", "valores": [null, null]},
  "amortizacion": {"partida": "n.d.", "valores": [null, null]},
  "gastos_financieros": {"partida": "n.d.", "valores": [null, null]},
  "resultado_antes_impuestos": {"partida": "n.d.", "valores": [null, null]},
  "resultado_ejercicio": {"partida": "Resultado del ejercicio", "valores": [-83138, -266296]},
  "deuda_credito_lp": {"partida": "Deudas a largo plazo", "valores": [6288936, 5879325]},
  "deuda_credito_cp": {"partida": "Deudas a corto plazo", "valores": [38907, 30170]}
}
```
--- FIN ---

#### Celda 11 — Visión directa: 3 recortes

Misma prueba con 3 fragmentos.

**Qué observar:** el tercer trozo produce un JSON truncado (`finish_reason: length`) porque el output de 22 partidas para un fragmento pequeño supera el límite de tokens de salida. A medida que los trozos son más pequeños, el modelo tiene menos contexto y más dificultad para generar el JSON completo.

In [6]:
# CELDA 6 - DEBUG 3 RECORTES

print("=== 3 RECORTES ===")
for i, ruta in enumerate(trozos_3, 1):
    print(f"\n── Trozo {i}/3 ──")
    print(f"ruta: {ruta}")
    debug_raw(ruta, f"trozo {i} de 3")
    if i < len(trozos_3):
        print("esperando 5s...")
        time.sleep(5)

=== 3 RECORTES ===

── Trozo 1/3 ──
ruta: C:\Users\david\Desktop\david\tfm\TFM PYTHON\outputs\excel_balance_exp_trozo_0_0.33.png
finish_reason : stop
tokens        : 2526 in / 690 out
--- RAW ---
Lo siento, pero no puedo extraer datos directamente de la imagen proporcionada. Sin embargo, puedo guiarte sobre cómo abordar la extracción de datos financieros de un balance o cuenta de pérdidas y ganancias.

Para extraer las partidas solicitadas, necesitaría ver los valores específicos en el documento o tabla que estás analizando. Dado que no puedo ver la imagen directamente, te proporcionaré una estructura JSON con los campos que mencionaste, pero sin valores, ya que no puedo acceder a la información visual.

```json
{
  "patrimonio_neto": {"partida": " Patrimonio Neto", "valores": []},
  "fondos_propios": {"partida": "Fondos Propios", "valores": []},
  "pasivo_no_corriente": {"partida": "Pasivo No Corriente", "valores": []},
  "deudas_lp": {"partida": "Deudas a Largo Plazo", "valores": []},
  "deudas_cp": {"partida": "Deudas a Corto Plazo", "valores": []},
  "pasivo_corriente": {"partida": "Pasivo Corriente", "valores": []},
  "total_activo": {"partida": "Total Activo", "valores": []},
  "activo_corriente": {"partida": "Activo Corriente", "valores": []},
  "existencias": {"partida": "Existencias", "valores": []},
  "deudores_comerciales": {"partida": "Deudores Comerciales", "valores": []},
  "efectivo": {"partida": "Efectivo", "valores": []},
  "inmovilizado_material": {"partida": "Inmovilizado Material", "valores": []},
  "acreedores_comerciales": {"partida": "Acreedores Comerciales", "valores": []},
  "cifra_negocios": {"partida": "Cifra de Negocios", "valores": []},
  "otros_ingresos_explotacion": {"partida": "Otros Ingresos de Explotación", "valores": []},
  "resultado_explotacion": {"partida": "Resultado de Explotación", "valores": []},
  "amortizacion": {"partida": "Amortización", "valores": []},
  "gastos_financieros": {"partida": "Gastos Financieros", "valores": []},
  "resultado_antes_impuestos": {"partida": "Resultado Antes de Impuestos", "valores": []},
  "resultado_ejercicio": {"partida": "Resultado del Ejercicio", "valores": []},
  "deuda_credito_lp": {"partida": "Deuda Crédito a Largo Plazo", "valores": []},
  "deuda_credito_cp": {"partida": "Deuda Crédito a Corto Plazo", "valores": []}
}
```

Para completar los valores, necesitarías revisar manualmente la tabla o documento financiero proporcionado e ir rellenando cada campo con la información correspondiente. Si tienes más detalles o una forma de compartir la información de manera textual, podría ayudarte a completarla.
--- FIN ---

esperando 5s...

── Trozo 2/3 ──
ruta: C:\Users\david\Desktop\david\tfm\TFM PYTHON\outputs\excel_balance_exp_trozo_0.33_0.66.png
finish_reason : stop
tokens        : 2526 in / 731 out
--- RAW ---
```json
{
  "patrimonio_neto": {"partida": "Patrimonio neto", "valores": [1953852, 2101487, 2343125]},
  "fondos_propios": {"partida": "A-1) Fondos propios", "valores": [1972243, 2044735, 2285248]},
  "pasivo_no_corriente": {"partida": "Pasivo no corriente", "valores": [10572251, 10561625, 10323483]},
  "deudas_lp": {"partida": "I) Deudas a largo plazo", "valores": [6288936, 5879325, 3901732]},
  "deudas_cp": {"partida": "III) Deudas a corto plazo", "valores": [68347, 106970, 74786]},
  "pasivo_corriente": {"partida": "C) Pasivo corriente", "valores": [313933, 298105, 226493]},
  "total_activo": {"partida": "Total activo (A + B)", "valores": [12840036, 12961217, 12893101]},
  "activo_corriente": {"partida": "B) Activo corriente", "valores": [342446, 1544994, 246099]},
  "existencias": {"partida": "II Existencias", "valores": [13342, 12333, 11439]},
  "deudores_comerciales": {"partida": "III Deudores comerciales", "valores": [79885, 79873, 72869]},
  "efectivo": {"partida": "VII Efectivo y otros activos", "valores": [1283, 12867, 13678]},
  "inmovilizado_material": {"partida": "Inmovilizado material", "valores": [nan, nan, nan]},
  "acreedores_comerciales": {"partida": "VII Acreedores comerciales", "valores": [nan, nan, nan]},
  "cifra_negocios": {"partida": "Cifra de negocios", "valores": [nan, nan, nan]},
  "otros_ingresos_explotacion": {"partida": "Otros ingresos de explotación", "valores": [nan, nan, nan]},
  "resultado_explotacion": {"partida": "Resultado de explotación", "valores": [-83138, -246735, -266296]},
  "amortizacion": {"partida": "Amortización", "valores": [nan, nan, nan]},
  "gastos_financieros": {"partida": "Gastos financieros", "valores": [nan, nan, nan]},
  "resultado_antes_impuestos": {"partida": "Resultado antes de impuestos", "valores": [nan, nan, nan]},
  "resultado_ejercicio": {"partida": "Resultado del ejercicio", "valores": [-83138, -246735, -266296]},
  "deuda_credito_lp": {"partida": "Deuda con crédito a largo plazo", "valores": [nan, nan, nan]},
  "deuda_credito_cp": {"partida": "Deuda con crédito a corto plazo", "valores": [nan, nan, nan]}
}
```
--- FIN ---

esperando 5s...

── Trozo 3/3 ──
ruta: C:\Users\david\Desktop\david\tfm\TFM PYTHON\outputs\excel_balance_exp_trozo_0.66_1.0.png
finish_reason : stop
tokens        : 2526 in / 618 out
--- RAW ---
```json
{
  "patrimonio_neto": {"partida": "Total patrimonio neto", "valores": [12840036, 12961217]},
  "fondos_propios": {"partida": "Total patrimonio neto", "valores": [12840036, 12961217]},
  "pasivo_no_corriente": {"partida": "Pasivo no corriente", "valores": [nan, nan]},
  "deudas_lp": {"partida": "Deudas con empresas", "valores": [4276854, 4673555]},
  "deudas_cp": {"partida": "Deudas a corto plazo", "valores": [68347, 106970]},
  "pasivo_corriente": {"partida": "Pasivo corriente", "valores": [313933, 298105]},
  "total_activo": {"partida": "Total activo", "valores": [nan, nan]},
  "activo_corriente": {"partida": "Activo corriente", "valores": [nan, nan]},
  "existencias": {"partida": "Existencias", "valores": [nan, nan]},
  "deudores_comerciales": {"partida": "Deudores comerciales", "valores": [nan, nan]},
  "efectivo": {"partida": "Efectivo", "valores": [nan, nan]},
  "inmovilizado_material": {"partida": "Inmovilizado material", "valores": [nan, nan]},
  "acreedores_comerciales": {"partida": "Acreedores comerciales", "valores": [94624, 112436]},
  "cifra_negocios": {"partida": "Importe neto de la cifra de negocios", "valores": [701053, 619242]},
  "otros_ingresos_explotacion": {"partida": "Otros ingresos de explotación", "valores": [nan, nan]},
  "resultado_explotacion": {"partida": "Resultado de explotación", "valores": [nan, nan]},
  "amortizacion": {"partida": "Amortización", "valores": [nan, nan]},
  "gastos_financieros": {"partida": "Gastos financieros", "valores": [nan, nan]},
  "resultado_antes_impuestos": {"partida": "Resultado antes de impuestos", "valores": [nan, nan]},
  "resultado_ejercicio": {"partida": "Resultado del ejercicio", "valores": [12840036, 12961217]},
  "deuda_credito_lp": {"partida": "Deuda con crédito a largo plazo", "valores": [nan, nan]},
  "deuda_credito_cp": {"partida": "Deuda con crédito a corto plazo", "valores": [nan, nan]}
}
```
--- FIN ---

#### Celda 12 — Visión directa: 4 recortes

Con 4 fragmentos el colapso es total: todos los trozos producen JSON truncado o vacío. El modelo no puede generar el JSON de 22 partidas para un fragmento que solo contiene una cuarta parte del balance.

**Conclusión de la batería:** el rendimiento de visión directa **empeora monotónicamente** al aumentar los recortes, en el patrón exactamente opuesto a Docling.

In [7]:
# CELDA 7 - DEBUG 4 RECORTES

print("=== 4 RECORTES ===")
for i, ruta in enumerate(trozos_4, 1):
    print(f"\n── Trozo {i}/4 ──")
    print(f"ruta: {ruta}")
    debug_raw(ruta, f"trozo {i} de 4")
    if i < len(trozos_4):
        print("esperando 5s...")
        time.sleep(5)

=== 4 RECORTES ===

── Trozo 1/4 ──
ruta: C:\Users\david\Desktop\david\tfm\TFM PYTHON\outputs\excel_balance_exp_trozo_0_0.25.png
finish_reason : stop
tokens        : 2526 in / 810 out
--- RAW ---
Lo siento, pero no puedo ver la imagen que mencionas. Sin embargo, puedo guiarte sobre cómo abordar la extracción de datos financieros de una tabla como la que describes.

Basándome en la estructura que proporcionaste, aquí te dejo un ejemplo de cómo podría estructurarse el JSON con las partidas que mencionas. Ten en cuenta que no tengo los valores específicos ya que no puedo visualizar la imagen:

```json
{
  "patrimonio_neto": {"partida": " Patrimonio Neto", "valores": [nan, nan, nan]},
  "fondos_propios": {"partida": "Fondos Propios", "valores": [nan, nan, nan]},
  "pasivo_no_corriente": {"partida": "Pasivo No Corriente", "valores": [nan, nan, nan]},
  "deudas_lp": {"partida": "Deudas a Largo Plazo", "valores": [nan, nan, nan]},
  "deudas_cp": {"partida": "Deudas a Corto Plazo", "valores": [nan, nan, nan]},
  "pasivo_corriente": {"partida": "Pasivo Corriente", "valores": [nan, nan, nan]},
  "total_activo": {"partida": "Total Activo", "valores": [nan, nan, nan]},
  "activo_corriente": {"partida": "Activo Corriente", "valores": [nan, nan, nan]},
  "existencias": {"partida": "Existencias", "valores": [nan, nan, nan]},
  "deudores_comerciales": {"partida": "Deudores Comerciales", "valores": [nan, nan, nan]},
  "efectivo": {"partida": "Efectivo", "valores": [nan, nan, nan]},
  "inmovilizado_material": {"partida": "Inmovilizado Material", "valores": [31989, 32524, 35545]},
  "acreedores_comerciales": {"partida": "Acreedores Comerciales", "valores": [nan, nan, nan]},
  "cifra_negocios": {"partida": "Cifra de Negocios", "valores": [nan, nan, nan]},
  "otros_ingresos_explotacion": {"partida": "Otros Ingresos de Explotación", "valores": [nan, nan, nan]},
  "resultado_explotacion": {"partida": "Resultado de Explotación", "valores": [nan, nan, nan]},
  "amortizacion": {"partida": "Amortización", "valores": [nan, nan, nan]},
  "gastos_financieros": {"partida": "Gastos Financieros", "valores": [nan, nan, nan]},
  "resultado_antes_impuestos": {"partida": "Resultado antes de Impuestos", "valores": [nan, nan, nan]},
  "resultado_ejercicio": {"partida": "Resultado del Ejercicio", "valores": [nan, nan, nan]},
  "deuda_credito_lp": {"partida": "Deuda Crédito a Largo Plazo", "valores": [nan, nan, nan]},
  "deuda_credito_cp": {"partida": "Deuda Crédito a Corto Plazo", "valores": [nan, nan, nan]}
}
```

Para extraer los datos, necesitaría ver la tabla completa o tener acceso a los valores específicos que se encuentran en cada fila y columna correspondiente a las partidas mencionadas.

Si puedes proporcionar más detalles o la ubicación exacta de cada partida dentro de la tabla (o directamente los valores), podría ayudarte a completar el JSON con los valores correctos.
--- FIN ---

esperando 5s...

── Trozo 2/4 ──
ruta: C:\Users\david\Desktop\david\tfm\TFM PYTHON\outputs\excel_balance_exp_trozo_0.25_0.5.png
finish_reason : stop
tokens        : 2526 in / 546 out
--- RAW ---
```json
{
  "patrimonio_neto": {"partida": "A) Patrimonio neto", "valores": [1953852]},
  "fondos_propios": {"partida": "A-1) Fondos propios", "valores": [1972243]},
  "pasivo_no_corriente": {"partida": "Pasivo", "valores": [nan]},
  "deudas_lp": {"partida": "nan", "valores": [nan]},
  "deudas_cp": {"partida": "nan", "valores": [nan]},
  "pasivo_corriente": {"partida": "B) Pasivo corriente", "valores": [nan]},
  "total_activo": {"partida": "Total activo (A + B)", "valores": [12840036]},
  "activo_corriente": {"partida": "B) Activo corriente", "valores": [342446]},
  "existencias": {"partida": "II Existencias", "valores": [13342]},
  "deudores_comerciales": {"partida": "III Deudores comerciales y otras cuentas a cobrar", "valores": [79885]},
  "efectivo": {"partida": "VII Efectivo y otros activos líquidos", "valores": [1283]},
  "inmovilizado_material": {"partida": "II Inmovilizado material", "valores": [31989]},
  "acreedores_comerciales": {"partida": "VII Deudas comerciales no corrientes", "valores": [nan]},
  "cifra_negocios": {"partida": "nan", "valores": [nan]},
  "otros_ingresos_explotacion": {"partida": "nan", "valores": [nan]},
  "resultado_explotacion": {"partida": "VII Resultado de explotación", "valores": [nan]},
  "amortizacion": {"partida": "nan", "valores": [nan]},
  "gastos_financieros": {"partida": "nan", "valores": [nan]},
  "resultado_antes_impuestos": {"partida": "nan", "valores": [nan]},
  "resultado_ejercicio": {"partida": "VI Resultado del ejercicio", "valores": [-83138]},
  "deuda_credito_lp": {"partida": "nan", "valores": [nan]},
  "deuda_credito_cp": {"partida": "nan", "valores": [nan]}
}
```
--- FIN ---

esperando 5s...

── Trozo 3/4 ──
ruta: C:\Users\david\Desktop\david\tfm\TFM PYTHON\outputs\excel_balance_exp_trozo_0.5_0.75.png
finish_reason : stop
tokens        : 2526 in / 637 out
--- RAW ---
```json
{
  "patrimonio_neto": {"partida": "nan", "valores": [nan]},
  "fondos_propios": {"partida": "I Capital", "valores": [119604, 119604]},
  "pasivo_no_corriente": {"partida": "B) Pasivo no corriente", "valores": [10572251, 10561625, 10323483]},
  "deudas_lp": {"partida": "II Deudas a largo plazo", "valores": [6288936, 5879325, 3901732]},
  "deudas_cp": {"partida": "III Deudas a corto plazo", "valores": [68347, 106970, 74786]},
  "pasivo_corriente": {"partida": "C) Pasivo corriente", "valores": [313933, 298105, 226493]},
  "total_activo": {"partida": "nan", "valores": [nan]},
  "activo_corriente": {"partida": "nan", "valores": [nan]},
  "existencias": {"partida": "nan", "valores": [nan]},
  "deudores_comerciales": {"partida": "nan", "valores": [nan]},
  "efectivo": {"partida": "nan", "valores": [nan]},
  "inmovilizado_material": {"partida": "nan", "valores": [nan]},
  "acreedores_comerciales": {"partida": "VI Acreedores comerciales", "valores": [n.d., n.d., n.d., 94624, 112436, 82987]},
  "cifra_negocios": {"partida": "nan", "valores": [nan]},
  "otros_ingresos_explotacion": {"partida": "nan", "valores": [nan]},
  "resultado_explotacion": {"partida": "nan", "valores": [nan]},
  "amortizacion": {"partida": "nan", "valores": [nan]},
  "gastos_financieros": {"partida": "nan", "valores": [nan]},
  "resultado_antes_impuestos": {"partida": "nan", "valores": [nan]},
  "resultado_ejercicio": {"partida": "VI Resultado del ejercicio", "valores": [-83138, -246735, -266296]},
  "deuda_credito_lp": {"partida": "1. Obligaciones y otros vi", "valores": [5387413, 4571059, 2556641, 38907, 30170, 12554]},
  "deuda_credito_cp": {"partida": "2. Deudas con entidades", "valores": [901345, 1308026, 1340473, 29383, 68542, 60899]}
}
```
--- FIN ---

esperando 5s...

── Trozo 4/4 ──
ruta: C:\Users\david\Desktop\david\tfm\TFM PYTHON\outputs\excel_balance_exp_trozo_0.75_1.0.png
finish_reason : stop
tokens        : 2526 in / 579 out
--- RAW ---
```json
{
  "patrimonio_neto": {"partida": "Total patrimonio neto y pasivo", "valores": [12840036]},
  "fondos_propios": {"partida": "Total patrimonio neto y pasivo", "valores": [12840036]},
  "pasivo_no_corriente": {"partida": "Deudas a largo plazo", "valores": [106970]},
  "deudas_lp": {"partida": "Deudas a largo plazo", "valores": [106970]},
  "deudas_cp": {"partida": "Deudas a corto plazo", "valores": [68347]},
  "pasivo_corriente": {"partida": "Deudas a corto plazo", "valores": [68347]},
  "total_activo": {"partida": "Total patrimonio neto y pasivo", "valores": [12840036]},
  "activo_corriente": {"partida": "Deudores comerciales", "valores": [112436]},
  "existencias": {"partida": "Variación de existencias", "valores": [247819]},
  "deudores_comerciales": {"partida": "Deudores comerciales", "valores": [112436]},
  "efectivo": {"partida": "Tesorería", "valores": [5213]},
  "inmovilizado_material": {"partida": "Inmovilizado material", "valores": [12961217]},
  "acreedores_comerciales": {"partida": "Acreedores comerciales", "valores": [94624]},
  "cifra_negocios": {"partida": "Importe neto de la cifra", "valores": [701053]},
  "otros_ingresos_explotacion": {"partida": "Otros ingresos de explotación", "valores": [30170]},
  "resultado_explotacion": {"partida": "Resultado de explotación", "valores": [12554]},
  "amortizacion": {"partida": "Amortización", "valores": [68542]},
  "gastos_financieros": {"partida": "Gastos financieros", "valores": [60899]},
  "resultado_antes_impuestos": {"partida": "Resultado antes de impuestos", "valores": [391]},
  "resultado_ejercicio": {"partida": "Resultado del ejercicio", "valores": [391]},
  "deuda_credito_lp": {"partida": "Deuda con características", "valores": [n.d.]},
  "deuda_credito_cp": {"partida": "Deudas con entidades", "valores": [29383]}
}
```
--- FIN ---

---

### Resultados del experimento de visión

El experimento evalúa las 4 configuraciones de recorte (0, 2, 3, 4) con dos versiones del prompt: una inicial más directa y una mejorada con reglas más estrictas. Los outputs de las siguientes celdas muestran el JSON raw devuelto por el modelo para cada configuración.

**Tabla resumen de resultados (documentada en la memoria):**

| Recortes | Partidas encontradas | Tokens totales | Problemas observados |
|:---:|:---:|:---:|---|
| **0** (imagen completa) | 22/22 | 3.309 | Valores inventados, solo 2 valores por partida en vez de 3, PyG vacía |
| **2** | 9/22 | 6.333 | JSON truncado en trozo 1, pérdida de referencia temporal |
| **3** | 12/22 | 8.958 | JSON truncado en trozo 3, valores incoherentes |
| **4** | 0/22 | 12.269 | JSON truncado en todos los trozos |

---

## Conclusiones del experimento

### Docling con recortes ✅

La densidad de filas por imagen es el **factor determinante** de la calidad de extracción con Docling. El recorte en fragmentos horizontales con solapamiento es el mecanismo más efectivo para reducirla.

La mejora es progresiva y consistente tanto en imágenes densas como limpias:

| Recortes | Resultado con Docling |
|:---:|---|
| 0 | Filas fusionadas, errores estructurales graves |
| 2 | Mejora notable, fusiones residuales en bordes |
| 3 | Mayoría de partidas individualizadas |
| **4** | **Extracción limpia, resultado correcto** |

### Visión directa ❌

El enfoque de visión directa con `llama-4-scout` (modelo gratuito) **no es viable** para este tipo de documentos. Sus limitaciones son estructurales:

- Con imagen completa: identifica las 22 partidas pero con valores incorrectos, columnas mezcladas y PyG vacía.
- Al segmentar: los trozos pierden la cabecera con las fechas y el JSON se trunca por superar el límite de tokens de salida.
- El coste en tokens **escala linealmente** con el número de recortes sin ninguna mejora de calidad.

> **Nota importante:** modelos de mayor capacidad (GPT-4o, Claude Sonnet) resuelven la extracción por visión directa sin estos problemas. La limitación es específica de los modelos gratuitos disponibles en el momento del experimento. El pipeline Docling se adoptó para garantizar reproducibilidad sin coste de inferencia.

### Heurística de recortes adoptada

| Tipo de documento | Recortes | Justificación |
|---|:---:|---|
| Imagen única con balance+PyG completos | 4 | Alta densidad, todo comprimido en un plano |
| PDF — páginas con balance completo | 0 | Cada página tiene densidad baja, Docling lee bien directamente |
| PDF — páginas con continuación de tabla | 0 | Idem |

El número óptimo de recortes **no es universal**: depende de la densidad de filas de cada imagen concreta. En producción, podría automatizarse detectando celdas fusionadas en el output de Docling e incrementando el número de recortes hasta eliminarlas.