# Pipeline de extracción de ratios financieros — Imagen

Notebook correspondiente al **experimento de extracción desde imagen** descrito en la sección 4.3 de la memoria del TFM.

El objetivo es extraer las mismas 22 partidas contables y calcular los mismos ratios que en el pipeline Excel, pero cuando el estado financiero llega en formato imagen (PNG, JPEG), ya sea una exportación directa del Excel, una captura de pantalla o una fotografía de un documento impreso.

## Empresa de prueba
**Grifols, S.A.** — imagen generada directamente a partir del Excel de SABI que comprime balance y cuenta de PyG de los tres ejercicios (2022, 2023, 2024) en un único plano visual.

## El problema de la densidad

Una imagen que contiene balance completo y PyG de tres ejercicios tiene una densidad de filas tan alta que Docling fusiona filas adyacentes en una misma celda. La separación visual entre filas es inferior al umbral que el modelo de layout de Docling necesita para identificarlas como entidades separadas.

**Solución:** segmentar la imagen en trozos horizontales con solapamiento del 5% antes de pasarlos a Docling, reduciendo la densidad hasta que la separación es suficiente. El experimento sistemático que justifica el número óptimo de recortes está en `experimentos_recortes.ipynb`.

## Pipeline completo

```
Imagen (.png / .jpg)
    │
    ├─ Recorte en N trozos con overlap 5%      ← PIL
    │
    ├─ Extracción estructurada de cada trozo   ← Docling + RapidOCR
    │
    ├─ Detección de fechas canónicas           ← LLM multimodal (solo cabecera)
    │
    ├─ Detección de layout por trozo           ← LLM textual (muestra serializada)
    │
    ├─ DataFrame de conceptos                  ← Python determinista
    │
    ├─ Selección de 22 partidas                ← LLM (índice posicional)
    │
    ├─ Extracción de valores                   ← Python determinista
    │
    └─ Cálculo de 22 ratios                    ← Python determinista
```

A partir del paso de construcción del DataFrame, la lógica es **idéntica al pipeline Excel** y produce resultados equivalentes.

---

## Celda 1 — Setup, recorte de imagen y extracción con Docling

Esta celda hace tres cosas:

**1. Configuración del entorno**
API keys desde variables de entorno (`.env`), modelos Groq y directorios de entrada/salida. Se definen tres modelos: `MODELO1` y `MODELO2` para llamadas de texto y `MODELO3` (`llama-4-scout-17b`) para la llamada multimodal de extracción de fechas.

**2. Función `recortar_y_escalar`**
Divide la imagen en un fragmento definido por `(top_pct, bottom_pct)` añadiendo un solapamiento del 5% en cada extremo (`overlap_pct=0.05`). El overlap garantiza que ninguna fila quede cortada entre dos trozos consecutivos. Aplica escalado ×2 con `Image.LANCZOS` antes de guardar para mejorar la resolución que recibe el OCR.

**3. Pipeline de extracción**
Para cada imagen en la carpeta de inputs genera 4 trozos (cuartos: 0-25%, 25-50%, 50-75%, 75-100%), pasa cada trozo por `DocumentConverter` de Docling y acumula los DataFrames resultantes en `dfs_trozos`.

> **Por qué 4 trozos:** el experimento en `experimentos_recortes.ipynb` demuestra que con esta imagen concreta 4 recortes es el número a partir del cual Docling deja de fusionar filas. El número óptimo depende de la densidad de filas de cada imagen y no es universal.

In [4]:
#En esta celda se hace la lectura de las imagenes y se recortar cada una en tres partes porque sino las celdas son muy pequeñas y docling junta algunas filas.

from PIL import Image
import pandas as pd
import json
import os

GROQ_API_KEY1  = os.getenv("GROQ_API_KEY_1", "")
GROQ_API_KEY2  = os.getenv("GROQ_API_KEY_2", "")
GROQ_BASE_URL = "https://api.groq.com/openai/v1"
MODELO1        = "openai/gpt-oss-120b"
MODELO2        = "llama-3.3-70b-versatile"
MODELO3 = "meta-llama/llama-4-scout-17b-16e-instruct"


def recortar_y_escalar(ruta_imagen, top_pct, bottom_pct, escala=2, overlap_pct=0.05):
    img = Image.open(ruta_imagen)
    w, h = img.size
    top    = max(0, int(h * (top_pct - overlap_pct)))
    bottom = min(h, int(h * (bottom_pct + overlap_pct)))
    recorte = img.crop((0, top, w, bottom))
    recorte = recorte.resize((w * escala, (bottom - top) * escala), Image.LANCZOS)
    nombre = os.path.splitext(os.path.basename(ruta_imagen))[0]
    OUTPUTS = r"C:\Users\perdi\Desktop\tfm\TFM PYTHON\outputs"
    ruta_salida = os.path.join(OUTPUTS, f"{nombre}_trozo_{top_pct}_{bottom_pct}.png")
    recorte.save(ruta_salida)
    print(f"Guardado: {ruta_salida} — tamaño: {recorte.size}")
    return ruta_salida

INPUTS  = r"C:\Users\perdi\Desktop\tfm\TFM PYTHON\inputs"
CORTES = [(0, 0.25), (0.25, 0.50), (0.50, 0.75), (0.75, 1.0)]

imagenes = [
    os.path.join(INPUTS, f)
    for f in os.listdir(INPUTS)
    if f.lower().endswith(".png")
]
print(f"Imágenes encontradas: {len(imagenes)}")

from docling.document_converter import DocumentConverter
converter = DocumentConverter()

dfs_trozos = []
for ruta_imagen in imagenes:
    print(f"\n{'='*50}\n📄 {os.path.basename(ruta_imagen)}")
    trozos = [recortar_y_escalar(ruta_imagen, top, bot) for top, bot in CORTES]
    for i, trozo in enumerate(trozos, 1):
        print(f"\n── Trozo {i} ──")
        result = converter.convert(trozo)
        print(f"  Tablas detectadas: {len(result.document.tables)}")
        for tabla in result.document.tables:
            df_trozo = tabla.export_to_dataframe()
            df_trozo = pd.DataFrame(
                [df_trozo.columns.tolist()] + df_trozo.values.tolist()
            )
            df_trozo.columns = [f"C{j}" for j in range(df_trozo.shape[1])]
            dfs_trozos.append(df_trozo)

Imágenes encontradas: 2

==================================================
📄 excel_balance (limpio).png
Guardado: C:\Users\perdi\Desktop\tfm\TFM PYTHON\outputs\excel_balance (limpio)_trozo_0_0.25.png — tamaño: (2924, 1778)
Guardado: C:\Users\perdi\Desktop\tfm\TFM PYTHON\outputs\excel_balance (limpio)_trozo_0.25_0.5.png — tamaño: (2924, 2076)
Guardado: C:\Users\perdi\Desktop\tfm\TFM PYTHON\outputs\excel_balance (limpio)_trozo_0.5_0.75.png — tamaño: (2924, 2076)

[INFO] 2026-05-07 22:18:04,193 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 22:18:04,197 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-05-07 22:18:04,198 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_det_mobile.onnx
[INFO] 2026-05-07 22:18:04,292 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 22:18:04,294 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-05-07 22:18:04,295 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_ppocr_mobile_v2.0_cls_mobile.onnx
[INFO] 2026-05-07 22:18:04,339 [RapidOCR] base.py:22: Using engine_name: onnxruntime
[INFO] 2026-05-07 22:18:04,348 [RapidOCR] download_file.py:60: File exists and is valid: C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx

Guardado: C:\Users\perdi\Desktop\tfm\TFM PYTHON\outputs\excel_balance (limpio)_trozo_0.75_1.0.png — tamaño: (2924, 1780)

── Trozo 1 ──

[INFO] 2026-05-07 22:18:04,349 [RapidOCR] main.py:57: Using C:\Users\perdi\Desktop\tfm\TFM PYTHON\entornotfm\Lib\site-packages\rapidocr\models\ch_PP-OCRv4_rec_mobile.onnx
Loading weights: 100%|██████████| 770/770 [00:00<00:00, 11005.30it/s]
Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1

── Trozo 2 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1

── Trozo 3 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1

── Trozo 4 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1

==================================================
📄 excel_pyg (limpio).png
Guardado: C:\Users\perdi\Desktop\tfm\TFM PYTHON\outputs\excel_pyg (limpio)_trozo_0_0.25.png — tamaño: (2924, 1092)
Guardado: C:\Users\perdi\Desktop\tfm\TFM PYTHON\outputs\excel_pyg (limpio)_trozo_0.25_0.5.png — tamaño: (2924, 1274)
Guardado: C:\Users\perdi\Desktop\tfm\TFM PYTHON\outputs\excel_pyg (limpio)_trozo_0.5_0.75.png — tamaño: (2924, 1274)
Guardado: C:\Users\perdi\Desktop\tfm\TFM PYTHON\outputs\excel_pyg (limpio)_trozo_0.75_1.0.png — tamaño: (2924, 1092)

── Trozo 1 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1

── Trozo 2 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1

── Trozo 3 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1

── Trozo 4 ──

Usage of TableItem.export_to_dataframe() without `doc` argument is deprecated.

  Tablas detectadas: 1

## Celda 2 — Extracción de fechas canónicas con LLM multimodal

Las fechas de los ejercicios solo aparecen en la cabecera de la imagen (primeras ~250px de alto). La función `extraer_fechas_vision`:
1. Recorta únicamente esa franja superior de la imagen.
2. La codifica en base64.
3. La envía al modelo de visión `llama-4-scout-17b` con un prompt minimalista que pide exclusivamente las fechas en formato `DD/MM/AAAA`.

**Por qué usar visión solo para las fechas y no para todo el balance:**
Los modelos de visión gratuitos presentan errores sistemáticos al leer valores numéricos de tablas densas: confunden columnas, inventan partidas y asignan valores incorrectos (documentado en `experimentos_recortes.ipynb`). Sin embargo, son perfectamente fiables para leer texto de cabecera en un recorte pequeño y limpio. Se usa el mínimo indispensable de visión directa para minimizar el riesgo de error.

Las fechas detectadas aquí (`fechas_canonicas`) se usarán en el paso de layout para asignar correctamente cada columna de valores a su período.

In [5]:
import base64

from openai import OpenAI

client1 = OpenAI(
    api_key=GROQ_API_KEY1,
    base_url=GROQ_BASE_URL
)

MODELO3 = "meta-llama/llama-4-scout-17b-16e-instruct"

import base64
import tempfile
import os

def extraer_fechas_vision(ruta_imagen):
    img = Image.open(ruta_imagen)
    w, h = img.size
    header = img.crop((0, 0, w, min(250, h)))
    
    tmp_path = os.path.join(tempfile.gettempdir(), "header_fechas.png")
    header.save(tmp_path)
    with open(tmp_path, "rb") as f:
        img_b64 = base64.b64encode(f.read()).decode()
    
    response = client1.chat.completions.create(
        model=MODELO3,
        messages=[{
            "role": "user",
            "content": [
                {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{img_b64}"}},
                {"type": "text", "text": "Extrae todas las fechas que aparecen en esta imagen (formato DD/MM/AAAA). Devuelve SOLO un JSON así: {\"fechas\": [\"31/12/2024\", \"31/12/2023\"]}. Sin markdown."}
            ]
        }],
        temperature=0
    )
    raw = response.choices[0].message.content.strip().strip("```json").strip("```").strip()
    return json.loads(raw)["fechas"]

## Celda 3 — Ejecución: detección de fechas de la imagen de balance

Llama a `extraer_fechas_vision` sobre la primera imagen de la carpeta de inputs, que es la que contiene la cabecera con los períodos. El resultado (`fechas_canonicas`) se imprime para verificación antes de continuar.

In [6]:
# Extraer fechas de la primera imagen (el balance, que es donde están las fechas de cabecera)
fechas_canonicas = extraer_fechas_vision(r"C:\Users\perdi\Desktop\tfm\TFM PYTHON\inputs\excel_balance (limpio).png")
print(f"Fechas detectadas: {fechas_canonicas}")

Fechas detectadas: ['31/12/2024', '31/12/2023', '31/12/2022']

## Celda 4 — Inspección de los DataFrames extraídos por Docling

Celda de diagnóstico: muestra todos los DataFrames de `dfs_trozos` para verificar visualmente que Docling ha separado correctamente las filas y que no quedan celdas fusionadas. 

Es útil ejecutar esta celda al cambiar la imagen de entrada para decidir si el número de recortes es suficiente: si se observan filas combinadas (una celda contiene el texto de dos o más partidas concatenadas), hay que aumentar el número de trozos en la celda 1.

In [7]:
#Esta celda es para revisar las tablas sacadas de cada trozo

for i, df in enumerate(dfs_trozos, 1):
    print(f"\n── Tabla {i} ──")
    display(df)

── Tabla 1 ──

,C0,C1,C2,C3,C4
0,,GRIFOLS SA,,,
1,Balance/Estadoderesultados,,,,
2,CuentasNoConsolidadas,31/12/2024,,,31/12/2022
3,,mil EUR,,,mil EUR
4,,,,12meses,
5,,Aprobado,Aprobado,Aprobado,
6,,NormalPGC2007,Normal PGC 2007,NormalPGC2007,
7,Activo,,,,
8,A)Activonocorriente,12497590,11416223,12647002,
9,IInmovilizadointangible,23959,19941,23213,
10,1.Fondodecomerciodeconsolidacion,n.d.,n.d.,n.d.,
11,2. Investigaci6n,n.d.,n.d.,n.d.,
12,3.Propiedad intelectual,n.d.,n.d.,n.d.,
13,5.Otro inmovilizadointangible,n.d.,n.d.,n.d.,
14,IInmovilizadomaterial,31989,32524,35545,
15,1.Terrenosy construcciones,11064,11151,11239,
16,2.Instalacionestecnicasy otro inmovilizado mat...,16685,14926,18207,
17,3.Inmovilizado en cursoy anticipos,4240,6447,6099,
18,I Inversionesinmobiliarias,102332,108977,80458,
19,IVInversionesenempresasdelgrupoyasociadasalarg...,11838151,11202474,12469437,
20,1.Participacionespuestas en equivalencia,n.d.,n.d.,n.d.,
21,2.Creditosasociedadespuestasenequivalencia,n.d.,n.d.,n.d.,
22,3.Otrosactivosfinancieros,n.d.,n.d.,n.d.,
23,4. Otras inversiones,n.d.,n.d.,n.d.,
24,VInversionesfinancierasalargoplazo,418896,2714,29199,
25,VIActivosporimpuestodiferido,82263,49593,9150,
26,VllDeudascomercialesnocorrientes,n.d.,n.d.,n.d.,
27,B)Activo corriente,342446,1544994,246099,
28,IActivosnocorrientesmantenidosparalaventa,n.d.,1360089,n.d.,
29,IlExistencias,13342,12333,11439,
30,IlIDeudorescomercialesyotrascuentasacobrar,79885,79873,72869,

── Tabla 2 ──

,C0,C1,C2,C3
0,2.Creditosasociedadespuestasenequivalencia,n.d.,n.d.,n.d.
1,3.Otros activos financieros,n.d.,n.d.,n.d.
2,4.Otras inversiones,n.d.,n.d.,n.d.
3,VInversionesfinancierasalargoplazo,418896,2714,29199
4,VIActivosporimpuestodiferido,82263,49593,9150
5,VllDeudascomercialesnocorrientes,n.d.,n.d.,n.d.
6,B)Activo corriente,342446,1544994,246099
7,IActivosnocorrientesmantenidosparalaventa,n.d.,1360089,n.d.
8,IIExistencias,13342,12333,11439
9,IllDeudorescomercialesyotrascuentasacobrar,79885,79873,72869
10,1.Clientesporventasyprestacionesdeservicios,1496,581,833
11,a)Clientesporventasyprestacionesdeserviciosa l...,n.d.,n.d.,n.d.
12,b) Clientes por ventasy prestaciones deservici...,1496,581,833
13,2.Sociedadespuestas enequivalencia,n.d.,n.d.,n.d.
14,3.Activos porimpuesto corriente,16453,12303,2486
15,4.Otrosdeudores,n.d.,n.d.,n.d.
16,IVInversionesenempresasdelgrupoyasociadasacort...,228981,47884,123033
17,1.Creditos a empresaspuestos enequivalencia,n.d.,n.d.,n.d.
18,2.Otros activos financieros,n.d.,n.d.,n.d.
19,3.Otras inversiones,n.d.,n.d.,n.d.
20,VInversionesfinancierasa cortoplazo,2752,20917,11569
21,VIPeriodificacionesacortoplazo,16203,11031,13511
22,VllEfectivoyotrosactivoslfquidosequivalentes,1283,12867,13678
23,Total activo (A + B),12840036,12961217,12893101
24,Pasivo,,,
25,A)Patrimonioneto,1953852,2101487,2343125
26,A-1) Fondos propios,1972243,2044735,2285248
27,ICapital,119604,119604,119604
28,1.Capital escriturado,119604,119604,119604
29,2. (Capital no exigido),n.d.,n.d.,n.d.
30,IlPrima de emision,910728,910728,910728
31,1.Reserva derevalorizaci6n,n.d.,n.d.,n.d.
32,2.Reserva de capitalizacion,n.d.,n.d.,n.d.
33,3.Otras reservas,n.d.,n.d.,n.d.
34,I Reservasyresultadosdeejerciciosanteriores,n.d.,n.d.,n.d.
35,IV (Acciones y participaciones en patrimonio p...,-134448,-152748,-162220
36,VOtras aportacionesdesocios,n.d.,n.d.,n.d.
37,nante,-83138,246735,266296

── Tabla 3 ──

,C0,C1,C2,C3
0,A-1)Fondospropios,1972243,2044735,2285248
1,ICapital,119604,119604,119604
2,1.Capital escriturado,119604,119604,119604
3,2. (Capital no exigido),n.d.,n.d.,n.d.
4,IlPrima de emision,910728,910728,910728
5,1.Reserva derevalorizacion,n.d.,n.d.,n.d.
6,2.Reserva de capitalizacion,n.d.,n.d.,n.d.
7,3.Otrasreservas,n.d.,n.d.,n.d.
8,Il Reservasyresultadosdeejerciciosanteriores,n.d.,n.d.,n.d.
9,IV(Accionesyparticipacionesenpatrimoniopropias...,-134448,-152748,-162220
10,V Otrasaportacionesdesocios,n.d.,n.d.,n.d.
11,VIResultadodelejercicioatribuidoalasociedaddom...,-83138,-246735,-266296
12,VllDividendoacuenta),n.d.,n.d.,n.d.
13,VIllOtrosinstrumentos depatrimonioneto,6647,8282,7303
14,A-2)Ajustesporcambiosdevalor,-18391,56752,57798
15,"IActivosnocorrientesypasivosvinculados,manteni...",n.d.,n.d.,n.d.
16,IDiferenciadeconversi6n,n.d.,n.d.,n.d.
17,IlOtros,n.d.,n.d.,n.d.
18,"A-3)Subvenciones,donacionesylegadosrecibidos",n.d.,n.d.,79
19,A-4)Sociosextemos,n.d.,n.d.,n.d.
20,B)Pasivonocorriente,10572251,10561625,10323483
21,IProvisionesalargoplazo,3217,3838,n.d.
22,IIDeudas a largoplazo,6288936,5879325,3901732
23,1.obligacionesy otrosvaloresnegociables,5387413,4571059,2556641
24,2.Deudasconentidadesdecredito,901345,1308026,1340473
25,3.Acreedoresporarrendamientofinanciero,21,27,52
26,4. Otros pasivos financieros,n.d.,n.d.,n.d.
27,IIDeudasconempresasdelgrupoyasociadasalargoplazo,4276854,4673555,6419171
28,1.Deudasconsociedadespuestaenequivalencia,n.d.,n.d.,n.d.
29,2. Otras deudas,n.d.,n.d.,n.d.
30,IVPasivos porimpuesto diferido,3244,4907,2580
31,VPeriodificacionesa largoplazo,n.d.,n.d.,n.d.
32,VIAcreedorescomercialesnocorientes,n.d.,n.d.,n.d.
33,VllDeuda concaracteristicas especialesa largop...,n.d.,n.d.,n.d.
34,C)Pasivo corriente,313933,298105,226493

── Tabla 4 ──

,C0,C1,C2,C3
0,3.Acreedoresporarrendamientofinanciero,,21 27,52
1,4. Otros pasivos financieros,n.d.,n.d.,n.d.
2,IlI Deudasconempresasdel grupoyasociadas alarg...,4276854,4673555,6419171
3,1.Deudasconsociedadespuestaenequivalencia,n.d.,n.d.,n.d.
4,2.Otras deudas,n.d.,n.d.,n.d.
5,IVPasivosporimpuestodiferido,3244,4907,2580
6,VPeriodificacionesalargoplazo,n.d.,n.d.,n.d.
7,VIAcreedorescomercialesnocorrientes,n.d.,n.d.,n.d.
8,VllDeudaconcaracteristicasespecialesalargoplazo,n.d.,n.d.,n.d.
9,C)Pasivo corriente,313933,298105,226493
10,IPasivosvinculadosconactivosnocorrientesmanten...,n.d.,n.d.,n.d.
11,IIProvisiones a cortoplazo,79947,14000,7000
12,1.Provisionesporderechosdeemisiondegasesdeefec...,n.d.,n.d.,n.d.
13,2. Otras provisiones,79947,14000,7000
14,IIDeudasacortoplazo,68347,106970,74786
15,1. Obligaciones y otros valores negociables,38907,30170,12554
16,2.Deudas conentidades decredito,29383,68542,60899
17,3.Acreedoresporarrendamientofinanciero,n.d.,25,391
18,4. Otros pasivos financieros,n.d.,n.d.,n.d.
19,IVDeudasconempresasdel grupoyasociadasa cortop...,62437,64699,61720
20,1.Deudas consociedadespuesta en equivalencia,n.d.,n.d.,n.d.
21,2.Otrasdeudas,n.d.,n.d.,n.d.
22,VAcreedorescomercialesyotrascuentasapagar,94624,112436,82987
23,1.Proveedores,65750,69365,58812
24,a)Proveedores a largo plazo,n.d.,n.d.,n.d.
25,b)Proveedores a cortoplazo,65750,69365,58812
26,"2.Proveedores,empresas del grupoy asociadas",n.d.,n.d.,n.d.
27,3.Pasivosporimpuesto corriente,n.d.,n.d.,n.d.
28,4.Otros acreedores,n.d.,n.d.,n.d.
29,VIPeriodificacionesacortoplazo,8578,n.d.,n.d.
30,VllDeudaconcaracteristicasespecialesacortoplazo,n.d.,n.d.,n.d.
31,Totalpatrimonio netoypasivo(A+B+C),12840036,12961217,12893101

── Tabla 5 ──

,C0,C1,C2,C3
0,0,1,2,3
1,A)Operacionescontinuadas,A)Operacionescontinuadas,A)Operacionescontinuadas,A)Operacionescontinuadas
2,1.Importenetodelacifra denegocios,701053,619242,488639
3,a)Ventas,n.d.,n.d.,n.d.
4,b)Prestacionesde servicios,247819,242824,199311
5,2.Variaciondeexistenciasdeproductosterminadosy...,n.d.,n.d.,n.d.
6,3.Trabajosrealizadosporlaempresaparasuactivo,5213,2312,5478
7,4.Aprovisionamientos,-4625,-4661,-7376
8,a)Consumodemercaderfas,n.d.,n.d.,n.d.
9,b)Consumodemateriasprimasyotrasmateriasconsumi...,-4421,-4244,-7074
10,c)Trabajosrealizadosporotrasempresas,n.d.,n.d.,n.d.
11,"d)Deteriorodemercaderfas,materiasprimasyotrosa...",-204,-417,-302
12,5.Otrosingresosdeexplotacion,5069,2582,1956
13,a)Ingresosaccesoriosyotrosdegestioncorriente,4971,2495,1881
14,b)Subvencionesdeexplotacionincorporadasalresul...,98,87,75
15,6.Gastos depersonal,-113208,-119602,-81088
16,"a)Sueldos,salariosyasimilados",-95399,-103507,-65742
17,b) Cargas sociales,-17809,-16095,-15194
18,c)Provisiones,n.d.,n.d.,-152
19,7.Otrosgastosdeexplotacion,-294670,-269381,-214386
20,"a)Perdidas,deterioroyvariaciondeprovisionespor...",n.d.,n.d.,n.d.

── Tabla 6 ──

,C0,C1,C2,C3
0,b)Subvencionesdeexplotacionincorporadas alresu...,98,87,75
1,6.Gastos depersonal,-113208,-119602,-81088
2,"a)Sueldos,salariosyasimilados",-95399,-103507,-65742
3,b) Cargas sociales,-17809,-16095,-15194
4,c)Provisiones,n.d.,n.d.,-152
5,7.Otros gastos de explotacion,-294670,-269381,-214386
6,"a)Perdidas,deterioroyvariaciondeprovisionespor...",n.d.,n.d.,n.d.
7,b)Otrosgastosdegestioncorriente,n.d.,n.d.,n.d.
8,c)Gastosporemisi6ndegasesdeefectoinvemadero,n.d.,n.d.,n.d.
9,8.Amortizacion del inmovilizado,-16360,-17294,-14341
10,9.Imputaci6ndesubvencionesdeinmovilizadonofina...,n.d.,106,4
11,10.Excesos deprovisiones,n.d.,n.d.,n.d.
12,11.Deterioroyresultadoporenajenacionesdelinmov...,236604,-7560,-119948
13,a)Deterioroyperdidas,-9881,-7560,-119946
14,b)Resultadosporenajenacionesyotras,246485,n.d.,-2
15,12.Resultadoporlaperdida decontrol departicipa...,n.d.,n.d.,n.d.
16,a)Resultadoporlaperdida decontrol deuna depend...,n.d.,n.d.,n.d.
17,b)Resultadoatribuidoalaparticipacionretenida,n.d.,n.d.,n.d.
18,13.Diferencianegativaencombinacionesdenegocios,n.d.,n.d.,n.d.
19,14. Otros resultados,-172,-396,n.d.
20,A1)Resultado de explotaci6n(1+2+3+4+5+6+7+8+9+...,518904,205348,58938
21,15.Ingresosfinancieros,10140,10219,8905
22,a)Departicipacioneseninstrumentosdepatrimonio,2060,n.d.,n.d.

── Tabla 7 ──

,C0,C1,C2,C3
0,0,1,2,3
1,13.Diferencianegativaencombinacionesdenegocios,n.d.,n.d.,n.d.
2,14.Otros resultados,-172,-396,n.d.
3,A1)Resultado de explotaci6n (1 + 2+ 3+ 4+5 + 6...,518904,205348,58938
4,15. Ingresos financieros,10140,10219,8905
5,a)Departicipacioneseninstrumentosdepatrimonio,2060,n.d.,n.d.
6,b)Devaloresnegociablesyotrosinstrumentosfinanc...,8080,10219,8905
7,"c)Imputacionde subvenciones,donacionesylegados...",n.d.,n.d.,n.d.
8,16.Gastosfinancieros,-605691,-537309,-401985
9,17.Variaciondevalorrazonableeninstrumentosfina...,21596,2141,16689
10,a)Valorrazonableconcambiosenperdidasyganancias,21596,2141,16689
11,b)Transferenciasdeajustesdevalorrazonableconca...,n.d.,n.d.,n.d.
12,18.Diferenciasdecambio,-20712,671,9219
13,a)Imputacionalresultadodelejerciciodeladiferen...,n.d.,n.d.,n.d.
14,b)Otrasdiferenciasdecambio,n.d.,n.d.,n.d.
15,19.Deterioroyresultadopor enajenaciones deinst...,n.d.,n.d.,n.d.
16,a)Deteriorosyperdidas,n.d.,n.d.,n.d.
17,b)Resultadosporenajenacionesyotras,n.d.,n.d.,n.d.
18,20.Otrosingresosy gastos de caracterfinanciero,308,620,368
19,a) Incorporaci6n al activode gastosfinancieros,308,620,368
20,b)Ingresosfinancierosderivadosdeconveniosdeacr...,n.d.,n.d.,n.d.
21,c)Restodeingresosygastos,n.d.,n.d.,n.d.
22,A2)Resultadofinanciero(15+16+17+18+19+20),-594359,-523658,-366804

── Tabla 8 ──

,C0,C1,C2,C3
0,b)Resultadosporenajenacionesy otras,n.d. n.d.,,n.d.
1,20.Otrosingresosygastosdecaracterfinanciero,308,620,368
2,a)Incorporacionalactivodegastosfinancieros,308,620,368
3,b)Ingresosfinancierosderivadosdeconveniosdeacr...,n.d.,n.d.,n.d.
4,c)Resto deingresosygastos,n.d.,n.d.,n.d.
5,A2）Resultadofinanciero（15+16+17+18+19+20),-594359,-523658,-366804
6,21.Participacionenbeneficios(perdidas)desocied...,n.d.,n.d.,n.d.
7,22.Deterioroyresultadosporenajenacionesdeparti...,n.d.,n.d.,n.d.
8,23.Diferencianegativadeconsolidaciondesociedad...,n.d.,n.d.,n.d.
9,A3)Resultadoantesdeimpuestos(A1+A2+21+22+23),-75455,-318310,-307866
10,24.Impuestossobrebeneficios,-7683,71575,41570
11,A4)Resultadodelejercicioprocedentedeoperacione...,-83138,-246735,-266296
12,B)Operacionesinterrumpidas,,,
13,25.Resultadodelejercicioprocedentedeoperacione...,n.d.,n.d.,n.d.
14,A5)Resultado delejercicio(A4+25),-83138,-246735,-266296
15,Resultadoatribuidoalasociedaddominante,n.d.,n.d.,n.d.
16,Resultadoatribuidoasociosextemos,n.d.,n.d.,n.d.

## Celda 5 — Serialización del primer trozo para diagnóstico

Genera el texto serializado `fila=i, col=Cj: valor` del primer trozo (el que contiene la cabecera con fechas y metadatos). Se imprime para verificar que la estructura es legible antes de enviársela al LLM de layout.

El primer trozo es el más informativo para la detección de layout porque contiene la cabecera completa; los trozos siguientes tienen la misma estructura de columnas pero sin ella.

In [8]:
#Este es el mapeo que se le envia al llm para que detecte el layout osea vea en que columnas estan los valores o las partidas por si cambiara o algo

df = dfs_trozos[0]

lineas = []
for row_idx, row in df.head(15).iterrows():
    for col_name, val in row.items():
        if pd.notna(val) and str(val).strip() not in ("", "nan"):
            lineas.append(f"fila={row_idx}, col={col_name}: {val}")

mapa = "\n".join(lineas)
print(mapa)

fila=0, col=C1: GRIFOLS SA
fila=1, col=C0: Balance/Estadoderesultados
fila=2, col=C0: CuentasNoConsolidadas
fila=2, col=C1: 31/12/2024
fila=2, col=C4: 31/12/2022
fila=3, col=C1: mil EUR
fila=3, col=C4: mil EUR
fila=4, col=C3: 12meses
fila=5, col=C1: Aprobado
fila=5, col=C2: Aprobado
fila=5, col=C3: Aprobado
fila=6, col=C1: NormalPGC2007
fila=6, col=C2: Normal PGC 2007
fila=6, col=C3: NormalPGC2007
fila=7, col=C0: Activo
fila=8, col=C0: A)Activonocorriente
fila=8, col=C1: 12497590
fila=8, col=C2: 11416223
fila=8, col=C3: 12647002
fila=9, col=C0: IInmovilizadointangible
fila=9, col=C1: 23959
fila=9, col=C2: 19941
fila=9, col=C3: 23213
fila=10, col=C0: 1.Fondodecomerciodeconsolidacion
fila=10, col=C1: n.d.
fila=10, col=C2: n.d.
fila=10, col=C3: n.d.
fila=11, col=C0: 2. Investigaci6n
fila=11, col=C1: n.d.
fila=11, col=C2: n.d.
fila=11, col=C3: n.d.
fila=12, col=C0: 3.Propiedad intelectual
fila=12, col=C1: n.d.
fila=12, col=C2: n.d.
fila=12, col=C3: n.d.
fila=13, col=C0: 5.Otro inmovilizadointangible
fila=13, col=C1: n.d.
fila=13, col=C2: n.d.
fila=13, col=C3: n.d.
fila=14, col=C0: IInmovilizadomaterial
fila=14, col=C1: 31989
fila=14, col=C2: 32524
fila=14, col=C3: 35545

## Celda 6 — Paso de layout: detección por trozo (llamada individual)

Para cada trozo se serializa su contenido y se envía al LLM con un prompt que incluye las `fechas_canonicas` ya conocidas. El modelo devuelve un JSON con:
- `columna_partidas`: columna de Docling donde están los nombres de las partidas.
- `columnas_valores`: lista de columnas con valores numéricos, en el mismo orden que las fechas.
- `unidades`: unidad monetaria detectada.

**Rotación de clientes Groq:** se usan 3 clientes con distintas API keys rotando en round-robin (`clients[i % len(clients)]`). Esto es necesario porque el plan gratuito de Groq limita a 30 RPM por key, y con 8 trozos se superaría ese límite en una sola ejecución.

Los layouts de todos los trozos quedan almacenados en el diccionario `layouts` indexado por posición de trozo.

In [9]:
import os
from dotenv import load_dotenv
import openai
import json

load_dotenv()

GROQ_BASE_URL = "https://api.groq.com/openai/v1"

clients = [
    openai.OpenAI(api_key=os.getenv("GROQ_API_KEY_1",   ""), base_url=GROQ_BASE_URL),
    openai.OpenAI(api_key=os.getenv("GROQ_API_KEY_2", ""), base_url=GROQ_BASE_URL),
    openai.OpenAI(api_key=os.getenv("GROQ_API_KEY_3", ""), base_url=GROQ_BASE_URL),
]

layouts = {}

for i, df in enumerate(dfs_trozos):
    print(f"\n{'='*50}")
    print(f"── Trozo {i+1}/{len(dfs_trozos)} ──")

    client = clients[i % len(clients)]  # rota entre los 3 clientes

    lineas = []
    for row_idx, row in df.head(15).iterrows():
        for col_name, val in row.items():
            if pd.notna(val) and str(val).strip() not in ("", "nan"):
                lineas.append(f"fila={row_idx}, col={col_name}: {val}")

    mapa = "\n".join(lineas)

    prompt = f"""Tienes un fragmento de un balance financiero extraído con OCR, mapeado celda a celda.
Cada línea indica exactamente en qué fila y columna está cada valor no vacío.

{mapa}

IMPORTANTE: Las fechas de este balance son exactamente estas en orden: {fechas_canonicas}

Analiza la estructura y responde SOLO en JSON sin markdown ni backticks:

{{
  "unidades": "mil EUR / EUR / desconocido",
  "columna_partidas": "columna exacta con los nombres de las partidas",
  "columnas_valores": ["columnas con valores numéricos"],
  "razonamiento": "breve explicación",
  "ejemplo": {{
    "partida": "nombre de partida de ejemplo",
    "valores": {{"nombre_columna": valor_numerico}}
  }}
}}

Instrucciones clave:
- Los valores numéricos son importes grandes del balance (ej: 12497590, 11416223).
- La columna de partidas contiene descripciones contables: 'Activo', 'Inmovilizado', 'Existencias', etc.
- Puede haber columnas intermedias vacías o con metadatos, ignóralas.
- Fíjate bien en qué columna aparecen los números grandes para identificar columnas_valores.
"""

    response = client.chat.completions.create(
        model=MODELO1,
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )
    raw = response.choices[0].message.content.strip().strip("```json").strip("```").strip()

    try:
        layout = json.loads(raw)
        layouts[i] = layout
        print(f"Unidades:         {layout['unidades']}")
        print(f"Columna partidas: {layout['columna_partidas']}")
        print(f"Columnas valores: {layout['columnas_valores']}")
        print(f"Ejemplo:          {layout['ejemplo']}")
    except json.JSONDecodeError:
        print(f"⚠️ No devolvió JSON limpio, revisa raw:")
        print(raw)

==================================================
── Trozo 1/8 ──
Unidades:         mil EUR / desconocido
Columna partidas: C0
Columnas valores: ['C1', 'C2', 'C3']
Ejemplo:          {'partida': 'A)Activonocorriente', 'valores': {'C1': 12497590, 'C2': 11416223, 'C3': 12647002}}

==================================================
── Trozo 2/8 ──
Unidades:         EUR
Columna partidas: C0
Columnas valores: ['C1', 'C2', 'C3']
Ejemplo:          {'partida': 'VInversionesfinancierasalargoplazo', 'valores': {'C1': 418896, 'C2': 2714, 'C3': 29199}}

==================================================
── Trozo 3/8 ──
Unidades:         EUR
Columna partidas: C0
Columnas valores: ['C1', 'C2', 'C3']
Ejemplo:          {'partida': 'A-1)Fondospropios', 'valores': {'C1': 1972243, 'C2': 2044735, 'C3': 2285248}}

==================================================
── Trozo 4/8 ──
Unidades:         mil EUR
Columna partidas: C0
Columnas valores: ['C1', 'C2', 'C3']
Ejemplo:          {'partida': 'IlI Deudas con empresas del grupo y asociadas al largo plazo', 'valores': {'C1': 4276854, 'C2': 4673555, 'C3': 6419171}}

==================================================
── Trozo 5/8 ──
Unidades:         EUR
Columna partidas: C0
Columnas valores: ['C1', 'C2', 'C3']
Ejemplo:          {'partida': '1.Importenetodelacifra denegocios', 'valores': {'C1': 701053, 'C2': 619242, 'C3': 488639}}

==================================================
── Trozo 6/8 ──
Unidades:         EUR
Columna partidas: C0
Columnas valores: ['C1', 'C2', 'C3']
Ejemplo:          {'partida': '6.Gastos de personal', 'valores': {'C1': -113208, 'C2': -119602, 'C3': -81088}}

==================================================
── Trozo 7/8 ──
Unidades:         mil EUR
Columna partidas: C0
Columnas valores: ['C1', 'C2', 'C3']
Ejemplo:          {'partida': '15. Ingresos financieros', 'valores': {'C1': 10140, 'C2': 10219, 'C3': 8905}}

==================================================
── Trozo 8/8 ──
Unidades:         EUR
Columna partidas: C0
Columnas valores: ['C1', 'C2', 'C3']
Ejemplo:          {'partida': 'A2）Resultado financiero (15+16+17+18+19+20)', 'valores': {'C1': -594359, 'C2': -523658, 'C3': -366804}}

## Construcción del DataFrame unificado

## Celda 7 — Construcción del DataFrame de conceptos y exportación a CSV

Con el layout detectado para cada trozo se recorre cada DataFrame de `dfs_trozos`, se extrae la columna de partidas y las columnas de valores, y se asocia cada valor a su fecha canónica mediante el mapeo `col_valor → fecha`. El resultado es un DataFrame largo con columnas `{partida, fecha, valor, trozo}`.

Se exporta a CSV como paso intermedio para facilitar la inspección manual y la depuración.

> **Diferencia respecto al pipeline Excel:** aquí los nombres de partidas pueden contener ruido OCR (letras pegadas, signos de puntuación intercalados, palabras concatenadas sin espacio). Esto es manejable porque el LLM de selección de partidas del siguiente paso está instruido explícitamente para tolerarlo.

In [10]:
registros = []

for i, df in enumerate(dfs_trozos):
    layout = layouts[i]
    col_partidas = layout['columna_partidas']
    cols_valores = layout['columnas_valores']

    col_a_fecha = {cv: cf for cv, cf in zip(cols_valores, fechas_canonicas)}

    for _, row in df.iterrows():
        partida = str(row.get(col_partidas, "")).strip()
        if not partida or partida in ("nan", ""):
            continue
        for col_val, fecha in col_a_fecha.items():
            if col_val not in df.columns:
                continue
            val = str(row.get(col_val, "")).strip()
            try:
                val = float(val)
            except ValueError:
                val = None
            registros.append({"partida": partida, "fecha": fecha, "valor": val, "trozo": i+1})

df_resultado = pd.DataFrame(registros)
pd.set_option('display.max_rows', None)
display(df_resultado)
pd.reset_option('display.max_rows')
df_resultado.to_csv(r"C:\Users\perdi\Desktop\tfm\TFM PYTHON\outputs\balance_final.csv", index=False)

,partida,fecha,valor,trozo
0,Balance/Estadoderesultados,31/12/2024,NaN,1
1,Balance/Estadoderesultados,31/12/2023,NaN,1
2,Balance/Estadoderesultados,31/12/2022,NaN,1
3,CuentasNoConsolidadas,31/12/2024,NaN,1
4,CuentasNoConsolidadas,31/12/2023,NaN,1
5,CuentasNoConsolidadas,31/12/2022,NaN,1
6,Activo,31/12/2024,NaN,1
7,Activo,31/12/2023,NaN,1
8,Activo,31/12/2022,NaN,1
9,A)Activonocorriente,31/12/2024,12497590.0,1
10,A)Activonocorriente,31/12/2023,11416223.0,1
11,A)Activonocorriente,31/12/2022,12647002.0,1
12,IInmovilizadointangible,31/12/2024,23959.0,1
13,IInmovilizadointangible,31/12/2023,19941.0,1
14,IInmovilizadointangible,31/12/2022,23213.0,1
15,1.Fondodecomerciodeconsolidacion,31/12/2024,NaN,1
16,1.Fondodecomerciodeconsolidacion,31/12/2023,NaN,1
17,1.Fondodecomerciodeconsolidacion,31/12/2022,NaN,1
18,2. Investigaci6n,31/12/2024,NaN,1
19,2. Investigaci6n,31/12/2023,NaN,1
20,2. Investigaci6n,31/12/2022,NaN,1
21,3.Propiedad intelectual,31/12/2024,NaN,1
22,3.Propiedad intelectual,31/12/2023,NaN,1
23,3.Propiedad intelectual,31/12/2022,NaN,1
24,5.Otro inmovilizadointangible,31/12/2024,NaN,1
25,5.Otro inmovilizadointangible,31/12/2023,NaN,1
26,5.Otro inmovilizadointangible,31/12/2022,NaN,1
27,IInmovilizadomaterial,31/12/2024,31989.0,1
28,IInmovilizadomaterial,31/12/2023,32524.0,1
29,IInmovilizadomaterial,31/12/2022,35545.0,1
30,1.Terrenosy construcciones,31/12/2024,11064.0,1
31,1.Terrenosy construcciones,31/12/2023,11151.0,1
32,1.Terrenosy construcciones,31/12/2022,11239.0,1
33,2.Instalacionestecnicasy otro inmovilizado mat...,31/12/2024,16685.0,1
34,2.Instalacionestecnicasy otro inmovilizado mat...,31/12/2023,14926.0,1
35,2.Instalacionestecnicasy otro inmovilizado mat...,31/12/2022,18207.0,1
36,3.Inmovilizado en cursoy anticipos,31/12/2024,4240.0,1
37,3.Inmovilizado en cursoy anticipos,31/12/2023,6447.0,1
38,3.Inmovilizado en cursoy anticipos,31/12/2022,6099.0,1
39,I Inversionesinmobiliarias,31/12/2024,102332.0,1
40,I Inversionesinmobiliarias,31/12/2023,108977.0,1
41,I Inversionesinmobiliarias,31/12/2022,80458.0,1
42,IVInversionesenempresasdelgrupoyasociadasalarg...,31/12/2024,11838151.0,1
43,IVInversionesenempresasdelgrupoyasociadasalarg...,31/12/2023,11202474.0,1
44,IVInversionesenempresasdelgrupoyasociadasalarg...,31/12/2022,12469437.0,1
45,1.Participacionespuestas en equivalencia,31/12/2024,NaN,1
46,1.Participacionespuestas en equivalencia,31/12/2023,NaN,1
47,1.Participacionespuestas en equivalencia,31/12/2022,NaN,1
48,2.Creditosasociedadespuestasenequivalencia,31/12/2024,NaN,1
49,2.Creditosasociedadespuestasenequivalencia,31/12/2023,NaN,1
50,2.Creditosasociedadespuestasenequivalencia,31/12/2022,NaN,1
51,3.Otrosactivosfinancieros,31/12/2024,NaN,1
52,3.Otrosactivosfinancieros,31/12/2023,NaN,1
53,3.Otrosactivosfinancieros,31/12/2022,NaN,1
54,4. Otras inversiones,31/12/2024,NaN,1
55,4. Otras inversiones,31/12/2023,NaN,1
56,4. Otras inversiones,31/12/2022,NaN,1
57,VInversionesfinancierasalargoplazo,31/12/2024,418896.0,1
58,VInversionesfinancierasalargoplazo,31/12/2023,2714.0,1
59,VInversionesfinancierasalargoplazo,31/12/2022,29199.0,1
60,VIActivosporimpuestodiferido,31/12/2024,82263.0,1
61,VIActivosporimpuestodiferido,31/12/2023,49593.0,1
62,VIActivosporimpuestodiferido,31/12/2022,9150.0,1
63,VllDeudascomercialesnocorrientes,31/12/2024,NaN,1
64,VllDeudascomercialesnocorrientes,31/12/2023,NaN,1
65,VllDeudascomercialesnocorrientes,31/12/2022,NaN,1
66,B)Activo corriente,31/12/2024,342446.0,1
67,B)Activo corriente,31/12/2023,1544994.0,1
68,B)Activo corriente,31/12/2022,246099.0,1
69,IActivosnocorrientesmantenidosparalaventa,31/12/2024,NaN,1
70,IActivosnocorrientesmantenidosparalaventa,31/12/2023,1360089.0,1
71,IActivosnocorrientesmantenidosparalaventa,31/12/2022,NaN,1
72,IlExistencias,31/12/2024,13342.0,1
73,IlExistencias,31/12/2023,12333.0,1
74,IlExistencias,31/12/2022,11439.0,1
75,IlIDeudorescomercialesyotrascuentasacobrar,31/12/2024,79885.0,1
76,IlIDeudorescomercialesyotrascuentasacobrar,31/12/2023,79873.0,1
77,IlIDeudorescomercialesyotrascuentasacobrar,31/12/2022,72869.0,1
78,2.Creditosasociedadespuestasenequivalencia,31/12/2024,NaN,2
79,2.Creditosasociedadespuestasenequivalencia,31/12/2023,NaN,2
80,2.Creditosasociedadespuestasenequivalencia,31/12/2022,NaN,2
81,3.Otros activos financieros,31/12/2024,NaN,2
82,3.Otros activos financieros,31/12/2023,NaN,2
83,3.Otros activos financieros,31/12/2022,NaN,2
84,4.Otras inversiones,31/12/2024,NaN,2
85,4.Otras inversiones,31/12/2023,NaN,2
86,4.Otras inversiones,31/12/2022,NaN,2
87,VInversionesfinancierasalargoplazo,31/12/2024,418896.0,2
88,VInversionesfinancierasalargoplazo,31/12/2023,2714.0,2
89,VInversionesfinancierasalargoplazo,31/12/2022,29199.0,2
90,VIActivosporimpuestodiferido,31/12/2024,82263.0,2
91,VIActivosporimpuestodiferido,31/12/2023,49593.0,2
92,VIActivosporimpuestodiferido,31/12/2022,9150.0,2
93,VllDeudascomercialesnocorrientes,31/12/2024,NaN,2
94,VllDeudascomercialesnocorrientes,31/12/2023,NaN,2
95,VllDeudascomercialesnocorrientes,31/12/2022,NaN,2
96,B)Activo corriente,31/12/2024,342446.0,2
97,B)Activo corriente,31/12/2023,1544994.0,2
98,B)Activo corriente,31/12/2022,246099.0,2
99,IActivosnocorrientesmantenidosparalaventa,31/12/2024,NaN,2
100,IActivosnocorrientesmantenidosparalaventa,31/12/2023,1360089.0,2
101,IActivosnocorrientesmantenidosparalaventa,31/12/2022,NaN,2
102,IIExistencias,31/12/2024,13342.0,2
103,IIExistencias,31/12/2023,12333.0,2
104,IIExistencias,31/12/2022,11439.0,2
105,IllDeudorescomercialesyotrascuentasacobrar,31/12/2024,79885.0,2
106,IllDeudorescomercialesyotrascuentasacobrar,31/12/2023,79873.0,2
107,IllDeudorescomercialesyotrascuentasacobrar,31/12/2022,72869.0,2
108,1.Clientesporventasyprestacionesdeservicios,31/12/2024,1496.0,2
109,1.Clientesporventasyprestacionesdeservicios,31/12/2023,581.0,2
110,1.Clientesporventasyprestacionesdeservicios,31/12/2022,833.0,2
111,a)Clientesporventasyprestacionesdeserviciosa l...,31/12/2024,NaN,2
112,a)Clientesporventasyprestacionesdeserviciosa l...,31/12/2023,NaN,2
113,a)Clientesporventasyprestacionesdeserviciosa l...,31/12/2022,NaN,2
114,b) Clientes por ventasy prestaciones deservici...,31/12/2024,1496.0,2
115,b) Clientes por ventasy prestaciones deservici...,31/12/2023,581.0,2
116,b) Clientes por ventasy prestaciones deservici...,31/12/2022,833.0,2
117,2.Sociedadespuestas enequivalencia,31/12/2024,NaN,2
118,2.Sociedadespuestas enequivalencia,31/12/2023,NaN,2
119,2.Sociedadespuestas enequivalencia,31/12/2022,NaN,2
120,3.Activos porimpuesto corriente,31/12/2024,16453.0,2
121,3.Activos porimpuesto corriente,31/12/2023,12303.0,2
122,3.Activos porimpuesto corriente,31/12/2022,2486.0,2
123,4.Otrosdeudores,31/12/2024,NaN,2
124,4.Otrosdeudores,31/12/2023,NaN,2
125,4.Otrosdeudores,31/12/2022,NaN,2
126,IVInversionesenempresasdelgrupoyasociadasacort...,31/12/2024,228981.0,2
127,IVInversionesenempresasdelgrupoyasociadasacort...,31/12/2023,47884.0,2
128,IVInversionesenempresasdelgrupoyasociadasacort...,31/12/2022,123033.0,2
129,1.Creditos a empresaspuestos enequivalencia,31/12/2024,NaN,2
130,1.Creditos a empresaspuestos enequivalencia,31/12/2023,NaN,2
131,1.Creditos a empresaspuestos enequivalencia,31/12/2022,NaN,2
132,2.Otros activos financieros,31/12/2024,NaN,2
133,2.Otros activos financieros,31/12/2023,NaN,2
134,2.Otros activos financieros,31/12/2022,NaN,2
135,3.Otras inversiones,31/12/2024,NaN,2
136,3.Otras inversiones,31/12/2023,NaN,2
137,3.Otras inversiones,31/12/2022,NaN,2
138,VInversionesfinancierasa cortoplazo,31/12/2024,2752.0,2
139,VInversionesfinancierasa cortoplazo,31/12/2023,20917.0,2
140,VInversionesfinancierasa cortoplazo,31/12/2022,11569.0,2
141,VIPeriodificacionesacortoplazo,31/12/2024,16203.0,2
142,VIPeriodificacionesacortoplazo,31/12/2023,11031.0,2
143,VIPeriodificacionesacortoplazo,31/12/2022,13511.0,2
144,VllEfectivoyotrosactivoslfquidosequivalentes,31/12/2024,1283.0,2
145,VllEfectivoyotrosactivoslfquidosequivalentes,31/12/2023,12867.0,2
146,VllEfectivoyotrosactivoslfquidosequivalentes,31/12/2022,13678.0,2
147,Total activo (A + B),31/12/2024,12840036.0,2
148,Total activo (A + B),31/12/2023,12961217.0,2
149,Total activo (A + B),31/12/2022,12893101.0,2
150,Pasivo,31/12/2024,NaN,2
151,Pasivo,31/12/2023,NaN,2
152,Pasivo,31/12/2022,NaN,2
153,A)Patrimonioneto,31/12/2024,1953852.0,2
154,A)Patrimonioneto,31/12/2023,2101487.0,2
155,A)Patrimonioneto,31/12/2022,2343125.0,2
156,A-1) Fondos propios,31/12/2024,1972243.0,2
157,A-1) Fondos propios,31/12/2023,2044735.0,2
158,A-1) Fondos propios,31/12/2022,2285248.0,2
159,ICapital,31/12/2024,119604.0,2
160,ICapital,31/12/2023,119604.0,2
161,ICapital,31/12/2022,119604.0,2
162,1.Capital escriturado,31/12/2024,119604.0,2
163,1.Capital escriturado,31/12/2023,119604.0,2
164,1.Capital escriturado,31/12/2022,119604.0,2
165,2. (Capital no exigido),31/12/2024,NaN,2
166,2. (Capital no exigido),31/12/2023,NaN,2
167,2. (Capital no exigido),31/12/2022,NaN,2
168,IlPrima de emision,31/12/2024,910728.0,2
169,IlPrima de emision,31/12/2023,910728.0,2
170,IlPrima de emision,31/12/2022,910728.0,2
171,1.Reserva derevalorizaci6n,31/12/2024,NaN,2
172,1.Reserva derevalorizaci6n,31/12/2023,NaN,2
173,1.Reserva derevalorizaci6n,31/12/2022,NaN,2
174,2.Reserva de capitalizacion,31/12/2024,NaN,2
175,2.Reserva de capitalizacion,31/12/2023,NaN,2
176,2.Reserva de capitalizacion,31/12/2022,NaN,2
177,3.Otras reservas,31/12/2024,NaN,2
178,3.Otras reservas,31/12/2023,NaN,2
179,3.Otras reservas,31/12/2022,NaN,2
180,I Reservasyresultadosdeejerciciosanteriores,31/12/2024,NaN,2
181,I Reservasyresultadosdeejerciciosanteriores,31/12/2023,NaN,2
182,I Reservasyresultadosdeejerciciosanteriores,31/12/2022,NaN,2
183,IV (Acciones y participaciones en patrimonio p...,31/12/2024,-134448.0,2
184,IV (Acciones y participaciones en patrimonio p...,31/12/2023,-152748.0,2
185,IV (Acciones y participaciones en patrimonio p...,31/12/2022,-162220.0,2
186,VOtras aportacionesdesocios,31/12/2024,NaN,2
187,VOtras aportacionesdesocios,31/12/2023,NaN,2
188,VOtras aportacionesdesocios,31/12/2022,NaN,2
189,nante,31/12/2024,-83138.0,2
190,nante,31/12/2023,246735.0,2
191,nante,31/12/2022,266296.0,2
192,A-1)Fondospropios,31/12/2024,1972243.0,3
193,A-1)Fondospropios,31/12/2023,2044735.0,3
194,A-1)Fondospropios,31/12/2022,2285248.0,3
195,ICapital,31/12/2024,119604.0,3
196,ICapital,31/12/2023,119604.0,3
197,ICapital,31/12/2022,119604.0,3
198,1.Capital escriturado,31/12/2024,119604.0,3
199,1.Capital escriturado,31/12/2023,119604.0,3
200,1.Capital escriturado,31/12/2022,119604.0,3
201,2. (Capital no exigido),31/12/2024,NaN,3
202,2. (Capital no exigido),31/12/2023,NaN,3
203,2. (Capital no exigido),31/12/2022,NaN,3
204,IlPrima de emision,31/12/2024,910728.0,3
205,IlPrima de emision,31/12/2023,910728.0,3
206,IlPrima de emision,31/12/2022,910728.0,3
207,1.Reserva derevalorizacion,31/12/2024,NaN,3
208,1.Reserva derevalorizacion,31/12/2023,NaN,3
209,1.Reserva derevalorizacion,31/12/2022,NaN,3
210,2.Reserva de capitalizacion,31/12/2024,NaN,3
211,2.Reserva de capitalizacion,31/12/2023,NaN,3
212,2.Reserva de capitalizacion,31/12/2022,NaN,3
213,3.Otrasreservas,31/12/2024,NaN,3
214,3.Otrasreservas,31/12/2023,NaN,3
215,3.Otrasreservas,31/12/2022,NaN,3
216,Il Reservasyresultadosdeejerciciosanteriores,31/12/2024,NaN,3
217,Il Reservasyresultadosdeejerciciosanteriores,31/12/2023,NaN,3
218,Il Reservasyresultadosdeejerciciosanteriores,31/12/2022,NaN,3
219,IV(Accionesyparticipacionesenpatrimoniopropias...,31/12/2024,-134448.0,3
220,IV(Accionesyparticipacionesenpatrimoniopropias...,31/12/2023,-152748.0,3
221,IV(Accionesyparticipacionesenpatrimoniopropias...,31/12/2022,-162220.0,3
222,V Otrasaportacionesdesocios,31/12/2024,NaN,3
223,V Otrasaportacionesdesocios,31/12/2023,NaN,3
224,V Otrasaportacionesdesocios,31/12/2022,NaN,3
225,VIResultadodelejercicioatribuidoalasociedaddom...,31/12/2024,-83138.0,3
226,VIResultadodelejercicioatribuidoalasociedaddom...,31/12/2023,-246735.0,3
227,VIResultadodelejercicioatribuidoalasociedaddom...,31/12/2022,-266296.0,3
228,VllDividendoacuenta),31/12/2024,NaN,3
229,VllDividendoacuenta),31/12/2023,NaN,3
230,VllDividendoacuenta),31/12/2022,NaN,3
231,VIllOtrosinstrumentos depatrimonioneto,31/12/2024,6647.0,3
232,VIllOtrosinstrumentos depatrimonioneto,31/12/2023,8282.0,3
233,VIllOtrosinstrumentos depatrimonioneto,31/12/2022,7303.0,3
234,A-2)Ajustesporcambiosdevalor,31/12/2024,-18391.0,3
235,A-2)Ajustesporcambiosdevalor,31/12/2023,56752.0,3
236,A-2)Ajustesporcambiosdevalor,31/12/2022,57798.0,3
237,"IActivosnocorrientesypasivosvinculados,manteni...",31/12/2024,NaN,3
238,"IActivosnocorrientesypasivosvinculados,manteni...",31/12/2023,NaN,3
239,"IActivosnocorrientesypasivosvinculados,manteni...",31/12/2022,NaN,3
240,IDiferenciadeconversi6n,31/12/2024,NaN,3
241,IDiferenciadeconversi6n,31/12/2023,NaN,3
242,IDiferenciadeconversi6n,31/12/2022,NaN,3
243,IlOtros,31/12/2024,NaN,3
244,IlOtros,31/12/2023,NaN,3
245,IlOtros,31/12/2022,NaN,3
246,"A-3)Subvenciones,donacionesylegadosrecibidos",31/12/2024,NaN,3
247,"A-3)Subvenciones,donacionesylegadosrecibidos",31/12/2023,NaN,3
248,"A-3)Subvenciones,donacionesylegadosrecibidos",31/12/2022,79.0,3
249,A-4)Sociosextemos,31/12/2024,NaN,3
250,A-4)Sociosextemos,31/12/2023,NaN,3
251,A-4)Sociosextemos,31/12/2022,NaN,3
252,B)Pasivonocorriente,31/12/2024,10572251.0,3
253,B)Pasivonocorriente,31/12/2023,10561625.0,3
254,B)Pasivonocorriente,31/12/2022,10323483.0,3
255,IProvisionesalargoplazo,31/12/2024,3217.0,3
256,IProvisionesalargoplazo,31/12/2023,3838.0,3
257,IProvisionesalargoplazo,31/12/2022,NaN,3
258,IIDeudas a largoplazo,31/12/2024,6288936.0,3
259,IIDeudas a largoplazo,31/12/2023,5879325.0,3
260,IIDeudas a largoplazo,31/12/2022,3901732.0,3
261,1.obligacionesy otrosvaloresnegociables,31/12/2024,5387413.0,3
262,1.obligacionesy otrosvaloresnegociables,31/12/2023,4571059.0,3
263,1.obligacionesy otrosvaloresnegociables,31/12/2022,2556641.0,3
264,2.Deudasconentidadesdecredito,31/12/2024,901345.0,3
265,2.Deudasconentidadesdecredito,31/12/2023,1308026.0,3
266,2.Deudasconentidadesdecredito,31/12/2022,1340473.0,3
267,3.Acreedoresporarrendamientofinanciero,31/12/2024,21.0,3
268,3.Acreedoresporarrendamientofinanciero,31/12/2023,27.0,3
269,3.Acreedoresporarrendamientofinanciero,31/12/2022,52.0,3
270,4. Otros pasivos financieros,31/12/2024,NaN,3
271,4. Otros pasivos financieros,31/12/2023,NaN,3
272,4. Otros pasivos financieros,31/12/2022,NaN,3
273,IIDeudasconempresasdelgrupoyasociadasalargoplazo,31/12/2024,4276854.0,3
274,IIDeudasconempresasdelgrupoyasociadasalargoplazo,31/12/2023,4673555.0,3
275,IIDeudasconempresasdelgrupoyasociadasalargoplazo,31/12/2022,6419171.0,3
276,1.Deudasconsociedadespuestaenequivalencia,31/12/2024,NaN,3
277,1.Deudasconsociedadespuestaenequivalencia,31/12/2023,NaN,3
278,1.Deudasconsociedadespuestaenequivalencia,31/12/2022,NaN,3
279,2. Otras deudas,31/12/2024,NaN,3
280,2. Otras deudas,31/12/2023,NaN,3
281,2. Otras deudas,31/12/2022,NaN,3
282,IVPasivos porimpuesto diferido,31/12/2024,3244.0,3
283,IVPasivos porimpuesto diferido,31/12/2023,4907.0,3
284,IVPasivos porimpuesto diferido,31/12/2022,2580.0,3
285,VPeriodificacionesa largoplazo,31/12/2024,NaN,3
286,VPeriodificacionesa largoplazo,31/12/2023,NaN,3
287,VPeriodificacionesa largoplazo,31/12/2022,NaN,3
288,VIAcreedorescomercialesnocorientes,31/12/2024,NaN,3
289,VIAcreedorescomercialesnocorientes,31/12/2023,NaN,3
290,VIAcreedorescomercialesnocorientes,31/12/2022,NaN,3
291,VllDeuda concaracteristicas especialesa largop...,31/12/2024,NaN,3
292,VllDeuda concaracteristicas especialesa largop...,31/12/2023,NaN,3
293,VllDeuda concaracteristicas especialesa largop...,31/12/2022,NaN,3
294,C)Pasivo corriente,31/12/2024,313933.0,3
295,C)Pasivo corriente,31/12/2023,298105.0,3
296,C)Pasivo corriente,31/12/2022,226493.0,3
297,3.Acreedoresporarrendamientofinanciero,31/12/2024,NaN,4
298,3.Acreedoresporarrendamientofinanciero,31/12/2023,NaN,4
299,3.Acreedoresporarrendamientofinanciero,31/12/2022,52.0,4
300,4. Otros pasivos financieros,31/12/2024,NaN,4
301,4. Otros pasivos financieros,31/12/2023,NaN,4
302,4. Otros pasivos financieros,31/12/2022,NaN,4
303,IlI Deudasconempresasdel grupoyasociadas alarg...,31/12/2024,4276854.0,4
304,IlI Deudasconempresasdel grupoyasociadas alarg...,31/12/2023,4673555.0,4
305,IlI Deudasconempresasdel grupoyasociadas alarg...,31/12/2022,6419171.0,4
306,1.Deudasconsociedadespuestaenequivalencia,31/12/2024,NaN,4
307,1.Deudasconsociedadespuestaenequivalencia,31/12/2023,NaN,4
308,1.Deudasconsociedadespuestaenequivalencia,31/12/2022,NaN,4
309,2.Otras deudas,31/12/2024,NaN,4
310,2.Otras deudas,31/12/2023,NaN,4
311,2.Otras deudas,31/12/2022,NaN,4
312,IVPasivosporimpuestodiferido,31/12/2024,3244.0,4
313,IVPasivosporimpuestodiferido,31/12/2023,4907.0,4
314,IVPasivosporimpuestodiferido,31/12/2022,2580.0,4
315,VPeriodificacionesalargoplazo,31/12/2024,NaN,4
316,VPeriodificacionesalargoplazo,31/12/2023,NaN,4
317,VPeriodificacionesalargoplazo,31/12/2022,NaN,4
318,VIAcreedorescomercialesnocorrientes,31/12/2024,NaN,4
319,VIAcreedorescomercialesnocorrientes,31/12/2023,NaN,4
320,VIAcreedorescomercialesnocorrientes,31/12/2022,NaN,4
321,VllDeudaconcaracteristicasespecialesalargoplazo,31/12/2024,NaN,4
322,VllDeudaconcaracteristicasespecialesalargoplazo,31/12/2023,NaN,4
323,VllDeudaconcaracteristicasespecialesalargoplazo,31/12/2022,NaN,4
324,C)Pasivo corriente,31/12/2024,313933.0,4
325,C)Pasivo corriente,31/12/2023,298105.0,4
326,C)Pasivo corriente,31/12/2022,226493.0,4
327,IPasivosvinculadosconactivosnocorrientesmanten...,31/12/2024,NaN,4
328,IPasivosvinculadosconactivosnocorrientesmanten...,31/12/2023,NaN,4
329,IPasivosvinculadosconactivosnocorrientesmanten...,31/12/2022,NaN,4
330,IIProvisiones a cortoplazo,31/12/2024,79947.0,4
331,IIProvisiones a cortoplazo,31/12/2023,14000.0,4
332,IIProvisiones a cortoplazo,31/12/2022,7000.0,4
333,1.Provisionesporderechosdeemisiondegasesdeefec...,31/12/2024,NaN,4
334,1.Provisionesporderechosdeemisiondegasesdeefec...,31/12/2023,NaN,4
335,1.Provisionesporderechosdeemisiondegasesdeefec...,31/12/2022,NaN,4
336,2. Otras provisiones,31/12/2024,79947.0,4
337,2. Otras provisiones,31/12/2023,14000.0,4
338,2. Otras provisiones,31/12/2022,7000.0,4
339,IIDeudasacortoplazo,31/12/2024,68347.0,4
340,IIDeudasacortoplazo,31/12/2023,106970.0,4
341,IIDeudasacortoplazo,31/12/2022,74786.0,4
342,1. Obligaciones y otros valores negociables,31/12/2024,38907.0,4
343,1. Obligaciones y otros valores negociables,31/12/2023,30170.0,4
344,1. Obligaciones y otros valores negociables,31/12/2022,12554.0,4
345,2.Deudas conentidades decredito,31/12/2024,29383.0,4
346,2.Deudas conentidades decredito,31/12/2023,68542.0,4
347,2.Deudas conentidades decredito,31/12/2022,60899.0,4
348,3.Acreedoresporarrendamientofinanciero,31/12/2024,NaN,4
349,3.Acreedoresporarrendamientofinanciero,31/12/2023,25.0,4
350,3.Acreedoresporarrendamientofinanciero,31/12/2022,391.0,4
351,4. Otros pasivos financieros,31/12/2024,NaN,4
352,4. Otros pasivos financieros,31/12/2023,NaN,4
353,4. Otros pasivos financieros,31/12/2022,NaN,4
354,IVDeudasconempresasdel grupoyasociadasa cortop...,31/12/2024,62437.0,4
355,IVDeudasconempresasdel grupoyasociadasa cortop...,31/12/2023,64699.0,4
356,IVDeudasconempresasdel grupoyasociadasa cortop...,31/12/2022,61720.0,4
357,1.Deudas consociedadespuesta en equivalencia,31/12/2024,NaN,4
358,1.Deudas consociedadespuesta en equivalencia,31/12/2023,NaN,4
359,1.Deudas consociedadespuesta en equivalencia,31/12/2022,NaN,4
360,2.Otrasdeudas,31/12/2024,NaN,4
361,2.Otrasdeudas,31/12/2023,NaN,4
362,2.Otrasdeudas,31/12/2022,NaN,4
363,VAcreedorescomercialesyotrascuentasapagar,31/12/2024,94624.0,4
364,VAcreedorescomercialesyotrascuentasapagar,31/12/2023,112436.0,4
365,VAcreedorescomercialesyotrascuentasapagar,31/12/2022,82987.0,4
366,1.Proveedores,31/12/2024,65750.0,4
367,1.Proveedores,31/12/2023,69365.0,4
368,1.Proveedores,31/12/2022,58812.0,4
369,a)Proveedores a largo plazo,31/12/2024,NaN,4
370,a)Proveedores a largo plazo,31/12/2023,NaN,4
371,a)Proveedores a largo plazo,31/12/2022,NaN,4
372,b)Proveedores a cortoplazo,31/12/2024,65750.0,4

## Celda 8 — Selección de las 22 partidas mediante LLM con índice posicional

Mismo enfoque que en el pipeline Excel pero con las instrucciones especiales adaptadas al ruido OCR típico de imágenes:
- Las partidas pueden estar truncadas o con palabras pegadas (`"ACTIVOSCORRIENTES"`, `"Deudorescomercialesyotrascuentasacobrar"`).
- El prompt menciona explícitamente variantes OCR esperadas para las partidas más conflictivas.
- Para `deuda_credito_lp` y `deuda_credito_cp` el razonamiento por anclas LP/CP sigue siendo la clave para resolver la ambigüedad de partidas con nombre idéntico en secciones distintas del balance.

El output es un JSON `{alias: {idx, partida}}` con los 22 mapeos sobre la lista de partidas únicas del DataFrame.

In [11]:
# ── PASO 3: LLM selecciona partidas directamente ──────────────────────────
partidas_unicas = df_resultado['partida'].drop_duplicates().tolist()
partidas_formateadas = "\n".join(f"idx={i}: {p}" for i, p in enumerate(partidas_unicas))

prompt_mapeo = f"""Eres un experto en contabilidad española (PGC 2007).
Tienes la lista completa de partidas de un balance financiero extraído con OCR,
en orden exacto tal como aparecen (los textos pueden estar truncados o con ruido OCR).

PARTIDAS DISPONIBLES:
{partidas_formateadas}

INSTRUCCIONES GENERALES:
- Devuelve el idx y el texto EXACTAMENTE como aparecen en la lista.
- Si una partida no existe en este balance devuelve null.

INSTRUCCIONES ESPECIALES:
- 'patrimonio_neto': puede aparecer como "Patrimonio neto", con letras/números antes o después, o todo junto.
- 'fondos_propios': si no hay partida específica usa patrimonio_neto para los dos; si hay fondos propios devuelve la partida específica.
- 'pasivo_no_corriente': puede aparecer como 'B) Pasivo no corriente'.
- 'pasivo_corriente': puede aparecer como 'C) Pasivo corriente'.
- 'total_activo': puede aparecer como 'Total activo (A + B)'.
- 'activo_corriente': puede aparecer como 'B) Activo corriente'.
- 'resultado_ejercicio': puede aparecer como 'A5) Resultado del ejercicio'.
- 'efectivo': puede aparecer como 'VII Efectivo y otros activos liquidos equivalentes'.
- 'deuda_credito_lp' y 'deuda_credito_cp': busca "Deudas con entidades de credito".
  Puede aparecer dos veces. Mira los índices anteriores para determinar si está más cerca
  de anclas LP ("Deudas a largo plazo", "largo plazo", "pasivo no corriente") o
  anclas CP ("Deudas a corto plazo", "corto plazo", "pasivo corriente").
  Asigna según la ancla más cercana en número de índice.

Devuelve SOLO JSON sin markdown, con este formato:
{{
  "patrimonio_neto": {{"idx": 40, "partida": "texto literal"}},
  "fondos_propios": {{"idx": 41, "partida": "texto literal"}},
  "pasivo_no_corriente": {{"idx": 61, "partida": "texto literal"}},
  "deudas_lp": {{"idx": 63, "partida": "texto literal"}},
  "deudas_cp": {{"idx": 80, "partida": "texto literal"}},
  "pasivo_corriente": {{"idx": 75, "partida": "texto literal"}},
  "total_activo": {{"idx": 46, "partida": "texto literal"}},
  "activo_corriente": {{"idx": 27, "partida": "texto literal"}},
  "existencias": {{"idx": 29, "partida": "texto literal"}},
  "deudores_comerciales": {{"idx": 31, "partida": "texto literal"}},
  "efectivo": {{"idx": 45, "partida": "texto literal"}},
  "inmovilizado_material": {{"idx": 14, "partida": "texto literal"}},
  "acreedores_comerciales": {{"idx": 88, "partida": "texto literal"}},
  "cifra_negocios": {{"idx": 100, "partida": "texto literal"}},
  "otros_ingresos_explotacion": {{"idx": 110, "partida": "texto literal"}},
  "resultado_explotacion": {{"idx": 132, "partida": "texto literal"}},
  "amortizacion": {{"idx": 121, "partida": "texto literal"}},
  "gastos_financieros": {{"idx": 137, "partida": "texto literal"}},
  "resultado_antes_impuestos": {{"idx": 155, "partida": "texto literal"}},
  "resultado_ejercicio": {{"idx": 160, "partida": "texto literal"}},
  "deuda_credito_lp": null,
  "deuda_credito_cp": {{"idx": 82, "partida": "texto literal"}}
}}
"""

response = client.chat.completions.create(
    model=MODELO2,
    messages=[{"role": "user", "content": prompt_mapeo}],
    temperature=0
)

raw = response.choices[0].message.content.strip().strip("```json").strip("```").strip()

try:
    mapeo_llm = json.loads(raw)
    print("\n── Mapeo LLM ──")
    for alias, info in mapeo_llm.items():
        if info:
            print(f"  {alias}: idx={info['idx']} → {info['partida']}")
        else:
            print(f"  {alias}: null")
except json.JSONDecodeError:
    print("⚠️ No devolvió JSON limpio")
    print(raw)

── Mapeo LLM ──
  patrimonio_neto: idx=45 → A)Patrimonioneto
  fondos_propios: idx=46 → A-1) Fondos propios
  pasivo_no_corriente: idx=73 → B)Pasivonocorriente
  deudas_lp: idx=77 → 2.Deudasconentidadesdecredito
  deudas_cp: idx=101 → 2.Deudasconentidadesdecredito
  pasivo_corriente: idx=87 → C)Pasivo corriente
  total_activo: idx=43 → Total activo (A + B)
  activo_corriente: idx=22 → B)Activo corriente
  existencias: idx=24 → IlExistencias
  deudores_comerciales: idx=25 → IlIDeudorescomercialesyotrascuentasacobrar
  efectivo: idx=42 → VllEfectivoyotrosactivoslfquidosequivalentes
  inmovilizado_material: idx=9 → IInmovilizadomaterial
  acreedores_comerciales: idx=104 → VAcreedorescomercialesyotrascuentasapagar
  cifra_negocios: idx=115 → A)Operacionescontinuadas
  otros_ingresos_explotacion: idx=125 → 5.Otrosingresosdeexplotacion
  resultado_explotacion: idx=149 → A1)Resultado de explotaci6n(1+2+3+4+5+6+7+8+9+10+11+12+13+14)
  amortizacion: idx=138 → 8.Amortizacion del inmovilizado
  gastos_financieros: idx=157 → 16.Gastosfinancieros
  resultado_antes_impuestos: idx=179 → A3)Resultadoantesdeimpuestos(A1+A2+21+22+23)
  resultado_ejercicio: idx=184 → A5)Resultado delejercicio(A4+25)
  deuda_credito_lp: idx=77 → 2.Deudasconentidadesdecredito
  deuda_credito_cp: idx=100 → 2.Deudasconentidadesdecredito

## Celda 9 — Extracción de valores por período

Con el mapeo del LLM se recupera para cada alias el valor numérico por fecha cruzando `partidas_unicas[info['idx']]` con `df_resultado`. El resultado es `valores_por_fecha`, idéntico en estructura al del pipeline Excel.

In [12]:
# ── PASO 4: extraer valores por periodo ──────────────────────────────────

valores_por_fecha = {}

for alias, info in mapeo_llm.items():
    if info is None:
        continue
    partida_real = partidas_unicas[info['idx']]
    filas = df_resultado[df_resultado['partida'] == partida_real]
    for _, row in filas.iterrows():
        fecha = row['fecha']
        valor = row['valor']
        if fecha not in valores_por_fecha:
            valores_por_fecha[fecha] = {}
        if alias not in valores_por_fecha[fecha]:
            valores_por_fecha[fecha][alias] = None if pd.isna(valor) else valor

print(pd.DataFrame(valores_por_fecha).T)

            patrimonio_neto  fondos_propios  pasivo_no_corriente  deudas_lp  \
31/12/2024        1953852.0       1972243.0           10572251.0   901345.0
31/12/2023        2101487.0       2044735.0           10561625.0  1308026.0
31/12/2022        2343125.0       2285248.0           10323483.0  1340473.0

            deudas_cp  pasivo_corriente  total_activo  activo_corriente  \
31/12/2024    62437.0          313933.0    12840036.0          342446.0
31/12/2023    64699.0          298105.0    12961217.0         1544994.0
31/12/2022    61720.0          226493.0    12893101.0          246099.0

            existencias  deudores_comerciales  ...  acreedores_comerciales  \
31/12/2024      13342.0               79885.0  ...                 94624.0
31/12/2023      12333.0               79873.0  ...                112436.0
31/12/2022      11439.0               72869.0  ...                 82987.0

            cifra_negocios  otros_ingresos_explotacion  resultado_explotacion  \
31/12/2024        701053.0                      5069.0               518904.0
31/12/2023        619242.0                      2582.0               205348.0
31/12/2022        488639.0                      1956.0                58938.0

            amortizacion  gastos_financieros  resultado_antes_impuestos  \
31/12/2024      -16360.0           -605691.0                   -75455.0
31/12/2023      -17294.0           -537309.0                  -318310.0
31/12/2022      -14341.0           -401985.0                  -307866.0

            resultado_ejercicio  deuda_credito_lp  deuda_credito_cp
31/12/2024             -83138.0          901345.0           29383.0
31/12/2023            -246735.0         1308026.0           68542.0
31/12/2022            -266296.0         1340473.0           60899.0

[3 rows x 22 columns]

## Celda 10 — Cálculo de 22 ratios financieros

Código idéntico al paso 5 del pipeline Excel. Los ratios se calculan sobre `valores_por_fecha` y se muestran en un DataFrame por período.

Los resultados son **idénticos a los del pipeline Excel** para los tres ejercicios analizados, lo que valida que el pipeline de imagen produce la misma extracción numérica que la lectura directa del fichero estructurado.

> **Nota sobre la amortización:** en SABI (Excel) la amortización viene en valor absoluto, por lo que `EBITDA = EBIT - amort` es directo. En imágenes exportadas desde SABI el signo también es positivo al proceder del mismo fichero fuente.

In [13]:
# ── PASO 5: calcular ratios ───────────────────────────────────────────────

def safe_div(a, b):
    if a is None or b is None or b == 0: return None
    return round(a / b, 6)

def pct(a, b):   r = safe_div(a, b); return round(r * 100, 2) if r is not None else None
def ratio(a, b): r = safe_div(a, b); return round(r, 2)       if r is not None else None
def dias(a, b):  r = safe_div(a, b); return round(r * 365, 1) if r is not None else None

ratios_calculados = {}

for fecha, v in valores_por_fecha.items():
    cn    = v.get('cifra_negocios')
    oi    = v.get('otros_ingresos_explotacion') or 0
    ebit  = v.get('resultado_explotacion')
    amort = v.get('amortizacion') or 0
    gf    = v.get('gastos_financieros')
    res   = v.get('resultado_ejercicio')
    act   = v.get('total_activo')
    actc  = v.get('activo_corriente')
    exst  = v.get('existencias') or 0
    deud  = v.get('deudores_comerciales')
    efec  = v.get('efectivo') or 0
    fp    = v.get('fondos_propios')
    pasc  = v.get('pasivo_corriente')
    acr   = v.get('acreedores_comerciales')
    delp  = v.get('deuda_credito_lp') or 0
    decp  = v.get('deuda_credito_cp') or 0
    pnc   = v.get('pasivo_no_corriente')

    ebitda  = (ebit - amort)  if ebit  is not None else None
    gf_abs  = abs(gf)         if gf    is not None else None
    pas_tot = (pnc + pasc)    if (pnc  is not None and pasc is not None) else None
    fm      = (actc - pasc)   if (actc is not None and pasc is not None) else None
    deuda_f = delp + decp
    dfn     = deuda_f - efec

    pmc   = dias(deud, cn)
    pmp   = dias(acr,  cn)
    stock = dias(exst, cn)
    ccc   = round((pmc or 0) + (stock or 0) - (pmp or 0), 1) if all(x is not None for x in [pmc, pmp, stock]) else None

    ratios_calculados[fecha] = {
        # Solvencia
        "SOL01_solvencia":              ratio(act, pas_tot),
        "SOL02_autonomia_financiera":   pct(fp, act),
        "SOL03_endeudamiento":          ratio(pas_tot, fp),
        "SOL04_dfn_sobre_fp":           pct(dfn, fp),
        # Cobertura
        "COV01_dfn_sobre_ebitda":       ratio(dfn, ebitda),
        "COV02_icr":                    ratio(ebitda, gf_abs),
        "COV03_carga_financiera_cn":    pct(gf_abs, cn),
        # Liquidez
        "LIQ01_ratio_corriente":        ratio(actc, pasc),
        "LIQ02_ratio_acido":            ratio((actc - exst) if actc is not None else None, pasc),
        "LIQ03_fm_sobre_cn":            pct(fm, cn),
        "LIQ04_tesoreria_sobre_activo": pct(efec, act),
        # Rentabilidad
        "REN01_margen_ebitda":          pct(ebitda, cn),
        "REN02_margen_ebit":            pct(ebit, cn),
        "REN03_margen_neto":            pct(res, cn),
        "REN04_roa":                    pct(ebit, act),
        "REN05_roe":                    pct(res, fp),
        # Apalancamiento
        "APL01_deuda_fin_sobre_activo": pct(deuda_f, act),
        "APL02_pasivo_sobre_activo":    pct(pas_tot, act),
        # Eficiencia
        "EFI01_pmc":   pmc,
        "EFI02_pmp":   pmp,
        "EFI03_stock": stock,
        "EFI04_ccc":   ccc,
    }

df_ratios = pd.DataFrame(ratios_calculados).T
df_ratios

,SOL01_solvencia,SOL02_autonomia_financiera,SOL03_endeudamiento,SOL04_dfn_sobre_fp,COV01_dfn_sobre_ebitda,COV02_icr,COV03_carga_financiera_cn,LIQ01_ratio_corriente,LIQ02_ratio_acido,LIQ03_fm_sobre_cn,...,REN02_margen_ebit,REN03_margen_neto,REN04_roa,REN05_roe,APL01_deuda_fin_sobre_activo,APL02_pasivo_sobre_activo,EFI01_pmc,EFI02_pmp,EFI03_stock,EFI04_ccc
31/12/2024,1.18,15.36,5.52,47.13,1.74,0.88,86.40,1.09,1.05,4.07,...,74.02,-11.86,4.04,-4.22,7.25,84.78,41.6,49.3,6.9,-0.8
31/12/2023,1.19,15.78,5.31,66.69,6.13,0.41,86.77,5.18,5.14,201.36,...,33.16,-39.84,1.58,-12.07,10.62,83.79,47.1,66.3,7.3,-11.9
31/12/2022,1.22,17.72,4.62,60.72,18.94,0.18,82.27,1.09,1.04,4.01,...,12.06,-54.50,0.46,-11.65,10.87,81.83,54.4,62.0,8.5,0.9

---

## Variante: detección de layout en llamada única

Las celdas siguientes implementan una optimización que reduce el consumo de tokens del paso de layout de **N llamadas individuales a 1 sola llamada**, enviando fingerprints compactos de todos los trozos juntos.

**Resultado del experimento:** para 8 trozos, pasar de 8 llamadas (~11.500 tokens) a 1 llamada unificada (~2.967 tokens) supone una reducción del **74% en tokens** con calidad equivalente en el mapeo de columnas.

## Celda 11 — Layout unificado: construcción del mapa compacto y llamada única

Se construye un texto con fingerprints de todos los trozos:
- Del trozo 1 (que tiene cabecera): 20 filas para que el modelo vea las fechas y metadatos.
- De los trozos siguientes: solo 5 filas, suficiente para identificar las columnas de valores.

El prompt pide un JSON con la estructura de columnas de **todos los trozos a la vez**, reduciendo el número de llamadas de N a 1. Se reportan los tokens consumidos para comparar con el enfoque anterior.

In [14]:
bloques = []
for i, df in enumerate(dfs_trozos):
    n_filas = 20 if i == 0 else 5
    
    lineas = []
    for row_idx, row in df.head(n_filas).iterrows():
        for col_name, val in row.items():
            if pd.notna(val) and str(val).strip() not in ("", "nan"):
                lineas.append(f"f{row_idx},c{col_name}:{val}")
    
    bloques.append(f"[TROZO {i+1}]\n" + " | ".join(lineas))

mapa_global = "\n".join(bloques)

prompt = f"""Tienes {len(dfs_trozos)} fragmentos de estados financieros extraídos con OCR.
Fechas del balance en orden: {fechas_canonicas}
Los valores numéricos son importes grandes (ej: 12497590, 418896). Los "n.d." son celdas sin dato.
La columna de partidas contiene descripciones contables (Activo, Pasivo, Existencias...).
El TROZO 1 contiene la cabecera completa con fechas y metadatos.
Los trozos siguientes comparten la misma estructura de columnas que el TROZO 1 pero sin cabecera.
{mapa_global}
Devuelve SOLO este JSON sin markdown:
{{
  "unidades": "mil EUR / EUR / desconocido",
  "trozos": [
    {{"trozo": 1, "col_partidas": "C0", "cols_valores": ["C1","C2","C3"]}},
    {{"trozo": 2, "col_partidas": "C0", "cols_valores": ["C1","C2","C3"]}},
    ...
  ]
}}"""

response = clients[0].chat.completions.create(
    model=MODELO1,
    messages=[{"role": "user", "content": prompt}],
    temperature=0
)

input_tokens  = response.usage.prompt_tokens
output_tokens = response.usage.completion_tokens
total_tokens  = response.usage.total_tokens

print(f"Input tokens:  {input_tokens}")
print(f"Output tokens: {output_tokens}")
print(f"Total tokens:  {total_tokens}")

raw = response.choices[0].message.content.strip().strip("```json").strip("```").strip()
layout_global = json.loads(raw)
print(layout_global)

Input tokens:  2522
Output tokens: 445
Total tokens:  2967
{'unidades': 'mil EUR / EUR / desconocido', 'trozos': [{'trozo': 1, 'col_partidas': 'C0', 'cols_valores': ['C1', 'C2', 'C3']}, {'trozo': 2, 'col_partidas': 'C0', 'cols_valores': ['C1', 'C2', 'C3']}, {'trozo': 3, 'col_partidas': 'C0', 'cols_valores': ['C1', 'C2', 'C3']}, {'trozo': 4, 'col_partidas': 'C0', 'cols_valores': ['C1', 'C2', 'C3']}, {'trozo': 5, 'col_partidas': 'C0', 'cols_valores': ['C1', 'C2', 'C3']}, {'trozo': 6, 'col_partidas': 'C0', 'cols_valores': ['C1', 'C2', 'C3']}, {'trozo': 7, 'col_partidas': 'C0', 'cols_valores': ['C1', 'C2', 'C3']}, {'trozo': 8, 'col_partidas': 'C0', 'cols_valores': ['C1', 'C2', 'C3']}]}

## Celda 12 — Construcción del DataFrame con layout unificado

Mismo proceso que la celda 7 pero usando el layout del JSON unificado (`layout_global`). El resultado final es equivalente, confirmando que la optimización de tokens no penaliza la calidad de extracción.

In [15]:
# Construir lookup: trozo_idx -> {col_partidas, cols_valores}
lookup = {t["trozo"] - 1: t for t in layout_global["trozos"]}

registros = []

for i, df in enumerate(dfs_trozos):
    layout = lookup.get(i)
    if layout is None:
        print(f"⚠️ No hay layout para trozo {i+1}, saltando")
        continue

    col_partidas = layout["col_partidas"]
    cols_valores = layout["cols_valores"]

    col_a_fecha = {cv: cf for cv, cf in zip(cols_valores, fechas_canonicas)}

    for _, row in df.iterrows():
        partida = str(row.get(col_partidas, "")).strip()
        if not partida or partida in ("nan", ""):
            continue
        for col_val, fecha in col_a_fecha.items():
            if col_val not in df.columns:
                continue
            val = str(row.get(col_val, "")).strip()
            try:
                val = float(val)
            except ValueError:
                val = None
            registros.append({"partida": partida, "fecha": fecha, "valor": val, "trozo": i+1})

df_resultado = pd.DataFrame(registros)
pd.set_option('display.max_rows', None)
display(df_resultado)
pd.reset_option('display.max_rows')
df_resultado.to_csv(r"C:\Users\perdi\Desktop\tfm\TFM PYTHON\outputs\balance_final.csv", index=False)

,partida,fecha,valor,trozo
0,Balance/Estadoderesultados,31/12/2024,NaN,1
1,Balance/Estadoderesultados,31/12/2023,NaN,1
2,Balance/Estadoderesultados,31/12/2022,NaN,1
3,CuentasNoConsolidadas,31/12/2024,NaN,1
4,CuentasNoConsolidadas,31/12/2023,NaN,1
5,CuentasNoConsolidadas,31/12/2022,NaN,1
6,Activo,31/12/2024,NaN,1
7,Activo,31/12/2023,NaN,1
8,Activo,31/12/2022,NaN,1
9,A)Activonocorriente,31/12/2024,12497590.0,1
10,A)Activonocorriente,31/12/2023,11416223.0,1
11,A)Activonocorriente,31/12/2022,12647002.0,1
12,IInmovilizadointangible,31/12/2024,23959.0,1
13,IInmovilizadointangible,31/12/2023,19941.0,1
14,IInmovilizadointangible,31/12/2022,23213.0,1
15,1.Fondodecomerciodeconsolidacion,31/12/2024,NaN,1
16,1.Fondodecomerciodeconsolidacion,31/12/2023,NaN,1
17,1.Fondodecomerciodeconsolidacion,31/12/2022,NaN,1
18,2. Investigaci6n,31/12/2024,NaN,1
19,2. Investigaci6n,31/12/2023,NaN,1
20,2. Investigaci6n,31/12/2022,NaN,1
21,3.Propiedad intelectual,31/12/2024,NaN,1
22,3.Propiedad intelectual,31/12/2023,NaN,1
23,3.Propiedad intelectual,31/12/2022,NaN,1
24,5.Otro inmovilizadointangible,31/12/2024,NaN,1
25,5.Otro inmovilizadointangible,31/12/2023,NaN,1
26,5.Otro inmovilizadointangible,31/12/2022,NaN,1
27,IInmovilizadomaterial,31/12/2024,31989.0,1
28,IInmovilizadomaterial,31/12/2023,32524.0,1
29,IInmovilizadomaterial,31/12/2022,35545.0,1
30,1.Terrenosy construcciones,31/12/2024,11064.0,1
31,1.Terrenosy construcciones,31/12/2023,11151.0,1
32,1.Terrenosy construcciones,31/12/2022,11239.0,1
33,2.Instalacionestecnicasy otro inmovilizado mat...,31/12/2024,16685.0,1
34,2.Instalacionestecnicasy otro inmovilizado mat...,31/12/2023,14926.0,1
35,2.Instalacionestecnicasy otro inmovilizado mat...,31/12/2022,18207.0,1
36,3.Inmovilizado en cursoy anticipos,31/12/2024,4240.0,1
37,3.Inmovilizado en cursoy anticipos,31/12/2023,6447.0,1
38,3.Inmovilizado en cursoy anticipos,31/12/2022,6099.0,1
39,I Inversionesinmobiliarias,31/12/2024,102332.0,1
40,I Inversionesinmobiliarias,31/12/2023,108977.0,1
41,I Inversionesinmobiliarias,31/12/2022,80458.0,1
42,IVInversionesenempresasdelgrupoyasociadasalarg...,31/12/2024,11838151.0,1
43,IVInversionesenempresasdelgrupoyasociadasalarg...,31/12/2023,11202474.0,1
44,IVInversionesenempresasdelgrupoyasociadasalarg...,31/12/2022,12469437.0,1
45,1.Participacionespuestas en equivalencia,31/12/2024,NaN,1
46,1.Participacionespuestas en equivalencia,31/12/2023,NaN,1
47,1.Participacionespuestas en equivalencia,31/12/2022,NaN,1
48,2.Creditosasociedadespuestasenequivalencia,31/12/2024,NaN,1
49,2.Creditosasociedadespuestasenequivalencia,31/12/2023,NaN,1
50,2.Creditosasociedadespuestasenequivalencia,31/12/2022,NaN,1
51,3.Otrosactivosfinancieros,31/12/2024,NaN,1
52,3.Otrosactivosfinancieros,31/12/2023,NaN,1
53,3.Otrosactivosfinancieros,31/12/2022,NaN,1
54,4. Otras inversiones,31/12/2024,NaN,1
55,4. Otras inversiones,31/12/2023,NaN,1
56,4. Otras inversiones,31/12/2022,NaN,1
57,VInversionesfinancierasalargoplazo,31/12/2024,418896.0,1
58,VInversionesfinancierasalargoplazo,31/12/2023,2714.0,1
59,VInversionesfinancierasalargoplazo,31/12/2022,29199.0,1
60,VIActivosporimpuestodiferido,31/12/2024,82263.0,1
61,VIActivosporimpuestodiferido,31/12/2023,49593.0,1
62,VIActivosporimpuestodiferido,31/12/2022,9150.0,1
63,VllDeudascomercialesnocorrientes,31/12/2024,NaN,1
64,VllDeudascomercialesnocorrientes,31/12/2023,NaN,1
65,VllDeudascomercialesnocorrientes,31/12/2022,NaN,1
66,B)Activo corriente,31/12/2024,342446.0,1
67,B)Activo corriente,31/12/2023,1544994.0,1
68,B)Activo corriente,31/12/2022,246099.0,1
69,IActivosnocorrientesmantenidosparalaventa,31/12/2024,NaN,1
70,IActivosnocorrientesmantenidosparalaventa,31/12/2023,1360089.0,1
71,IActivosnocorrientesmantenidosparalaventa,31/12/2022,NaN,1
72,IlExistencias,31/12/2024,13342.0,1
73,IlExistencias,31/12/2023,12333.0,1
74,IlExistencias,31/12/2022,11439.0,1
75,IlIDeudorescomercialesyotrascuentasacobrar,31/12/2024,79885.0,1
76,IlIDeudorescomercialesyotrascuentasacobrar,31/12/2023,79873.0,1
77,IlIDeudorescomercialesyotrascuentasacobrar,31/12/2022,72869.0,1
78,2.Creditosasociedadespuestasenequivalencia,31/12/2024,NaN,2
79,2.Creditosasociedadespuestasenequivalencia,31/12/2023,NaN,2
80,2.Creditosasociedadespuestasenequivalencia,31/12/2022,NaN,2
81,3.Otros activos financieros,31/12/2024,NaN,2
82,3.Otros activos financieros,31/12/2023,NaN,2
83,3.Otros activos financieros,31/12/2022,NaN,2
84,4.Otras inversiones,31/12/2024,NaN,2
85,4.Otras inversiones,31/12/2023,NaN,2
86,4.Otras inversiones,31/12/2022,NaN,2
87,VInversionesfinancierasalargoplazo,31/12/2024,418896.0,2
88,VInversionesfinancierasalargoplazo,31/12/2023,2714.0,2
89,VInversionesfinancierasalargoplazo,31/12/2022,29199.0,2
90,VIActivosporimpuestodiferido,31/12/2024,82263.0,2
91,VIActivosporimpuestodiferido,31/12/2023,49593.0,2
92,VIActivosporimpuestodiferido,31/12/2022,9150.0,2
93,VllDeudascomercialesnocorrientes,31/12/2024,NaN,2
94,VllDeudascomercialesnocorrientes,31/12/2023,NaN,2
95,VllDeudascomercialesnocorrientes,31/12/2022,NaN,2
96,B)Activo corriente,31/12/2024,342446.0,2
97,B)Activo corriente,31/12/2023,1544994.0,2
98,B)Activo corriente,31/12/2022,246099.0,2
99,IActivosnocorrientesmantenidosparalaventa,31/12/2024,NaN,2
100,IActivosnocorrientesmantenidosparalaventa,31/12/2023,1360089.0,2
101,IActivosnocorrientesmantenidosparalaventa,31/12/2022,NaN,2
102,IIExistencias,31/12/2024,13342.0,2
103,IIExistencias,31/12/2023,12333.0,2
104,IIExistencias,31/12/2022,11439.0,2
105,IllDeudorescomercialesyotrascuentasacobrar,31/12/2024,79885.0,2
106,IllDeudorescomercialesyotrascuentasacobrar,31/12/2023,79873.0,2
107,IllDeudorescomercialesyotrascuentasacobrar,31/12/2022,72869.0,2
108,1.Clientesporventasyprestacionesdeservicios,31/12/2024,1496.0,2
109,1.Clientesporventasyprestacionesdeservicios,31/12/2023,581.0,2
110,1.Clientesporventasyprestacionesdeservicios,31/12/2022,833.0,2
111,a)Clientesporventasyprestacionesdeserviciosa l...,31/12/2024,NaN,2
112,a)Clientesporventasyprestacionesdeserviciosa l...,31/12/2023,NaN,2
113,a)Clientesporventasyprestacionesdeserviciosa l...,31/12/2022,NaN,2
114,b) Clientes por ventasy prestaciones deservici...,31/12/2024,1496.0,2
115,b) Clientes por ventasy prestaciones deservici...,31/12/2023,581.0,2
116,b) Clientes por ventasy prestaciones deservici...,31/12/2022,833.0,2
117,2.Sociedadespuestas enequivalencia,31/12/2024,NaN,2
118,2.Sociedadespuestas enequivalencia,31/12/2023,NaN,2
119,2.Sociedadespuestas enequivalencia,31/12/2022,NaN,2
120,3.Activos porimpuesto corriente,31/12/2024,16453.0,2
121,3.Activos porimpuesto corriente,31/12/2023,12303.0,2
122,3.Activos porimpuesto corriente,31/12/2022,2486.0,2
123,4.Otrosdeudores,31/12/2024,NaN,2
124,4.Otrosdeudores,31/12/2023,NaN,2
125,4.Otrosdeudores,31/12/2022,NaN,2
126,IVInversionesenempresasdelgrupoyasociadasacort...,31/12/2024,228981.0,2
127,IVInversionesenempresasdelgrupoyasociadasacort...,31/12/2023,47884.0,2
128,IVInversionesenempresasdelgrupoyasociadasacort...,31/12/2022,123033.0,2
129,1.Creditos a empresaspuestos enequivalencia,31/12/2024,NaN,2
130,1.Creditos a empresaspuestos enequivalencia,31/12/2023,NaN,2
131,1.Creditos a empresaspuestos enequivalencia,31/12/2022,NaN,2
132,2.Otros activos financieros,31/12/2024,NaN,2
133,2.Otros activos financieros,31/12/2023,NaN,2
134,2.Otros activos financieros,31/12/2022,NaN,2
135,3.Otras inversiones,31/12/2024,NaN,2
136,3.Otras inversiones,31/12/2023,NaN,2
137,3.Otras inversiones,31/12/2022,NaN,2
138,VInversionesfinancierasa cortoplazo,31/12/2024,2752.0,2
139,VInversionesfinancierasa cortoplazo,31/12/2023,20917.0,2
140,VInversionesfinancierasa cortoplazo,31/12/2022,11569.0,2
141,VIPeriodificacionesacortoplazo,31/12/2024,16203.0,2
142,VIPeriodificacionesacortoplazo,31/12/2023,11031.0,2
143,VIPeriodificacionesacortoplazo,31/12/2022,13511.0,2
144,VllEfectivoyotrosactivoslfquidosequivalentes,31/12/2024,1283.0,2
145,VllEfectivoyotrosactivoslfquidosequivalentes,31/12/2023,12867.0,2
146,VllEfectivoyotrosactivoslfquidosequivalentes,31/12/2022,13678.0,2
147,Total activo (A + B),31/12/2024,12840036.0,2
148,Total activo (A + B),31/12/2023,12961217.0,2
149,Total activo (A + B),31/12/2022,12893101.0,2
150,Pasivo,31/12/2024,NaN,2
151,Pasivo,31/12/2023,NaN,2
152,Pasivo,31/12/2022,NaN,2
153,A)Patrimonioneto,31/12/2024,1953852.0,2
154,A)Patrimonioneto,31/12/2023,2101487.0,2
155,A)Patrimonioneto,31/12/2022,2343125.0,2
156,A-1) Fondos propios,31/12/2024,1972243.0,2
157,A-1) Fondos propios,31/12/2023,2044735.0,2
158,A-1) Fondos propios,31/12/2022,2285248.0,2
159,ICapital,31/12/2024,119604.0,2
160,ICapital,31/12/2023,119604.0,2
161,ICapital,31/12/2022,119604.0,2
162,1.Capital escriturado,31/12/2024,119604.0,2
163,1.Capital escriturado,31/12/2023,119604.0,2
164,1.Capital escriturado,31/12/2022,119604.0,2
165,2. (Capital no exigido),31/12/2024,NaN,2
166,2. (Capital no exigido),31/12/2023,NaN,2
167,2. (Capital no exigido),31/12/2022,NaN,2
168,IlPrima de emision,31/12/2024,910728.0,2
169,IlPrima de emision,31/12/2023,910728.0,2
170,IlPrima de emision,31/12/2022,910728.0,2
171,1.Reserva derevalorizaci6n,31/12/2024,NaN,2
172,1.Reserva derevalorizaci6n,31/12/2023,NaN,2
173,1.Reserva derevalorizaci6n,31/12/2022,NaN,2
174,2.Reserva de capitalizacion,31/12/2024,NaN,2
175,2.Reserva de capitalizacion,31/12/2023,NaN,2
176,2.Reserva de capitalizacion,31/12/2022,NaN,2
177,3.Otras reservas,31/12/2024,NaN,2
178,3.Otras reservas,31/12/2023,NaN,2
179,3.Otras reservas,31/12/2022,NaN,2
180,I Reservasyresultadosdeejerciciosanteriores,31/12/2024,NaN,2
181,I Reservasyresultadosdeejerciciosanteriores,31/12/2023,NaN,2
182,I Reservasyresultadosdeejerciciosanteriores,31/12/2022,NaN,2
183,IV (Acciones y participaciones en patrimonio p...,31/12/2024,-134448.0,2
184,IV (Acciones y participaciones en patrimonio p...,31/12/2023,-152748.0,2
185,IV (Acciones y participaciones en patrimonio p...,31/12/2022,-162220.0,2
186,VOtras aportacionesdesocios,31/12/2024,NaN,2
187,VOtras aportacionesdesocios,31/12/2023,NaN,2
188,VOtras aportacionesdesocios,31/12/2022,NaN,2
189,nante,31/12/2024,-83138.0,2
190,nante,31/12/2023,246735.0,2
191,nante,31/12/2022,266296.0,2
192,A-1)Fondospropios,31/12/2024,1972243.0,3
193,A-1)Fondospropios,31/12/2023,2044735.0,3
194,A-1)Fondospropios,31/12/2022,2285248.0,3
195,ICapital,31/12/2024,119604.0,3
196,ICapital,31/12/2023,119604.0,3
197,ICapital,31/12/2022,119604.0,3
198,1.Capital escriturado,31/12/2024,119604.0,3
199,1.Capital escriturado,31/12/2023,119604.0,3
200,1.Capital escriturado,31/12/2022,119604.0,3
201,2. (Capital no exigido),31/12/2024,NaN,3
202,2. (Capital no exigido),31/12/2023,NaN,3
203,2. (Capital no exigido),31/12/2022,NaN,3
204,IlPrima de emision,31/12/2024,910728.0,3
205,IlPrima de emision,31/12/2023,910728.0,3
206,IlPrima de emision,31/12/2022,910728.0,3
207,1.Reserva derevalorizacion,31/12/2024,NaN,3
208,1.Reserva derevalorizacion,31/12/2023,NaN,3
209,1.Reserva derevalorizacion,31/12/2022,NaN,3
210,2.Reserva de capitalizacion,31/12/2024,NaN,3
211,2.Reserva de capitalizacion,31/12/2023,NaN,3
212,2.Reserva de capitalizacion,31/12/2022,NaN,3
213,3.Otrasreservas,31/12/2024,NaN,3
214,3.Otrasreservas,31/12/2023,NaN,3
215,3.Otrasreservas,31/12/2022,NaN,3
216,Il Reservasyresultadosdeejerciciosanteriores,31/12/2024,NaN,3
217,Il Reservasyresultadosdeejerciciosanteriores,31/12/2023,NaN,3
218,Il Reservasyresultadosdeejerciciosanteriores,31/12/2022,NaN,3
219,IV(Accionesyparticipacionesenpatrimoniopropias...,31/12/2024,-134448.0,3
220,IV(Accionesyparticipacionesenpatrimoniopropias...,31/12/2023,-152748.0,3
221,IV(Accionesyparticipacionesenpatrimoniopropias...,31/12/2022,-162220.0,3
222,V Otrasaportacionesdesocios,31/12/2024,NaN,3
223,V Otrasaportacionesdesocios,31/12/2023,NaN,3
224,V Otrasaportacionesdesocios,31/12/2022,NaN,3
225,VIResultadodelejercicioatribuidoalasociedaddom...,31/12/2024,-83138.0,3
226,VIResultadodelejercicioatribuidoalasociedaddom...,31/12/2023,-246735.0,3
227,VIResultadodelejercicioatribuidoalasociedaddom...,31/12/2022,-266296.0,3
228,VllDividendoacuenta),31/12/2024,NaN,3
229,VllDividendoacuenta),31/12/2023,NaN,3
230,VllDividendoacuenta),31/12/2022,NaN,3
231,VIllOtrosinstrumentos depatrimonioneto,31/12/2024,6647.0,3
232,VIllOtrosinstrumentos depatrimonioneto,31/12/2023,8282.0,3
233,VIllOtrosinstrumentos depatrimonioneto,31/12/2022,7303.0,3
234,A-2)Ajustesporcambiosdevalor,31/12/2024,-18391.0,3
235,A-2)Ajustesporcambiosdevalor,31/12/2023,56752.0,3
236,A-2)Ajustesporcambiosdevalor,31/12/2022,57798.0,3
237,"IActivosnocorrientesypasivosvinculados,manteni...",31/12/2024,NaN,3
238,"IActivosnocorrientesypasivosvinculados,manteni...",31/12/2023,NaN,3
239,"IActivosnocorrientesypasivosvinculados,manteni...",31/12/2022,NaN,3
240,IDiferenciadeconversi6n,31/12/2024,NaN,3
241,IDiferenciadeconversi6n,31/12/2023,NaN,3
242,IDiferenciadeconversi6n,31/12/2022,NaN,3
243,IlOtros,31/12/2024,NaN,3
244,IlOtros,31/12/2023,NaN,3
245,IlOtros,31/12/2022,NaN,3
246,"A-3)Subvenciones,donacionesylegadosrecibidos",31/12/2024,NaN,3
247,"A-3)Subvenciones,donacionesylegadosrecibidos",31/12/2023,NaN,3
248,"A-3)Subvenciones,donacionesylegadosrecibidos",31/12/2022,79.0,3
249,A-4)Sociosextemos,31/12/2024,NaN,3
250,A-4)Sociosextemos,31/12/2023,NaN,3
251,A-4)Sociosextemos,31/12/2022,NaN,3
252,B)Pasivonocorriente,31/12/2024,10572251.0,3
253,B)Pasivonocorriente,31/12/2023,10561625.0,3
254,B)Pasivonocorriente,31/12/2022,10323483.0,3
255,IProvisionesalargoplazo,31/12/2024,3217.0,3
256,IProvisionesalargoplazo,31/12/2023,3838.0,3
257,IProvisionesalargoplazo,31/12/2022,NaN,3
258,IIDeudas a largoplazo,31/12/2024,6288936.0,3
259,IIDeudas a largoplazo,31/12/2023,5879325.0,3
260,IIDeudas a largoplazo,31/12/2022,3901732.0,3
261,1.obligacionesy otrosvaloresnegociables,31/12/2024,5387413.0,3
262,1.obligacionesy otrosvaloresnegociables,31/12/2023,4571059.0,3
263,1.obligacionesy otrosvaloresnegociables,31/12/2022,2556641.0,3
264,2.Deudasconentidadesdecredito,31/12/2024,901345.0,3
265,2.Deudasconentidadesdecredito,31/12/2023,1308026.0,3
266,2.Deudasconentidadesdecredito,31/12/2022,1340473.0,3
267,3.Acreedoresporarrendamientofinanciero,31/12/2024,21.0,3
268,3.Acreedoresporarrendamientofinanciero,31/12/2023,27.0,3
269,3.Acreedoresporarrendamientofinanciero,31/12/2022,52.0,3
270,4. Otros pasivos financieros,31/12/2024,NaN,3
271,4. Otros pasivos financieros,31/12/2023,NaN,3
272,4. Otros pasivos financieros,31/12/2022,NaN,3
273,IIDeudasconempresasdelgrupoyasociadasalargoplazo,31/12/2024,4276854.0,3
274,IIDeudasconempresasdelgrupoyasociadasalargoplazo,31/12/2023,4673555.0,3
275,IIDeudasconempresasdelgrupoyasociadasalargoplazo,31/12/2022,6419171.0,3
276,1.Deudasconsociedadespuestaenequivalencia,31/12/2024,NaN,3
277,1.Deudasconsociedadespuestaenequivalencia,31/12/2023,NaN,3
278,1.Deudasconsociedadespuestaenequivalencia,31/12/2022,NaN,3
279,2. Otras deudas,31/12/2024,NaN,3
280,2. Otras deudas,31/12/2023,NaN,3
281,2. Otras deudas,31/12/2022,NaN,3
282,IVPasivos porimpuesto diferido,31/12/2024,3244.0,3
283,IVPasivos porimpuesto diferido,31/12/2023,4907.0,3
284,IVPasivos porimpuesto diferido,31/12/2022,2580.0,3
285,VPeriodificacionesa largoplazo,31/12/2024,NaN,3
286,VPeriodificacionesa largoplazo,31/12/2023,NaN,3
287,VPeriodificacionesa largoplazo,31/12/2022,NaN,3
288,VIAcreedorescomercialesnocorientes,31/12/2024,NaN,3
289,VIAcreedorescomercialesnocorientes,31/12/2023,NaN,3
290,VIAcreedorescomercialesnocorientes,31/12/2022,NaN,3
291,VllDeuda concaracteristicas especialesa largop...,31/12/2024,NaN,3
292,VllDeuda concaracteristicas especialesa largop...,31/12/2023,NaN,3
293,VllDeuda concaracteristicas especialesa largop...,31/12/2022,NaN,3
294,C)Pasivo corriente,31/12/2024,313933.0,3
295,C)Pasivo corriente,31/12/2023,298105.0,3
296,C)Pasivo corriente,31/12/2022,226493.0,3
297,3.Acreedoresporarrendamientofinanciero,31/12/2024,NaN,4
298,3.Acreedoresporarrendamientofinanciero,31/12/2023,NaN,4
299,3.Acreedoresporarrendamientofinanciero,31/12/2022,52.0,4
300,4. Otros pasivos financieros,31/12/2024,NaN,4
301,4. Otros pasivos financieros,31/12/2023,NaN,4
302,4. Otros pasivos financieros,31/12/2022,NaN,4
303,IlI Deudasconempresasdel grupoyasociadas alarg...,31/12/2024,4276854.0,4
304,IlI Deudasconempresasdel grupoyasociadas alarg...,31/12/2023,4673555.0,4
305,IlI Deudasconempresasdel grupoyasociadas alarg...,31/12/2022,6419171.0,4
306,1.Deudasconsociedadespuestaenequivalencia,31/12/2024,NaN,4
307,1.Deudasconsociedadespuestaenequivalencia,31/12/2023,NaN,4
308,1.Deudasconsociedadespuestaenequivalencia,31/12/2022,NaN,4
309,2.Otras deudas,31/12/2024,NaN,4
310,2.Otras deudas,31/12/2023,NaN,4
311,2.Otras deudas,31/12/2022,NaN,4
312,IVPasivosporimpuestodiferido,31/12/2024,3244.0,4
313,IVPasivosporimpuestodiferido,31/12/2023,4907.0,4
314,IVPasivosporimpuestodiferido,31/12/2022,2580.0,4
315,VPeriodificacionesalargoplazo,31/12/2024,NaN,4
316,VPeriodificacionesalargoplazo,31/12/2023,NaN,4
317,VPeriodificacionesalargoplazo,31/12/2022,NaN,4
318,VIAcreedorescomercialesnocorrientes,31/12/2024,NaN,4
319,VIAcreedorescomercialesnocorrientes,31/12/2023,NaN,4
320,VIAcreedorescomercialesnocorrientes,31/12/2022,NaN,4
321,VllDeudaconcaracteristicasespecialesalargoplazo,31/12/2024,NaN,4
322,VllDeudaconcaracteristicasespecialesalargoplazo,31/12/2023,NaN,4
323,VllDeudaconcaracteristicasespecialesalargoplazo,31/12/2022,NaN,4
324,C)Pasivo corriente,31/12/2024,313933.0,4
325,C)Pasivo corriente,31/12/2023,298105.0,4
326,C)Pasivo corriente,31/12/2022,226493.0,4
327,IPasivosvinculadosconactivosnocorrientesmanten...,31/12/2024,NaN,4
328,IPasivosvinculadosconactivosnocorrientesmanten...,31/12/2023,NaN,4
329,IPasivosvinculadosconactivosnocorrientesmanten...,31/12/2022,NaN,4
330,IIProvisiones a cortoplazo,31/12/2024,79947.0,4
331,IIProvisiones a cortoplazo,31/12/2023,14000.0,4
332,IIProvisiones a cortoplazo,31/12/2022,7000.0,4
333,1.Provisionesporderechosdeemisiondegasesdeefec...,31/12/2024,NaN,4
334,1.Provisionesporderechosdeemisiondegasesdeefec...,31/12/2023,NaN,4
335,1.Provisionesporderechosdeemisiondegasesdeefec...,31/12/2022,NaN,4
336,2. Otras provisiones,31/12/2024,79947.0,4
337,2. Otras provisiones,31/12/2023,14000.0,4
338,2. Otras provisiones,31/12/2022,7000.0,4
339,IIDeudasacortoplazo,31/12/2024,68347.0,4
340,IIDeudasacortoplazo,31/12/2023,106970.0,4
341,IIDeudasacortoplazo,31/12/2022,74786.0,4
342,1. Obligaciones y otros valores negociables,31/12/2024,38907.0,4
343,1. Obligaciones y otros valores negociables,31/12/2023,30170.0,4
344,1. Obligaciones y otros valores negociables,31/12/2022,12554.0,4
345,2.Deudas conentidades decredito,31/12/2024,29383.0,4
346,2.Deudas conentidades decredito,31/12/2023,68542.0,4
347,2.Deudas conentidades decredito,31/12/2022,60899.0,4
348,3.Acreedoresporarrendamientofinanciero,31/12/2024,NaN,4
349,3.Acreedoresporarrendamientofinanciero,31/12/2023,25.0,4
350,3.Acreedoresporarrendamientofinanciero,31/12/2022,391.0,4
351,4. Otros pasivos financieros,31/12/2024,NaN,4
352,4. Otros pasivos financieros,31/12/2023,NaN,4
353,4. Otros pasivos financieros,31/12/2022,NaN,4
354,IVDeudasconempresasdel grupoyasociadasa cortop...,31/12/2024,62437.0,4
355,IVDeudasconempresasdel grupoyasociadasa cortop...,31/12/2023,64699.0,4
356,IVDeudasconempresasdel grupoyasociadasa cortop...,31/12/2022,61720.0,4
357,1.Deudas consociedadespuesta en equivalencia,31/12/2024,NaN,4
358,1.Deudas consociedadespuesta en equivalencia,31/12/2023,NaN,4
359,1.Deudas consociedadespuesta en equivalencia,31/12/2022,NaN,4
360,2.Otrasdeudas,31/12/2024,NaN,4
361,2.Otrasdeudas,31/12/2023,NaN,4
362,2.Otrasdeudas,31/12/2022,NaN,4
363,VAcreedorescomercialesyotrascuentasapagar,31/12/2024,94624.0,4
364,VAcreedorescomercialesyotrascuentasapagar,31/12/2023,112436.0,4
365,VAcreedorescomercialesyotrascuentasapagar,31/12/2022,82987.0,4
366,1.Proveedores,31/12/2024,65750.0,4
367,1.Proveedores,31/12/2023,69365.0,4
368,1.Proveedores,31/12/2022,58812.0,4
369,a)Proveedores a largo plazo,31/12/2024,NaN,4
370,a)Proveedores a largo plazo,31/12/2023,NaN,4
371,a)Proveedores a largo plazo,31/12/2022,NaN,4
372,b)Proveedores a cortoplazo,31/12/2024,65750.0,4